export interface StaticConceptItem {
  id: string;
  slug: string;
  title: string;
  shortDefinition: string;
  difficulty: string;
  topicTitle: string;
  subjectName: string;
}

export const STATIC_CONCEPT_INDEX: StaticConceptItem[] = [
  // =========================================================================
  // TOPIC 1: BASIC CONCEPTS OF POLITY (4 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T1-01',
    slug: 'state-and-nation-constituent-elements-saptanga-theory',
    title: 'The State and Nation: Constituent Elements, Saptanga Theory & Distinctions',
    shortDefinition: 'The State as a sovereign political-legal entity defined by four elements (territory, population, government, sovereignty), Kautilya’s Saptanga model, and Nation distinction.',
    difficulty: 'BEGINNER',
    topicTitle: 'Basic Concepts of Polity',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T1-02',
    slug: 'theories-of-origin-of-state-divine-social-contract-marxist',
    title: 'Theories of the Origin of the State: Divine, Social Contract, Historical & Marxist',
    shortDefinition: 'Philosophical accounts of state emergence: Divine Origin, Social Contract (Hobbes, Locke, Rousseau overcoming Matsya Nyaya), and Evolutionary models.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Basic Concepts of Polity',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T1-03',
    slug: 'systems-of-governance-parliamentary-presidential-constitutional-supremacy',
    title: 'Systems of Governance: Parliamentary vs Presidential & Constitutional Supremacy',
    shortDefinition: 'Dual Legislature/Executive in India, Unified Judiciary, Parliamentary executive-legislative fusion vs US Separation of Powers, and UK Parliamentary Sovereignty vs Indian Constitutional Supremacy.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Basic Concepts of Polity',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T1-04',
    slug: 'constitution-and-constitutionalism-nature-functions-pillars',
    title: 'Constitution & Constitutionalism: Nature, Functions & Pillars of Limited Government',
    shortDefinition: 'The Constitution as supreme organic law versus Constitutionalism as the philosophy of limited government, rule of law, and institutional restraint.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Basic Concepts of Polity',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 2: CONSTITUENT ASSEMBLY (6 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T2-01',
    slug: 'historical-evolution-demand-for-constituent-assembly',
    title: 'Historical Evolution & Demand for the Constituent Assembly (1895–1946)',
    shortDefinition: 'Progression from Tilak’s Swaraj Bill (1895) and Nehru Report (1928) to M.N. Roy (1934), INC demands, August Offer (1940), Cripps Mission (1942), and Cabinet Mission (1946).',
    difficulty: 'BEGINNER',
    topicTitle: 'Constituent Assembly of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T2-02',
    slug: 'composition-election-restructuring-constituent-assembly',
    title: 'Composition, Election Framework & Restructuring of the Constituent Assembly',
    shortDefinition: 'Original 389-seat architecture (292 Provinces, 93 Princely States, 4 Chief Commissioner Provinces), indirect proportional voting via STV, and post-partition reduction to 299 seats.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Constituent Assembly of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T2-03',
    slug: 'functioning-working-timeline-dual-roles-constituent-assembly',
    title: 'Functioning, Working Timeline & Dual Roles of the Constituent Assembly',
    shortDefinition: 'Dec 9, 1946 opening, leadership appointments, Objectives Resolution, dual role as Constitution-maker and Provisional Parliament, adoption on Nov 26, 1949, and commencement on Jan 26, 1950.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Constituent Assembly of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T2-04',
    slug: 'committees-of-constituent-assembly-and-drafting-committee',
    title: 'Committees of the Constituent Assembly & The Drafting Committee',
    shortDefinition: 'Division of labor across 8 major committees and the 7-member Drafting Committee chaired by Dr. B.R. Ambedkar appointed on August 29, 1947.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Constituent Assembly of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T2-05',
    slug: 'sources-of-the-indian-constitution-borrowing-matrix',
    title: 'Major Sources Borrowed & Constitutional Borrowing Matrix',
    shortDefinition: 'Systematic borrowing from the 1935 Act and 10 world democracies (UK, USA, Ireland, Canada, Australia, Germany, USSR, France, South Africa, Japan).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Constituent Assembly of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T2-06',
    slug: 'constituent-assembly-rajasthan-representation-criticisms',
    title: 'Constituent Assembly: Rajasthan Representation, Critical Appraisals & Rebuttals',
    shortDefinition: 'The 14 representative members from Rajasthan, key officers/calligraphers, and comprehensive intellectual rebuttals to classical criticisms.',
    difficulty: 'ADVANCED',
    topicTitle: 'Constituent Assembly of India',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 3: PREAMBLE (4 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T3-01',
    slug: 'preamble-historical-genesis-text-authority-jurist-views',
    title: 'Preamble: Historical Genesis, Text, Source of Authority & Eminent Perspectives',
    shortDefinition: 'Nehru’s Objectives Resolution (1946), verbatim text enacted on Oct 17, 1949, popular sovereignty ("We the People"), and jurist characterizations (Palkhivala, Munshi, Bhargava).',
    difficulty: 'BEGINNER',
    topicTitle: 'The Preamble of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T3-02',
    slug: 'nature-of-indian-state-sovereign-socialist-secular-democratic-republic',
    title: 'Nature of the Indian State: Sovereign, Socialist, Secular, Democratic, Republic',
    shortDefinition: 'Internal-external sovereignty, democratic socialism, positive secularism (Sarva Dharma Sambhava / Bommai basic structure), representative democracy, and republican headship.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'The Preamble of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T3-03',
    slug: 'constitutional-objectives-justice-liberty-equality-fraternity',
    title: 'Constitutional Objectives: Justice, Liberty, Equality, Fraternity & Dignity',
    shortDefinition: 'Four grand ideals: three-dimensional Justice (Social, Economic, Political from Russia 1917), bounded Liberty (France 1789), Equality, and Fraternity with Dignity & Integrity.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'The Preamble of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T3-04',
    slug: 'status-justiciability-amendability-of-the-preamble',
    title: 'Constitutional Status, Justiciability & Amendability of the Preamble',
    shortDefinition: 'Berubari (1960) to Kesavananda (1973) and LIC (1995), non-justiciable character, and the 42nd Amendment (Socialist, Secular, Integrity).',
    difficulty: 'ADVANCED',
    topicTitle: 'The Preamble of the Indian Constitution',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 4: SCHEDULES (8 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T4-01',
    slug: 'schedules-overview-evolution-and-structural-matrix',
    title: 'Overview, Evolution & Structural Matrix of the 12 Schedules',
    shortDefinition: 'Functional role of Schedules, expansion from 8 in 1949 to 12 today via 1st, 52nd, 73rd, 74th Amendments, and direct substantive Article anchorage.',
    difficulty: 'BEGINNER',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-02',
    slug: 'schedules-1-to-4-territory-emoluments-oaths-rajya-sabha',
    title: 'Schedules 1 to 4: Territory, Emoluments, Oaths and Rajya Sabha Seat Allocation',
    shortDefinition: '1st Schedule (28 States & 8 UTs), 2nd Schedule (emoluments; Ministers excluded), 3rd Schedule (oaths; President/VP/Governor excluded), and 4th Schedule (RS seats).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-03',
    slug: 'schedules-5-and-6-scheduled-and-tribal-areas-administration',
    title: 'Schedules 5 and 6: Administration of Scheduled & Tribal Areas',
    shortDefinition: '5th Schedule administration in 10 states via TACs and Governor regulations vs 6th Schedule Autonomous District Councils in the 4 NE states (AMTM).',
    difficulty: 'ADVANCED',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-04',
    slug: '7th-schedule-division-of-powers-lists-and-residuary-power',
    title: '7th Schedule: Legislative Lists, Division of Powers & Residuary Powers',
    shortDefinition: 'Article 246 division across Union (100), State (61), Concurrent (52) lists, 42nd Amendment shift of 5 subjects, and Canadian-style Residuary Powers (Art 248).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-05',
    slug: '8th-schedule-22-official-languages-classical-languages',
    title: '8th Schedule: 22 Official Languages, Classical Languages & Amendments',
    shortDefinition: '14 original to 22 languages today across 21st, 71st, 92nd Amendments, English/Rajasthani exclusions, and 11 Classical Languages (incl. 2024 additions).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-06',
    slug: '9th-schedule-land-reforms-protective-umbrella-ir-coelho',
    title: '9th Schedule: Land Reforms, Protective Umbrella & The I.R. Coelho Doctrine',
    shortDefinition: '1st Amendment (1951) + Art 31B protecting land reforms, growth to 284 laws, and 9-judge I.R. Coelho ruling (2007) subjecting post-1973 laws to Basic Structure review.',
    difficulty: 'ADVANCED',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-07',
    slug: '10th-schedule-anti-defection-law-exceptions-judicial-evolution',
    title: '10th Schedule: Anti-Defection Law, Exceptions & Judicial Evolution',
    shortDefinition: '52nd Amendment (1985) and 91st Amendment (2003): disqualification grounds, British Whip convention, Kihoto Holohan (1992), and Keisham Meghchandra (2020).',
    difficulty: 'ADVANCED',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-08',
    slug: '11th-and-12th-schedules-local-governance-devolutions',
    title: '11th and 12th Schedules: Panchayati Raj & Municipal Functional Devolutions',
    shortDefinition: '73rd and 74th Amendments (1992): 11th Schedule (29 functional subjects for Panchayats) and 12th Schedule (18 functional subjects for Municipalities).',
    difficulty: 'BEGINNER',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 9: PART III FUNDAMENTAL RIGHTS (16 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T9-01',
    slug: 'part-3-overview-nature-of-fundamental-rights',
    title: 'Part III: Overview & Magna Carta of India',
    shortDefinition: 'Constitutional charter of fundamental rights under Articles 12 to 35, justifiable against state action.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-02',
    slug: 'article-12-definition-of-state',
    title: 'Article 12: Definition of State & Other Authorities',
    shortDefinition: 'Constitutional definition of State encompassing legislative, executive, statutory, and instrumentality bodies.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-03',
    slug: 'article-13-judicial-review-doctrines',
    title: 'Article 13: Laws Inconsistent with Fundamental Rights',
    shortDefinition: 'Constitutional shield establishing judicial review, doctrine of severability, eclipse, and waiver.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-04',
    slug: 'article-14-equality-non-arbitrariness',
    title: 'Article 14: Right to Equality & Non-Arbitrariness Doctrine',
    shortDefinition: 'Universal equality before law and equal protection of laws, proscribing state arbitrariness.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-05',
    slug: 'articles-15-16-reservations-protective-discrimination',
    title: 'Articles 15 & 16: Prohibition of Discrimination & Public Employment Reservations',
    shortDefinition: 'Constitutional framework for protective discrimination, affirmative action, and public employment quotas.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-06',
    slug: 'articles-17-18-abolition-untouchability-titles',
    title: 'Articles 17 & 18: Abolition of Untouchability & Titles',
    shortDefinition: 'Absolute constitutional abolition of untouchability and prohibition of noble and aristocratic titles.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-07',
    slug: 'article-19-six-freedoms-reasonable-restrictions',
    title: 'Article 19: Six Democratic Freedoms & Reasonable Restrictions',
    shortDefinition: 'Six fundamental democratic freedoms guaranteed to citizens with exhaustive grounds of reasonable restrictions.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-08',
    slug: 'article-20-protection-conviction-offences',
    title: 'Article 20: Protection in Respect of Conviction for Offences',
    shortDefinition: 'Inviolable criminal safeguards against ex-post facto laws, double jeopardy, and self-incrimination.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-09',
    slug: 'article-21-21a-life-liberty-privacy-education',
    title: 'Articles 21 & 21A: Right to Life, Personal Liberty, Privacy & Education',
    shortDefinition: 'Procedural due process under Maneka Gandhi, fundamental right to privacy under Puttaswamy, and right to education.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-10',
    slug: 'article-22-preventive-detention-safeguards',
    title: 'Article 22: Protection Against Arrest & Preventive Detention Safeguards',
    shortDefinition: 'Constitutional balance between punitive procedural rights and preventive detention safeguards.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-11',
    slug: 'articles-23-24-right-against-exploitation',
    title: 'Articles 23 & 24: Right Against Exploitation & Child Labour Prohibition',
    shortDefinition: 'Constitutional prohibitions against human trafficking, begar, forced labor, and hazardous child employment.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-12',
    slug: 'articles-25-28-freedom-of-religion-secularism',
    title: 'Articles 25 to 28: Freedom of Religion & Secularism',
    shortDefinition: 'Individual religious conscience, denominational autonomy, and the positive secularism architecture.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-13',
    slug: 'articles-29-30-cultural-educational-rights-minorities',
    title: 'Articles 29 & 30: Cultural & Educational Rights of Minorities',
    shortDefinition: 'Preservation of distinct language, script, culture, and minority rights to establish and administer educational institutions.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-14',
    slug: 'articles-31a-31b-31c-saving-certain-laws',
    title: 'Articles 31A, 31B & 31C: Constitutional Savings of Agrarian & Welfare Laws',
    shortDefinition: 'Protective constitutional umbrellas shielding agrarian reforms, Ninth Schedule statutes, and socialist directive principles.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-15',
    slug: 'article-32-constitutional-remedies-prerogative-writs',
    title: 'Article 32: Right to Constitutional Remedies & Five Prerogative Writs',
    shortDefinition: 'The cornerstone and heart of the Constitution providing direct access to the Supreme Court via five prerogative writs.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-16',
    slug: 'articles-33-35-armed-forces-martial-law-legislation',
    title: 'Articles 33, 34 & 35: Armed Forces Modifications, Martial Law & Legislative Exclusivity',
    shortDefinition: 'Parliamentary restrictions on armed forces rights, indemnity during martial law, and Union legislative exclusivity for Part III.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 10: DIRECTIVE PRINCIPLES (5 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T10-01',
    slug: 'part-4-nature-philosophy-non-justiciability-dpsp',
    title: 'Part IV: Nature, Philosophy & Non-Justiciability of DPSPs',
    shortDefinition: 'Instrument of Instructions for socio-economic democracy, moral imperatives, and non-justiciable character under Article 37.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T10-02',
    slug: 'socialistic-gandhian-liberal-intellectual-classification',
    title: 'Socialistic, Gandhian & Liberal-Intellectual Classification of DPSPs',
    shortDefinition: 'Tripartite philosophical taxonomy of welfare principles spanning Articles 38 to 51.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T10-03',
    slug: 'amendments-to-part-4-42nd-44th-86th-97th',
    title: 'Constitutional Amendments to Part IV: 42nd, 44th, 86th & 97th Amendments',
    shortDefinition: 'Evolution of DPSPs through constitutional amendments introducing legal aid, worker participation, early childhood care, and cooperatives.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T10-04',
    slug: 'fundamental-rights-vs-dpsp-judicial-reconciliation-minerva-mills',
    title: 'Fundamental Rights vs DPSPs: Judicial Reconciliation & Minerva Mills Balance',
    shortDefinition: 'Evolution of judicial reconciliation from Champakam Dorairajan to Kesavananda Bharati and Minerva Mills.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T10-05',
    slug: 'directivism-outside-part-4-implementation-schemes',
    title: 'Directives Outside Part IV & Statutory Implementation Schemes',
    shortDefinition: 'Articles 335, 350A, 351 directives and welfare schemes translating DPSPs into statutory rights.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // ECONOMICS: INFLATION BENCHMARK (5 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-ECON-INF-01',
    slug: 'inflation-definition-distinctions-real-nominal',
    title: 'Inflation Definition, Rate vs Level & Real-Nominal Distinctions',
    shortDefinition: 'Persistent generalized price rise, speedometer disinflation, and Fisher equation exact compounding.',
    difficulty: 'BEGINNER',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  {
    id: 'CON-ECON-INF-02',
    slug: 'price-indices-measurement-cpi-wpi-core-headline',
    title: 'Price Indices & Measurement: CPI, WPI, Core vs Headline & Base Effect',
    shortDefinition: 'NSO CPI vs DPIIT WPI commodity scope, Laspeyres weighting, and 3-step Base Effect price ladders.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  {
    id: 'CON-ECON-INF-03',
    slug: 'inflation-causes-mechanisms-demand-cost-structural',
    title: 'Causal Mechanisms: Demand-Pull, Cost-Push & Structural Inflation',
    shortDefinition: 'Factory sustainable output gap, landed currency pass-through ($100 at ₹75 vs ₹85), and structural bottlenecks.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  {
    id: 'CON-ECON-INF-04',
    slug: 'inflation-distributional-impacts-growth-tradeoffs-phillips-curve',
    title: 'Distributional Impacts, Growth Trade-Offs & Phillips Curve Dynamics',
    shortDefinition: 'Fixed vs floating loan debt redistribution, fiscal bracket creep, and Indian 4-6% empirical threshold.',
    difficulty: 'ADVANCED',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  {
    id: 'CON-ECON-INF-05',
    slug: 'inflation-policy-framework-rbi-mpc-flexible-targeting-supply-side',
    title: 'Policy Framework: RBI Flexible Inflation Targeting & Supply-Side Policy',
    shortDefinition: 'Section 45ZA mandate, monetary transmission frictions (EBLR), and the Two Hands of Policy boundary.',
    difficulty: 'ADVANCED',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
];
