export interface StaticConceptItem {
  id: string;
  slug: string;
  title: string;
  shortDefinition: string;
  difficulty: string;
  topicTitle: string;
  subjectName: string;
}

export const STATIC_CONCEPT_INDEX: StaticConceptItem[] = [
  // Topic 9: Part III Fundamental Rights (16 concepts)
  {
    id: 'CON-T9-01',
    slug: 'part-3-overview-nature-of-fundamental-rights',
    title: 'Part III: Overview & Magna Carta of India',
    shortDefinition: 'Constitutional charter of fundamental rights under Articles 12 to 35, justifiable against state action.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-02',
    slug: 'article-12-definition-of-state',
    title: 'Article 12: Definition of State & Other Authorities',
    shortDefinition: 'Constitutional definition of State encompassing legislative, executive, statutory, and instrumentality bodies.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-03',
    slug: 'article-13-judicial-review-doctrines',
    title: 'Article 13: Laws Inconsistent with Fundamental Rights',
    shortDefinition: 'Constitutional shield establishing judicial review, doctrine of severability, eclipse, and waiver.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-04',
    slug: 'article-14-equality-non-arbitrariness',
    title: 'Article 14: Right to Equality & Non-Arbitrariness Doctrine',
    shortDefinition: 'Universal equality before law and equal protection of laws, proscribing state arbitrariness.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-05',
    slug: 'articles-15-16-reservations-protective-discrimination',
    title: 'Articles 15 & 16: Prohibition of Discrimination & Public Employment Reservations',
    shortDefinition: 'Constitutional framework for protective discrimination, affirmative action, and public employment quotas.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-06',
    slug: 'articles-17-18-abolition-untouchability-titles',
    title: 'Articles 17 & 18: Abolition of Untouchability & Titles',
    shortDefinition: 'Absolute abolition of untouchability practice and prohibition of state-conferred aristocratic titles.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-07',
    slug: 'article-19-democratic-freedoms-civil-liberties',
    title: 'Article 19: Six Democratic Freedoms & Reasonable Restrictions',
    shortDefinition: 'Protection of speech, assembly, association, movement, residence, and profession under Article 19(2)-(6) boundaries.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-08',
    slug: 'article-20-conviction-protections',
    title: 'Article 20: Protections in Respect of Conviction for Offences',
    shortDefinition: 'Triple criminal constitutional protections: ex-post facto laws, double jeopardy, and self-incrimination.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-09',
    slug: 'article-21-21a-life-liberty-privacy-education',
    title: 'Articles 21 & 21A: Right to Life, Personal Liberty, Privacy & Education',
    shortDefinition: 'Substantive due process, expanded life dignity rights under Maneka Gandhi, privacy under Puttaswamy, and education under 21A.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-10',
    slug: 'article-22-arrest-safeguards-preventive-detention',
    title: 'Article 22: Safeguards against Arrest & Preventive Detention',
    shortDefinition: 'Procedural rights of punitive detainees and constitutional constraints on executive preventive detention.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-11',
    slug: 'articles-23-24-right-against-exploitation',
    title: 'Articles 23 & 24: Right against Exploitation',
    shortDefinition: 'Prohibition of human trafficking, forced labor (begar), and hazardous child labor.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-12',
    slug: 'articles-25-28-freedom-of-religion-essential-practices',
    title: 'Articles 25–28: Freedom of Religion & Essential Religious Practices',
    shortDefinition: 'Individual conscience, collective denomination management, tax exemptions, and religious instruction boundaries.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-13',
    slug: 'articles-29-30-minority-cultural-educational-rights',
    title: 'Articles 29 & 30: Cultural and Educational Rights of Minorities',
    shortDefinition: 'Protection of distinct culture/language for any section and fundamental right of minorities to establish educational institutions.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-14',
    slug: 'articles-31-300a-property-due-process',
    title: 'Articles 31, 31A–31C & 300A: Right to Property & Saving of Laws',
    shortDefinition: 'Transformation from Fundamental Right under Article 19(1)(f)/31 to Constitutional Right under Article 300A.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-15',
    slug: 'article-32-writs-constitutional-remedies',
    title: 'Article 32: Right to Constitutional Remedies & Prerogative Writs',
    shortDefinition: 'The heart and soul of the Constitution: direct Supreme Court enforcement via Habeas Corpus, Mandamus, Prohibition, Certiorari, and Quo Warranto.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-16',
    slug: 'articles-33-35-amendability-basic-structure',
    title: 'Articles 33–35: Armed Forces Exceptions, Martial Law & Basic Structure',
    shortDefinition: 'Parliamentary modification of rights for armed forces, martial law indemnities, and exclusive parliamentary penal power.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },

  // Topic 10: Part IV Directive Principles (5 concepts)
  {
    id: 'CON-T10-01',
    slug: 'dpsp-nature-justiciability-article-37',
    title: 'Nature & Non-Justiciability of DPSPs (Article 37)',
    shortDefinition: 'Fundamental in the governance of the country yet non-enforceable by courts.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T10-02',
    slug: 'dpsp-classification-socialistic-gandhian-liberal',
    title: 'Classification of DPSPs: Socialistic, Gandhian & Liberal-Intellectual',
    shortDefinition: 'Threefold ideological taxonomy of state directives under Part IV.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T10-03',
    slug: 'article-44-uniform-civil-code-jurisprudence',
    title: 'Article 44: Uniform Civil Code Jurisprudence & Judicial Evolution',
    shortDefinition: 'Directives on UCC, secular civil laws, Shah Bano, Sarla Mudgal, and modern constitutional debates.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T10-04',
    slug: 'part-3-part-4-conflict-harmonious-construction',
    title: 'Part III vs Part IV Conflict & The Doctrine of Harmonious Construction',
    shortDefinition: 'Evolution of judicial reconciliation from Champakam Dorairajan to Kesavananda Bharati and Minerva Mills.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T10-05',
    slug: 'directivism-outside-part-4-implementation-schemes',
    title: 'Directives Outside Part IV & Statutory Implementation Schemes',
    shortDefinition: 'Articles 335, 350A, 351 directives and welfare schemes translating DPSPs into statutory rights.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },

  // Economics: Inflation (5 concepts)
  {
    id: 'CON-ECON-INF-01',
    slug: 'inflation-definition-distinctions-real-nominal',
    title: 'Inflation Definition, Rate vs Level & Real-Nominal Distinctions',
    shortDefinition: 'Persistent generalized price rise, speedometer disinflation, and Fisher equation exact compounding.',
    difficulty: 'BEGINNER',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  {
    id: 'CON-ECON-INF-02',
    slug: 'price-indices-measurement-cpi-wpi-core-headline',
    title: 'Price Indices & Measurement: CPI, WPI, Core vs Headline & Base Effect',
    shortDefinition: 'NSO CPI vs DPIIT WPI commodity scope, Laspeyres weighting, and 3-step Base Effect price ladders.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  {
    id: 'CON-ECON-INF-03',
    slug: 'inflation-causes-mechanisms-demand-cost-structural',
    title: 'Causal Mechanisms: Demand-Pull, Cost-Push & Structural Inflation',
    shortDefinition: 'Factory sustainable output gap, landed currency pass-through ($100 at ₹75 vs ₹85), and structural bottlenecks.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  {
    id: 'CON-ECON-INF-04',
    slug: 'inflation-distributional-impacts-growth-tradeoffs-phillips-curve',
    title: 'Distributional Impacts, Growth Trade-Offs & Phillips Curve Dynamics',
    shortDefinition: 'Fixed vs floating loan debt redistribution, fiscal bracket creep, and Indian 4-6% empirical threshold.',
    difficulty: 'ADVANCED',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  {
    id: 'CON-ECON-INF-05',
    slug: 'inflation-policy-framework-rbi-mpc-flexible-targeting-supply-side',
    title: 'Policy Framework: RBI Flexible Inflation Targeting & Supply-Side Policy',
    shortDefinition: 'Section 45ZA mandate, monetary transmission frictions (EBLR), and the Two Hands of Policy boundary.',
    difficulty: 'ADVANCED',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
];
