export interface StaticConceptItem {
  id: string;
  slug: string;
  title: string;
  shortDefinition: string;
  difficulty: string;
  topicTitle: string;
  subjectName: string;
}

export const STATIC_CONCEPT_INDEX: StaticConceptItem[] = [
  // =========================================================================
  // TOPIC 1: BASIC CONCEPTS OF POLITY (4 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T1-01',
    slug: 'state-and-nation-constituent-elements-saptanga-theory',
    title: 'The State and Nation: Constituent Elements, Saptanga Theory & Distinctions',
    shortDefinition: 'The State as a sovereign political-legal entity defined by four elements (territory, population, government, sovereignty), Kautilya’s Saptanga model, and Nation distinction.',
    difficulty: 'BEGINNER',
    topicTitle: 'Basic Concepts of Polity',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T1-02',
    slug: 'theories-of-origin-of-state-divine-social-contract-marxist',
    title: 'Theories of the Origin of the State: Divine, Social Contract, Historical & Marxist',
    shortDefinition: 'Philosophical accounts of state emergence: Divine Origin, Social Contract (Hobbes, Locke, Rousseau overcoming Matsya Nyaya), and Evolutionary models.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Basic Concepts of Polity',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T1-03',
    slug: 'systems-of-governance-parliamentary-presidential-constitutional-supremacy',
    title: 'Systems of Governance: Parliamentary vs Presidential & Constitutional Supremacy',
    shortDefinition: 'Dual Legislature/Executive in India, Unified Judiciary, Parliamentary executive-legislative fusion vs US Separation of Powers, and UK Parliamentary Sovereignty vs Indian Constitutional Supremacy.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Basic Concepts of Polity',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T1-04',
    slug: 'constitution-and-constitutionalism-nature-functions-pillars',
    title: 'Constitution & Constitutionalism: Nature, Functions & Pillars of Limited Government',
    shortDefinition: 'The Constitution as supreme organic law versus Constitutionalism as the philosophy of limited government, rule of law, and institutional restraint.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Basic Concepts of Polity',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 2: CONSTITUENT ASSEMBLY (6 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T2-01',
    slug: 'historical-evolution-demand-for-constituent-assembly',
    title: 'Historical Evolution & Demand for the Constituent Assembly (1895–1946)',
    shortDefinition: 'Progression from Tilak’s Swaraj Bill (1895) and Nehru Report (1928) to M.N. Roy (1934), INC demands, August Offer (1940), Cripps Mission (1942), and Cabinet Mission (1946).',
    difficulty: 'BEGINNER',
    topicTitle: 'Constituent Assembly of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T2-02',
    slug: 'composition-election-restructuring-constituent-assembly',
    title: 'Composition, Election Framework & Restructuring of the Constituent Assembly',
    shortDefinition: 'Original 389-seat architecture (292 Provinces, 93 Princely States, 4 Chief Commissioner Provinces), indirect proportional voting via STV, and post-partition reduction to 299 seats.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Constituent Assembly of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T2-03',
    slug: 'functioning-working-timeline-dual-roles-constituent-assembly',
    title: 'Functioning, Working Timeline & Dual Roles of the Constituent Assembly',
    shortDefinition: 'Dec 9, 1946 opening, leadership appointments, Objectives Resolution, dual role as Constitution-maker and Provisional Parliament, adoption on Nov 26, 1949, and commencement on Jan 26, 1950.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Constituent Assembly of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T2-04',
    slug: 'committees-of-constituent-assembly-and-drafting-committee',
    title: 'Committees of the Constituent Assembly & The Drafting Committee',
    shortDefinition: 'Division of labor across 8 major committees and the 7-member Drafting Committee chaired by Dr. B.R. Ambedkar appointed on August 29, 1947.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Constituent Assembly of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T2-05',
    slug: 'sources-of-the-indian-constitution-borrowing-matrix',
    title: 'Major Sources Borrowed & Constitutional Borrowing Matrix',
    shortDefinition: 'Systematic borrowing from the 1935 Act and 10 world democracies (UK, USA, Ireland, Canada, Australia, Germany, USSR, France, South Africa, Japan).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Constituent Assembly of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T2-06',
    slug: 'constituent-assembly-rajasthan-representation-criticisms',
    title: 'Constituent Assembly: Rajasthan Representation, Critical Appraisals & Rebuttals',
    shortDefinition: 'The 14 representative members from Rajasthan, key officers/calligraphers, and comprehensive intellectual rebuttals to classical criticisms.',
    difficulty: 'ADVANCED',
    topicTitle: 'Constituent Assembly of India',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 3: PREAMBLE (4 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T3-01',
    slug: 'preamble-historical-genesis-text-authority-jurist-views',
    title: 'Preamble: Historical Genesis, Text, Source of Authority & Eminent Perspectives',
    shortDefinition: 'Nehru’s Objectives Resolution (1946), verbatim text enacted on Oct 17, 1949, popular sovereignty ("We the People"), and jurist characterizations (Palkhivala, Munshi, Bhargava).',
    difficulty: 'BEGINNER',
    topicTitle: 'The Preamble of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T3-02',
    slug: 'nature-of-indian-state-sovereign-socialist-secular-democratic-republic',
    title: 'Nature of the Indian State: Sovereign, Socialist, Secular, Democratic, Republic',
    shortDefinition: 'Internal-external sovereignty, democratic socialism, positive secularism (Sarva Dharma Sambhava / Bommai basic structure), representative democracy, and republican headship.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'The Preamble of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T3-03',
    slug: 'constitutional-objectives-justice-liberty-equality-fraternity',
    title: 'Constitutional Objectives: Justice, Liberty, Equality, Fraternity & Dignity',
    shortDefinition: 'Four grand ideals: three-dimensional Justice (Social, Economic, Political from Russia 1917), bounded Liberty (France 1789), Equality, and Fraternity with Dignity & Integrity.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'The Preamble of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T3-04',
    slug: 'status-justiciability-amendability-of-the-preamble',
    title: 'Constitutional Status, Justiciability & Amendability of the Preamble',
    shortDefinition: 'Berubari (1960) to Kesavananda (1973) and LIC (1995), non-justiciable character, and the 42nd Amendment (Socialist, Secular, Integrity).',
    difficulty: 'ADVANCED',
    topicTitle: 'The Preamble of the Indian Constitution',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 4: SCHEDULES (8 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T4-01',
    slug: 'schedules-overview-evolution-and-structural-matrix',
    title: 'Overview, Evolution & Structural Matrix of the 12 Schedules',
    shortDefinition: 'Functional role of Schedules, expansion from 8 in 1949 to 12 today via 1st, 52nd, 73rd, 74th Amendments, and direct substantive Article anchorage.',
    difficulty: 'BEGINNER',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-02',
    slug: 'schedules-1-to-4-territory-emoluments-oaths-rajya-sabha',
    title: 'Schedules 1 to 4: Territory, Emoluments, Oaths and Rajya Sabha Seat Allocation',
    shortDefinition: '1st Schedule (28 States & 8 UTs), 2nd Schedule (emoluments; Ministers excluded), 3rd Schedule (oaths; President/VP/Governor excluded), and 4th Schedule (RS seats).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-03',
    slug: 'schedules-5-and-6-scheduled-and-tribal-areas-administration',
    title: 'Schedules 5 and 6: Administration of Scheduled & Tribal Areas',
    shortDefinition: '5th Schedule administration in 10 states via TACs and Governor regulations vs 6th Schedule Autonomous District Councils in the 4 NE states (AMTM).',
    difficulty: 'ADVANCED',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-04',
    slug: '7th-schedule-division-of-powers-lists-and-residuary-power',
    title: '7th Schedule: Legislative Lists, Division of Powers & Residuary Powers',
    shortDefinition: 'Article 246 division across Union (100), State (61), Concurrent (52) lists, 42nd Amendment shift of 5 subjects, and Canadian-style Residuary Powers (Art 248).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-05',
    slug: '8th-schedule-22-official-languages-classical-languages',
    title: '8th Schedule: 22 Official Languages, Classical Languages & Amendments',
    shortDefinition: '14 original to 22 languages today across 21st, 71st, 92nd Amendments, English/Rajasthani exclusions, and 11 Classical Languages (incl. 2024 additions).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-06',
    slug: '9th-schedule-land-reforms-protective-umbrella-ir-coelho',
    title: '9th Schedule: Land Reforms, Protective Umbrella & The I.R. Coelho Doctrine',
    shortDefinition: '1st Amendment (1951) + Art 31B protecting land reforms, growth to 284 laws, and 9-judge I.R. Coelho ruling (2007) subjecting post-1973 laws to Basic Structure review.',
    difficulty: 'ADVANCED',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-07',
    slug: '10th-schedule-anti-defection-law-exceptions-judicial-evolution',
    title: '10th Schedule: Anti-Defection Law, Exceptions & Judicial Evolution',
    shortDefinition: '52nd Amendment (1985) and 91st Amendment (2003): disqualification grounds, British Whip convention, Kihoto Holohan (1992), and Keisham Meghchandra (2020).',
    difficulty: 'ADVANCED',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T4-08',
    slug: '11th-and-12th-schedules-local-governance-devolutions',
    title: '11th and 12th Schedules: Panchayati Raj & Municipal Functional Devolutions',
    shortDefinition: '73rd and 74th Amendments (1992): 11th Schedule (29 functional subjects for Panchayats) and 12th Schedule (18 functional subjects for Municipalities).',
    difficulty: 'BEGINNER',
    topicTitle: 'Schedules of the Indian Constitution',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 5: PART 1 — UNION AND ITS TERRITORY (4 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T5-01',
    slug: 'article-1-union-of-states-federal-nature-territory-of-india',
    title: 'Article 1: Union of States, Federal Nature & Territory of India',
    shortDefinition: 'India as an indestructible "Union of States", distinction between "Union of India" and "Territory of India", and Dr. Ambedkar’s rationale.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part I: The Union and Its Territory',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T5-02',
    slug: 'articles-2-and-3-admission-vs-internal-reorganisation-of-states',
    title: 'Articles 2 and 3: Admission vs Internal Reorganisation of States',
    shortDefinition: 'Admitting new external territories under Article 2 vs reorganising internal state boundaries under Article 3 ("Indestructible Union of Destructible States").',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part I: The Union and Its Territory',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T5-03',
    slug: 'article-4-and-cession-of-territory-the-berubari-doctrine',
    title: 'Article 4 & Cession of Indian Territory: The Berubari Doctrine',
    shortDefinition: 'Article 4 simple majority rule and the landmark Berubari Union doctrine (1960) requiring an Article 368 amendment to cede Indian territory.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part I: The Union and Its Territory',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T5-04',
    slug: 'union-territories-architecture-and-100th-amendment-enclaves-exchange',
    title: 'Union Territories: Constitutional Architecture & Enclaves Exchange',
    shortDefinition: 'Constitutional categorization of UTs under Part VIII and the 100th Constitutional Amendment (2015) Indo-Bangladesh enclaves exchange.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part I: The Union and Its Territory',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 6: UNIFICATION OF INDIA (4 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T6-01',
    slug: 'lapse-of-paramountcy-and-patel-menon-integration-architecture',
    title: 'Lapse of Paramountcy & The Patel-Menon Integration Architecture',
    shortDefinition: 'Lapse of British paramountcy over 565 princely states and Sardar Patel/V.P. Menon’s integration strategy via Standstill Agreements and Instruments of Accession.',
    difficulty: 'BEGINNER',
    topicTitle: 'Unification and Integration of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T6-02',
    slug: 'integration-of-challenging-states-junagadh-hyderabad-and-jammu-kashmir',
    title: 'Integration of Challenging States: Junagadh, Hyderabad & Jammu & Kashmir',
    shortDefinition: 'Integrating Junagadh (1948 plebiscite), Hyderabad (Operation Polo 1948), and Jammu & Kashmir (Instrument of Accession 1947 and 2019 reorganisation).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Unification and Integration of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T6-03',
    slug: 'liberation-of-foreign-enclaves-french-and-portuguese-territories',
    title: 'Liberation of Foreign Enclaves: French and Portuguese Territories',
    shortDefinition: 'Diplomatic transfer of French settlements (Puducherry) and military liberation of Portuguese settlements (Goa Operation Vijay 1961) to statehood (1987).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Unification and Integration of India',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T6-04',
    slug: 'integration-of-sikkim-from-associate-state-to-full-statehood',
    title: 'Integration of Sikkim: From Associate State to Full Statehood',
    shortDefinition: 'Sikkim’s constitutional transition: 35th Amendment (1974 "Associate State") to 36th Amendment (1975 22nd State, Article 371F), and 1950 four-fold state classification.',
    difficulty: 'ADVANCED',
    topicTitle: 'Unification and Integration of India',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 7: REORGANISATION OF STATES (4 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T7-01',
    slug: 'linguistic-demands-and-early-commissions-dhar-and-jvp',
    title: 'Linguistic Demands & Early Commissions: Dhar Commission & JVP Committee',
    shortDefinition: 'Historical demands for linguistic states, the S.K. Dhar Commission (1948), and the JVP Committee’s initial rejection of language-based reorganization.',
    difficulty: 'BEGINNER',
    topicTitle: 'Reorganisation of States & Zonal Councils',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T7-02',
    slug: 'andhra-crisis-and-fazal-ali-commission-src-1953-1955',
    title: 'Andhra Crisis & Fazal Ali Commission (States Reorganisation Commission 1953–55)',
    shortDefinition: 'Creation of Andhra State (1953) after Potti Sreeramulu’s fast, Fazal Ali Commission (SRC), acceptance of language criterion, and its four core principles.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Reorganisation of States & Zonal Councils',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T7-03',
    slug: 'states-reorganisation-act-1956-and-historical-evolution-of-indian-states',
    title: 'States Reorganisation Act 1956 & Evolution of States (1956–2020)',
    shortDefinition: 'The 7th Amendment and 1956 Act creating 14 states and 6 UTs, and post-1956 milestones (1960, 1966, 1972, 2000, 2014, 2019, 2020) leading to 28 states and 8 UTs.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Reorganisation of States & Zonal Councils',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T7-04',
    slug: 'zonal-councils-and-north-eastern-council-inter-state-cooperative-architecture',
    title: 'Zonal Councils & North-Eastern Council: Inter-State Cooperative Architecture',
    shortDefinition: 'Statutory framework of Zonal Councils under the 1956 Act and the North-Eastern Council (1971) chaired by the Union Home Minister.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Reorganisation of States & Zonal Councils',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 8: PART 2 — CITIZENSHIP (6 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T8-01',
    slug: 'citizenship-meaning-civil-rights-and-constitutional-articles-5-to-11',
    title: 'Citizenship: Meaning, Civil Rights & Constitutional Articles (5–11)',
    shortDefinition: 'Exclusive constitutional rights reserved for citizens (Arts 15, 16, 19, 29, 30, 326) and the transitional citizenship provisions on Jan 26, 1950.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part II: Citizenship (Articles 5 to 11)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T8-02',
    slug: 'acquisition-of-indian-citizenship-under-citizenship-act-1955',
    title: 'Acquisition of Indian Citizenship under Citizenship Act 1955',
    shortDefinition: 'Five statutory pathways to citizenship (Birth, Descent, Registration, Naturalisation, Incorporation) and their evolving criteria (1986, 1992, 2003, 2019).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part II: Citizenship (Articles 5 to 11)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T8-03',
    slug: 'loss-of-indian-citizenship-renunciation-termination-and-deprivation',
    title: 'Loss of Indian Citizenship: Renunciation, Termination & Deprivation',
    shortDefinition: 'Three statutory modes of losing citizenship: voluntary Renunciation, automatic Termination, and compulsory Deprivation by Central Government.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part II: Citizenship (Articles 5 to 11)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T8-04',
    slug: 'single-citizenship-vs-dual-citizenship-and-constitutional-unity',
    title: 'Single Citizenship vs Dual Citizenship & Constitutional Unity',
    shortDefinition: 'Indian Single Citizenship doctrine ensuring undivided allegiance, equality of rights, and comparison with US dual citizenship.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part II: Citizenship (Articles 5 to 11)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T8-05',
    slug: 'overseas-citizen-of-india-oci-scheme-and-rights-framework',
    title: 'Overseas Citizen of India (OCI) Scheme & Rights Framework',
    shortDefinition: 'Statutory OCI scheme, 2015 PIO merger, extensive economic rights granted (Sec 7B), and strict denial of political/constitutional rights (Sec 7B(2)).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part II: Citizenship (Articles 5 to 11)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T8-06',
    slug: 'citizenship-policy-renunciation-trends-and-dual-citizenship-debate',
    title: 'Contemporary Citizenship Dynamics: Renunciation Trends & Policy Debate',
    shortDefinition: '1.6 million renunciations since 2011, passport rankings, economic diplomacy, and cost-benefit analysis of conditional dual citizenship.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part II: Citizenship (Articles 5 to 11)',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 9: PART III FUNDAMENTAL RIGHTS (16 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T9-01',
    slug: 'part-3-overview-nature-of-fundamental-rights',
    title: 'Part III: Overview & Magna Carta of India',
    shortDefinition: 'Constitutional charter of fundamental rights under Articles 12 to 35, justifiable against state action.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-02',
    slug: 'article-12-definition-of-state',
    title: 'Article 12: Definition of State & Other Authorities',
    shortDefinition: 'Constitutional definition of State encompassing legislative, executive, statutory, and instrumentality bodies.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-03',
    slug: 'article-13-judicial-review-doctrines',
    title: 'Article 13: Laws Inconsistent with Fundamental Rights',
    shortDefinition: 'Constitutional shield establishing judicial review, doctrine of severability, eclipse, and waiver.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-04',
    slug: 'article-14-equality-non-arbitrariness',
    title: 'Article 14: Right to Equality & Non-Arbitrariness Doctrine',
    shortDefinition: 'Universal equality before law and equal protection of laws, proscribing state arbitrariness.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-05',
    slug: 'articles-15-16-reservations-protective-discrimination',
    title: 'Articles 15 & 16: Prohibition of Discrimination & Public Employment Reservations',
    shortDefinition: 'Constitutional framework for protective discrimination, affirmative action, and public employment quotas.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-06',
    slug: 'articles-17-18-abolition-untouchability-titles',
    title: 'Articles 17 & 18: Abolition of Untouchability & Titles',
    shortDefinition: 'Absolute constitutional abolition of untouchability and prohibition of noble and aristocratic titles.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-07',
    slug: 'article-19-six-freedoms-reasonable-restrictions',
    title: 'Article 19: Six Democratic Freedoms & Reasonable Restrictions',
    shortDefinition: 'Six fundamental democratic freedoms guaranteed to citizens with exhaustive grounds of reasonable restrictions.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-08',
    slug: 'article-20-protection-conviction-offences',
    title: 'Article 20: Protection in Respect of Conviction for Offences',
    shortDefinition: 'Inviolable criminal safeguards against ex-post facto laws, double jeopardy, and self-incrimination.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-09',
    slug: 'article-21-21a-life-liberty-privacy-education',
    title: 'Articles 21 & 21A: Right to Life, Personal Liberty, Privacy & Education',
    shortDefinition: 'Procedural due process under Maneka Gandhi, fundamental right to privacy under Puttaswamy, and right to education.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-10',
    slug: 'article-22-preventive-detention-safeguards',
    title: 'Article 22: Protection Against Arrest & Preventive Detention Safeguards',
    shortDefinition: 'Constitutional balance between punitive procedural rights and preventive detention safeguards.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-11',
    slug: 'articles-23-24-right-against-exploitation',
    title: 'Articles 23 & 24: Right Against Exploitation & Child Labour Prohibition',
    shortDefinition: 'Constitutional prohibitions against human trafficking, begar, forced labor, and hazardous child employment.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-12',
    slug: 'articles-25-28-freedom-of-religion-secularism',
    title: 'Articles 25 to 28: Freedom of Religion & Secularism',
    shortDefinition: 'Individual religious conscience, denominational autonomy, and the positive secularism architecture.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-13',
    slug: 'articles-29-30-cultural-educational-rights-minorities',
    title: 'Articles 29 & 30: Cultural & Educational Rights of Minorities',
    shortDefinition: 'Preservation of distinct language, script, culture, and minority rights to establish and administer educational institutions.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-14',
    slug: 'articles-31a-31b-31c-saving-certain-laws',
    title: 'Articles 31A, 31B & 31C: Constitutional Savings of Agrarian & Welfare Laws',
    shortDefinition: 'Protective constitutional umbrellas shielding agrarian reforms, Ninth Schedule statutes, and socialist directive principles.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-15',
    slug: 'article-32-constitutional-remedies-prerogative-writs',
    title: 'Article 32: Right to Constitutional Remedies & Five Prerogative Writs',
    shortDefinition: 'The cornerstone and heart of the Constitution providing direct access to the Supreme Court via five prerogative writs.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T9-16',
    slug: 'articles-33-35-armed-forces-martial-law-legislation',
    title: 'Articles 33, 34 & 35: Armed Forces Modifications, Martial Law & Legislative Exclusivity',
    shortDefinition: 'Parliamentary restrictions on armed forces rights, indemnity during martial law, and Union legislative exclusivity for Part III.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part III: Fundamental Rights',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 10: DIRECTIVE PRINCIPLES (5 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T10-01',
    slug: 'part-4-nature-philosophy-non-justiciability-dpsp',
    title: 'Part IV: Nature, Philosophy & Non-Justiciability of DPSPs',
    shortDefinition: 'Instrument of Instructions for socio-economic democracy, moral imperatives, and non-justiciable character under Article 37.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T10-02',
    slug: 'socialistic-gandhian-liberal-intellectual-classification',
    title: 'Socialistic, Gandhian & Liberal-Intellectual Classification of DPSPs',
    shortDefinition: 'Tripartite philosophical taxonomy of welfare principles spanning Articles 38 to 51.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T10-03',
    slug: 'amendments-to-part-4-42nd-44th-86th-97th',
    title: 'Constitutional Amendments to Part IV: 42nd, 44th, 86th & 97th Amendments',
    shortDefinition: 'Evolution of DPSPs through constitutional amendments introducing legal aid, worker participation, early childhood care, and cooperatives.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T10-04',
    slug: 'fundamental-rights-vs-dpsp-judicial-reconciliation-minerva-mills',
    title: 'Fundamental Rights vs DPSPs: Judicial Reconciliation & Minerva Mills Balance',
    shortDefinition: 'Evolution of judicial reconciliation from Champakam Dorairajan to Kesavananda Bharati and Minerva Mills.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T10-05',
    slug: 'directivism-outside-part-4-implementation-schemes',
    title: 'Directives Outside Part IV & Statutory Implementation Schemes',
    shortDefinition: 'Articles 335, 350A, 351 directives and welfare schemes translating DPSPs into statutory rights.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part IV: Directive Principles of State Policy',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 11: THE UNION EXECUTIVE (6 CONCEPTS: CON-T11-01 to CON-T11-06)
  // =========================================================================
  {
    id: 'CON-T11-01',
    slug: 'president-constitutional-status-electoral-college-impeachment',
    title: 'President of India: Constitutional Status, Electoral College & Impeachment',
    shortDefinition: 'The President as de jure Head of State, Art 54-55 proportional representation electoral formula, and Art 61 quasi-judicial impeachment by 2/3rd total membership.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part V: The Union Executive (President, Vice-President, PM & AG)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T11-02',
    slug: 'president-powers-veto-and-ordinance-making-power',
    title: "President's Powers: Veto Powers (Art 111) & Ordinance-Making Power (Art 123)",
    shortDefinition: 'Tripartite veto powers (Absolute, Suspensive, Pocket), 24th CAA mandatory assent, and Art 123 ordinance limits with judicial anti-repromulgation checks.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part V: The Union Executive (President, Vice-President, PM & AG)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T11-03',
    slug: 'president-judicial-and-pardoning-powers-article-72',
    title: "President's Judicial & Pardoning Powers (Article 72)",
    shortDefinition: 'Article 72 five forms of clemency, cabinet aid & advice binding rule (Maru Ram), and judicial review limits against arbitrariness and delay (Shatrughan Chauhan).',
    difficulty: 'ADVANCED',
    topicTitle: 'Part V: The Union Executive (President, Vice-President, PM & AG)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T11-04',
    slug: 'vice-president-constitutional-status-election-removal',
    title: 'Vice-President of India: Status, Election (Art 66), Removal (Art 67) & Role',
    shortDefinition: 'Second-highest dignitary, Ex-officio Chairman of Rajya Sabha (Art 64), electoral college comprising all MPs, and removal by Effective Majority in RS + Simple Majority in LS.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part V: The Union Executive (President, Vice-President, PM & AG)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T11-05',
    slug: 'prime-minister-and-central-council-of-ministers-architecture',
    title: 'Prime Minister & Central Council of Ministers: Architecture & Collective Responsibility',
    shortDefinition: 'Prime Minister as real executive (De Facto), Art 74 aid & advice mechanism, Art 75(3) collective responsibility to Lok Sabha, and 91st CAA 15% size ceiling.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part V: The Union Executive (President, Vice-President, PM & AG)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T11-06',
    slug: 'attorney-general-of-india-constitutional-status-and-powers',
    title: 'Attorney General of India (Article 76) & Law Officers Architecture',
    shortDefinition: 'Highest law officer of India, SC Judge qualifications, pleasure tenure, and Art 88 right to participate in Parliament without voting right.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part V: The Union Executive (President, Vice-President, PM & AG)',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 12: THE STATE EXECUTIVE (4 CONCEPTS: CON-T12-01 to CON-T12-04)
  // =========================================================================
  {
    id: 'CON-T12-01',
    slug: 'governor-constitutional-dual-role-appointment-and-removal',
    title: 'Governor of the State: Constitutional Dual Role, Appointment & Removal',
    shortDefinition: 'Dual capacity as State Head and Centre Agent (Arts 153-154), presidential warrant appointment, pleasure tenure (Art 156), and BP Singhal (2010) judicial restraints.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part VI: The State Executive (Governor, Chief Minister & Advocate General)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T12-02',
    slug: 'governor-discretionary-powers-bill-reservation-and-ordinance',
    title: "Governor's Discretionary Powers (Art 163), Bill Reservation (Arts 200–201) & Ordinance (Art 213)",
    shortDefinition: 'Article 163 explicit discretion, mandatory floor test rules (SR Bommai), state bill reservation for President (Arts 200-201), and Article 161 pardoning limits.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part VI: The State Executive (Governor, Chief Minister & Advocate General)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T12-03',
    slug: 'chief-minister-and-state-council-of-ministers-architecture',
    title: 'Chief Minister & State Council of Ministers: Constitutional Architecture',
    shortDefinition: 'Real executive at state level, 91st CAA dual limits (15% assembly ceiling, minimum 12 ministers), and collective responsibility to Legislative Assembly (Art 164(2)).',
    difficulty: 'BEGINNER',
    topicTitle: 'Part VI: The State Executive (Governor, Chief Minister & Advocate General)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T12-04',
    slug: 'advocate-general-for-the-state-constitutional-status-and-powers',
    title: 'Advocate General for the State (Article 165) & Rights in Legislature (Art 177)',
    shortDefinition: 'Highest state law officer, HC Judge qualifications, pleasure of Governor, and Art 177 right to participate in State Legislature without voting power.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part VI: The State Executive (Governor, Chief Minister & Advocate General)',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 13: CIVIL SERVICES & PUBLIC SERVICES (2 CONCEPTS: CON-T13-01 to CON-T13-02)
  // =========================================================================
  {
    id: 'CON-T13-01',
    slug: 'all-india-services-and-constitutional-framework-of-public-services',
    title: 'All-India Services (Article 312) & Framework of Public Services (Arts 308–309)',
    shortDefinition: 'Part XIV classification, creation of new All-India Services via Rajya Sabha 2/3rd resolution under Art 312, and federal dual-control administrative mechanism.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part XIV: Civil Services, Doctrine of Pleasure & Constitutional Safeguards',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T13-02',
    slug: 'doctrine-of-pleasure-and-article-311-constitutional-safeguards',
    title: 'Doctrine of Pleasure (Art 310) & Article 311 Safeguards with Exceptions',
    shortDefinition: 'Article 310 pleasure doctrine, Article 311 procedural safeguards against dismissal, and three exceptions (conviction, impracticability, state security) upheld in Tulsiram Patel (1985).',
    difficulty: 'ADVANCED',
    topicTitle: 'Part XIV: Civil Services, Doctrine of Pleasure & Constitutional Safeguards',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 14: THE UNION LEGISLATURE (6 CONCEPTS: CON-T14-01 to CON-T14-06)
  // =========================================================================
  {
    id: 'CON-T14-01',
    slug: 'parliament-architecture-bicameralism-composition-and-sessions',
    title: 'Parliament Architecture: Bicameralism (Art 79), Composition & Sessions',
    shortDefinition: 'The tripartite structure of Parliament (President, RS, LS), federal composition of Rajya Sabha, democratic Lok Sabha, and constitutional rules for sessions and quorum.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part V: The Union Legislature (Parliament Architecture, Procedure & Budget)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T14-02',
    slug: 'presiding-officers-speaker-vs-chairman-and-disqualifications',
    title: 'Presiding Officers: Speaker vs Chairman (Arts 89, 93) & Disqualifications',
    shortDefinition: 'Speaker of Lok Sabha and Chairman of Rajya Sabha roles, casting vote, Money Bill certification, and Article 102 vs 10th Schedule disqualifications.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part V: The Union Legislature (Parliament Architecture, Procedure & Budget)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T14-03',
    slug: 'legislative-enactments-classification-of-bills-and-joint-sittings',
    title: 'Legislative Enactments: Classification of Bills (Arts 107–110, 117) & Joint Sittings (Art 108)',
    shortDefinition: 'Four classes of bills (Ordinary, Money, Financial I & II), Article 108 Joint Sittings with exclusions (Money Bills & CAAs), and Article 107 dissolution lapse rules.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part V: The Union Legislature (Parliament Architecture, Procedure & Budget)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T14-04',
    slug: 'parliamentary-financial-control-and-budget-procedure',
    title: 'Parliamentary Financial Control: Budget Procedure & Cut Motions (Arts 112–116)',
    shortDefinition: 'Six-stage Union Budget procedure, Charged vs Voted expenditure, Demands for Grants (Art 113), Cut Motions (Policy, Economy, Token), and Appropriation Bill.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part V: The Union Legislature (Parliament Architecture, Procedure & Budget)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T14-05',
    slug: 'parliamentary-standing-committees-pac-estimates-copu-and-drscs',
    title: 'Parliamentary Standing Committees: PAC (1921), Estimates (1950), COPU (1964) & DRSCs',
    shortDefinition: 'Three premier Financial Standing Committees (PAC, Estimates 30 LS only, COPU), 24 DRSCs, and the strict ban on ministerial membership.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part V: The Union Legislature (Parliament Architecture, Procedure & Budget)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T14-06',
    slug: 'parliamentary-privileges-motions-and-procedural-devices',
    title: 'Parliamentary Privileges (Art 105), Motions & Procedural Devices',
    shortDefinition: 'Constitutional privileges under Article 105, civil arrest immunity, Question Hour, Zero Hour (1962 innovation), and No-Confidence Motions.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part V: The Union Legislature (Parliament Architecture, Procedure & Budget)',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 15: THE STATE LEGISLATURE (4 CONCEPTS: CON-T15-01 to CON-T15-04)
  // =========================================================================
  {
    id: 'CON-T15-01',
    slug: 'state-legislature-architecture-and-creation-abolition-of-councils',
    title: 'State Legislature Architecture & Creation/Abolition of Councils (Art 169)',
    shortDefinition: 'Structure of State Legislatures under Part VI, 6 bicameral states, and the two-stage Assembly Special Majority + Parliament Simple Majority procedure under Art 169.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part VI: The State Legislature (Vidhan Sabha, Vidhan Parishad & Procedure)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T15-02',
    slug: 'composition-of-legislative-council-and-governor-nominations',
    title: 'Composition of Legislative Council (Art 171) & 5-Tier Electoral Formula',
    shortDefinition: 'Size limits of Legislative Council (max 1/3rd, min 40), 5-tier composition formula, and Governor 1/6th nomination including Cooperative Movement.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part VI: The State Legislature (Vidhan Sabha, Vidhan Parishad & Procedure)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T15-03',
    slug: 'state-legislative-procedure-and-delaying-powers-of-councils',
    title: 'State Legislative Procedure: 4-Month Delaying Powers & Absence of Joint Sitting',
    shortDefinition: 'Legislative relationship between Assembly and Council, max 4-month delaying power of Council on ordinary bills (Arts 197-198), and total absence of joint sittings.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part VI: The State Legislature (Vidhan Sabha, Vidhan Parishad & Procedure)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T15-04',
    slug: 'state-legislature-privileges-disqualifications-and-rajasthan-assembly',
    title: 'State Legislature: Privileges (Art 194), Disqualifications (Art 191) & Rajasthan Assembly',
    shortDefinition: 'State legislative privileges under Article 194, disqualification grounds under Article 191, and Rajasthan Legislative Assembly structure (200 unicameral seats).',
    difficulty: 'BEGINNER',
    topicTitle: 'Part VI: The State Legislature (Vidhan Sabha, Vidhan Parishad & Procedure)',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 16: THE UNION JUDICIARY (3 CONCEPTS: CON-T16-01 to CON-T16-03)
  // =========================================================================
  {
    id: 'CON-T16-01',
    slug: 'supreme-court-architecture-composition-collegium-and-removal',
    title: 'Supreme Court Architecture: Composition (34 Judges), Collegium & Removal',
    shortDefinition: 'Structure of the Supreme Court of India under Articles 124-128, Three Judges Cases collegium evolution, and Article 124(4) removal procedure.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part V: The Union Judiciary (The Supreme Court of India)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T16-02',
    slug: 'supreme-court-jurisdiction-original-appellate-and-special-leave',
    title: 'Supreme Court Jurisdiction: Original (Art 131), Appellate & SLP (Art 136)',
    shortDefinition: 'Exclusive Federal Original Jurisdiction (Art 131), Constitutional/Civil/Criminal Appellate routes, and plenary Special Leave Petitions (Art 136).',
    difficulty: 'ADVANCED',
    topicTitle: 'Part V: The Union Judiciary (The Supreme Court of India)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T16-03',
    slug: 'advisory-jurisdiction-article-143-and-inherent-powers-141-142',
    title: 'Advisory Jurisdiction (Art 143), Complete Justice (Art 142) & Law of Land (Art 141)',
    shortDefinition: 'Presidential consultative references under Article 143, Article 142 "complete justice" inherent powers, and Article 141 binding precedent.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part V: The Union Judiciary (The Supreme Court of India)',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 17: STATE JUDICIARY (4 CONCEPTS: CON-T17-01 to CON-T17-04)
  // =========================================================================
  {
    id: 'CON-T17-01',
    slug: 'high-court-architecture-appointments-qualifications-and-transfers',
    title: 'High Court Architecture: Appointments, Qualifications & Transfers (Arts 214–224A)',
    shortDefinition: 'Framework of 25 High Courts, judicial appointments, qualifications (no distinguished jurist), 62-year retirement age, and transfers under Art 222.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part VI: State Judiciary (High Courts & Subordinate Courts)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T17-02',
    slug: 'high-court-writ-jurisdiction-art-226-vs-art-32-and-superintendence',
    title: 'High Court Jurisdiction: Writ Jurisdiction (Art 226 vs Art 32) & Superintendence (Art 227)',
    shortDefinition: 'Expansive Article 226 writ jurisdiction ("for any other purpose"), comparison with Article 32, and Article 227 superintendence over all courts/tribunals.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part VI: State Judiciary (High Courts & Subordinate Courts)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T17-03',
    slug: 'subordinate-judiciary-architecture-and-high-court-control',
    title: 'Subordinate Judiciary Architecture (Arts 233–237) & High Court Control (Art 235)',
    shortDefinition: 'District Judges appointment (Art 233), judicial officer recruitment (Art 234), and complete High Court administrative/disciplinary control (Art 235).',
    difficulty: 'BEGINNER',
    topicTitle: 'Part VI: State Judiciary (High Courts & Subordinate Courts)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T17-04',
    slug: 'rajasthan-high-court-architecture-and-judicial-administration',
    title: 'Rajasthan High Court Architecture: Jodhpur Principal Seat & Jaipur Bench',
    shortDefinition: 'Establishment on Aug 29, 1949, first CJ Kamala Kant Verma, Satyanarayan Rao Committee (1958), permanent Jaipur Bench (1976/1977), and 50 sanctioned judges.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part VI: State Judiciary (High Courts & Subordinate Courts)',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 18: JUDICIAL INNOVATION & TRIBUNALS (3 CONCEPTS: CON-T18-01 to CON-T18-03)
  // =========================================================================
  {
    id: 'CON-T18-01',
    slug: 'public-interest-litigation-pil-locus-standi-and-epistolary-jurisdiction',
    title: 'Public Interest Litigation (PIL): Relaxation of Locus Standi & Epistolary Jurisdiction',
    shortDefinition: 'Pioneering work of Justice VR Krishna Iyer & PN Bhagwati, relaxation of locus standi, epistolary jurisdiction, and landmark cases (Hussainara, Bandhua Mukti, Vishaka).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part XIV-A: Judicial Innovation, PIL & Tribunals Architecture',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T18-02',
    slug: 'judicial-review-vs-activism-vs-judicial-overreach',
    title: 'Judicial Review vs Judicial Activism vs Judicial Overreach',
    shortDefinition: 'Boundaries separating constitutional Judicial Review (Arts 13, 32, 226), positive Judicial Activism, and unconstitutional Judicial Overreach.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part XIV-A: Judicial Innovation, PIL & Tribunals Architecture',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T18-03',
    slug: 'tribunals-architecture-article-323a-vs-323b-and-l-chandra-kumar',
    title: 'Tribunals Architecture: Part XIV-A (42nd CAA), Art 323A vs 323B & L. Chandra Kumar',
    shortDefinition: 'Administrative and specialized tribunals under Part XIV-A, Art 323A (CAT) vs 323B, and L. Chandra Kumar (1997) mandatory High Court Division Bench review.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part XIV-A: Judicial Innovation, PIL & Tribunals Architecture',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 19: CENTRE-STATE RELATIONS & FEDERAL STRUCTURE (5 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T19-01',
    slug: 'nature-of-indian-federalism-and-asymmetric-structure',
    title: 'Nature of Indian Federalism: Quasi-Federal Character & Asymmetric Provisions',
    shortDefinition: 'Holding-together federalism under Article 1, unitary/centripetal features, Basic Structure doctrine (S.R. Bommai 1994), and asymmetric federalism under Articles 371 to 371-J.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part XI & XII: Centre–State Relations & Federal Architecture',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T19-02',
    slug: 'legislative-relations-three-lists-residuary-powers-and-exceptions',
    title: 'Legislative Relations: Three Lists (7th Schedule), Residuary Powers & Exceptions',
    shortDefinition: '7th Schedule distribution, Article 248 residuary powers, 5 exceptions for Parliamentary law on State List (Arts 249, 250, 252, 253, 356), and Article 254 Repugnancy.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part XI & XII: Centre–State Relations & Federal Architecture',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T19-03',
    slug: 'administrative-relations-directives-all-india-services-and-water-disputes',
    title: 'Administrative Relations: Directives (Arts 256-257), Sanctions (Art 365) & All India Services',
    shortDefinition: 'Union directives to States (Arts 256-257), Article 365 sanction, Article 355 duty, All India Services (Art 312), and Inter-State River Water Disputes (Art 262).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part XI & XII: Centre–State Relations & Federal Architecture',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T19-04',
    slug: 'inter-state-council-zonal-councils-and-federal-commissions',
    title: 'Inter-State Council (Art 263), Zonal Councils & Federal Commissions',
    shortDefinition: 'Constitutional Inter-State Council (Art 263, est 1990), 5 statutory Zonal Councils (1956 Act), and Sarkaria/Punchhi Commission federal doctrines.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part XI & XII: Centre–State Relations & Federal Architecture',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T19-05',
    slug: 'financial-relations-finance-commission-and-gst-council',
    title: 'Financial Relations: Division of Taxes, Finance Commission (Art 280) & GST Council',
    shortDefinition: 'Fiscal federalism under Part XII, GST Council (Art 279A) weighted voting formula, Finance Commission (Art 280), Grants (Art 275 vs 282), and borrowing (Art 293).',
    difficulty: 'ADVANCED',
    topicTitle: 'Part XI & XII: Centre–State Relations & Federal Architecture',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 20: EMERGENCY PROVISIONS & SAFEGUARDS (4 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T20-01',
    slug: 'national-emergency-article-352-grounds-approval-and-safeguards',
    title: 'National Emergency (Article 352): Grounds, Approval & 44th CAA Safeguards',
    shortDefinition: 'Part XVIII Article 352 grounds (War, External Aggression, Armed Rebellion), written Cabinet advice, 1-month Special Majority approval, and Lok Sabha disapproval.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part XVIII: Emergency Provisions & Constitutional Safeguards',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T20-02',
    slug: 'national-emergency-effects-and-fundamental-rights-art-358-vs-359',
    title: 'National Emergency Impact: Federal Balance & Fundamental Rights (Art 358 vs Art 359)',
    shortDefinition: 'Federal centralization during emergency, Lok Sabha term extension, Article 358 automatic suspension of Art 19 for external emergency, and non-derogable Articles 20 & 21 under Art 359.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part XVIII: Emergency Provisions & Constitutional Safeguards',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T20-03',
    slug: 'presidents-rule-article-356-and-sr-bommai-doctrine',
    title: 'President\'s Rule (Articles 356 & 365): Grounds, Procedure & S.R. Bommai Doctrine',
    shortDefinition: 'Breakdown of state machinery, Simple Majority approval within 2 months, 44th CAA 3-year extension rules, and S.R. Bommai (1994) judicial review and floor test standards.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part XVIII: Emergency Provisions & Constitutional Safeguards',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T20-04',
    slug: 'financial-emergency-article-360-invocation-and-consequences',
    title: 'Financial Emergency (Article 360): Invocation, Indefinite Duration & Distinctive Powers',
    shortDefinition: 'Article 360 threat to financial credit, 2-month Simple Majority approval, indefinite continuation rule, reduction of SC/HC judges salaries, and non-invocation history.',
    difficulty: 'BEGINNER',
    topicTitle: 'Part XVIII: Emergency Provisions & Constitutional Safeguards',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 21: RURAL & URBAN LOCAL GOVERNANCE (73RD & 74TH CAAS) (4 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T21-01',
    slug: '73rd-amendment-panchayati-raj-architecture-and-devolution',
    title: '73rd Constitutional Amendment Act: Panchayati Raj Architecture & 3-Tier Devolution',
    shortDefinition: 'Constitutionalization of rural local self-government under Part IX (Articles 243–243O) and Eleventh Schedule (29 matters), establishing mandatory 3-tier PRIs, Gram Sabha, State Election Commission (Art 243K), and State Finance Commission (Art 243I).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part IX & IX-A: Rural & Urban Local Governance (73rd & 74th CAAs)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T21-02',
    slug: 'pesa-act-1996-tribal-self-governance-fifth-schedule',
    title: 'PESA Act (1996) & Tribal Self-Governance in Fifth Schedule Areas',
    shortDefinition: 'The Provisions of the Panchayats (Extension to the Scheduled Areas) Act 1996, extending Part IX with critical modifications to Fifth Schedule areas across 10 states, granting Gram Sabhas sovereign authority over natural resources, minor forest produce, and land preservation.',
    difficulty: 'ADVANCED',
    topicTitle: 'Part IX & IX-A: Rural & Urban Local Governance (73rd & 74th CAAs)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T21-03',
    slug: '74th-amendment-urban-local-bodies-and-metropolitan-planning',
    title: '74th Constitutional Amendment Act: Urban Local Bodies & Metropolitan Planning',
    shortDefinition: 'Constitutionalization of Urban Local Bodies (ULBs) under Part IX-A (Articles 243P–243ZG) and Twelfth Schedule (18 matters), establishing 3 municipal tiers, Wards Committees, District Planning Committees (Art 243ZD), and Metropolitan Planning Committees (Art 243ZE).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part IX & IX-A: Rural & Urban Local Governance (73rd & 74th CAAs)',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T21-04',
    slug: 'local-governance-rajasthan-nagaur-inception-acts-and-devolution',
    title: 'Local Governance in Rajasthan: Nagaur Inception, 5-Tier Devolution & Rajasthan Acts',
    shortDefinition: 'The pioneering historic evolution of Panchayati Raj inaugurated at Nagaur, Rajasthan on October 2, 1959, the major committee trajectories, and modern Rajasthan-specific local governance features (Rajasthan Panchayati Raj Act 1994, 50% women quota, Ward Sabha).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Part IX & IX-A: Rural & Urban Local Governance (73rd & 74th CAAs)',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 22: CONSTITUTIONAL INSTITUTIONS (ECI & CAG) (4 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T22-01',
    slug: 'election-commission-of-india-article-324-and-2023-appointment-act',
    title: 'Election Commission of India (Article 324): Composition, Independence & CEC/EC Appointment Act 2023',
    shortDefinition: 'The constitutional framework of the Election Commission under Article 324, its multi-member evolution, removal protections, plenary powers under Mohinder Singh Gill (1978), the Anoop Baranwal (2023) bench, and the CEC & Other ECs (Appointment) Act 2023.',
    difficulty: 'ADVANCED',
    topicTitle: 'Constitutional Institutions: Election Commission of India & Comptroller and Auditor General',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T22-02',
    slug: 'electoral-reforms-and-representation-of-the-people-acts-1950-1951',
    title: 'Electoral Reforms & Representation of the People Acts (1950 & 1951)',
    shortDefinition: 'The statutory dual-statute architecture governing Indian democracy—RPA 1950 (seats, delimitation, voter rolls) vs RPA 1951 (conduct of elections, qualifications, disqualifications under Section 8, corrupt practices, anti-defection, and electoral transparency).',
    difficulty: 'ADVANCED',
    topicTitle: 'Constitutional Institutions: Election Commission of India & Comptroller and Auditor General',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T22-03',
    slug: 'comptroller-and-auditor-general-of-india-articles-148-151',
    title: 'Comptroller and Auditor-General of India (Articles 148–151): Independence & Duties',
    shortDefinition: 'The constitutional office of the CAG under Articles 148–151 as the supreme guardian of the public purse, with institutional independence protections, duties under the CAG DPC Act 1971, separation of accounting from audit (1976), and partnership with the Public Accounts Committee.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Constitutional Institutions: Election Commission of India & Comptroller and Auditor General',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T22-04',
    slug: 'public-audit-spectrum-regulatory-propriety-performance-audit',
    title: 'Public Audit Architecture & Financial Oversight: Regulatory, Propriety & Performance Audit',
    shortDefinition: 'The three-dimensional methodology of public audit (Regulatory, Propriety, and Performance/Efficiency audit), institutional limitations (post-mortem nature, secret service limits), and expanded jurisdiction over PPPs and private discoms.',
    difficulty: 'ADVANCED',
    topicTitle: 'Constitutional Institutions: Election Commission of India & Comptroller and Auditor General',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 23: STATUTORY & NON-CONSTITUTIONAL BODIES (5 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T23-01',
    slug: 'central-information-commission-rti-act-2005-and-2019-amendments',
    title: 'Central Information Commission (CIC) & RTI Act (2005): Architecture, Exemptions & 2019 Amendments',
    shortDefinition: 'Statutory transparency watchdog established under the Right to Information Act 2005, proactive disclosures under Section 4, exemptions under Section 8, the 3-member Selection Committee, and the impact of the RTI (Amendment) Act 2019.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Statutory & Non-Constitutional Regulatory Authorities: Transparency, Human Rights & Integrity',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T23-02',
    slug: 'central-vigilance-commission-and-anti-corruption-framework',
    title: 'Central Vigilance Commission (CVC): Santhanam Committee to Statutory Apex Anti-Corruption Body',
    shortDefinition: 'The apex statutory anti-corruption vigilance authority established on Santhanam Committee recommendations, statutory recognition via the CVC Act 2003 following Vineet Narain (1997), superintendence over CBI for corruption offences, and Whistleblowers Protection framework.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Statutory & Non-Constitutional Regulatory Authorities: Transparency, Human Rights & Integrity',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T23-03',
    slug: 'national-human-rights-commission-and-state-hrcs-framework',
    title: 'National Human Rights Commission (NHRC): Protection of Human Rights Act 1993 & 2019 Reforms',
    shortDefinition: 'Statutory human rights watchdog under PHRA 1993 conforming to Paris Principles, 6-member Selection Committee, 2019 Amendment reforms (broadened Chairperson eligibility and 3-yr tenure), civil court powers, and structural limitations (1-yr bar, armed forces restrictions).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Statutory & Non-Constitutional Regulatory Authorities: Transparency, Human Rights & Integrity',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T23-04',
    slug: 'lokpal-and-lokayuktas-act-2013-anti-corruption-ombudsman',
    title: 'Lokpal and Lokayuktas Act (2013): Anti-Corruption Architecture & State Ombudsman',
    shortDefinition: 'Statutory anti-corruption ombudsman established under the Lokpal and Lokayuktas Act 2013 following ARC (1966) recommendations and Anna Hazare movement, jurisdiction covering PM, Ministers, MPs, and public servants, alongside state Lokayukta systems (Rajasthan 1973 model).',
    difficulty: 'ADVANCED',
    topicTitle: 'Statutory & Non-Constitutional Regulatory Authorities: Transparency, Human Rights & Integrity',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T23-05',
    slug: 'niti-aayog-vs-planning-commission-think-tank-and-cooperative-federalism',
    title: 'NITI Aayog vs Planning Commission: Think Tank Architecture & Cooperative Federalism',
    shortDefinition: 'The extra-constitutional executive think tank established on 1 January 2015 replacing the top-down Planning Commission (1950–2014), emphasizing bottom-up cooperative federalism, the Governing Council, Team India Hub, and the structural transfer of fund allocation powers to the Finance Ministry.',
    difficulty: 'BEGINNER',
    topicTitle: 'Statutory & Non-Constitutional Regulatory Authorities: Transparency, Human Rights & Integrity',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 24: RAJASTHAN STATE POLITY & GOVERNANCE (4 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T24-01',
    slug: 'political-demography-electoral-geography-social-stratification-rajasthan',
    title: 'Political Demography, Electoral Geography & Social Stratification of Rajasthan',
    shortDefinition: 'Structural demographic and electoral geography of Rajasthan based on Census 2011 baseline data (6.85 Cr population, density 200/km2, sex ratio 928, literacy 66.1%), regional divisions (Marwar, Mewar, Dhundhar, Hadoti, Shekhawati), 200 Assembly seats (34 SC, 25 ST), and 25 Lok Sabha seats (4 SC, 3 ST).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Rajasthan State Polity: Executive, Assembly, Demography & Apex Institutions',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T24-02',
    slug: 'state-executive-rajasthan-governor-chief-minister-council-of-ministers',
    title: 'State Executive of Rajasthan: Governor, Chief Minister & Council of Ministers',
    shortDefinition: 'The institutional evolution and constitutional operational dynamics of the State Executive in Rajasthan under Articles 153–167, transitioning on 1 November 1956 from Rajpramukh to Governor (First Governor: Gurumukh Nihal Singh), Chief Ministership milestones, CM Secretariat, and discretionary gubernatorial governance.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Rajasthan State Polity: Executive, Assembly, Demography & Apex Institutions',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T24-03',
    slug: 'rajasthan-legislative-assembly-evolution-committees-unicameral-procedure',
    title: 'Rajasthan Legislative Assembly (Vidhan Sabha): Evolution, Committees & Unicameral Procedure',
    shortDefinition: 'The constitutional architecture and procedural mechanics of the unicameral Rajasthan Legislative Assembly under Articles 168–212, its historical seat growth from 160 (1952) to 200 (1977 6th Assembly), legislative committees (PAC, Estimates, PUC), Speaker prerogatives, and assembly quorum.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Rajasthan State Polity: Executive, Assembly, Demography & Apex Institutions',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T24-04',
    slug: 'judicial-and-constitutional-bodies-rajasthan-high-court-rpsc',
    title: 'Judicial & Constitutional Bodies of Rajasthan: High Court (Jodhpur/Jaipur) & RPSC (Ajmer)',
    shortDefinition: 'The constitutional architecture and operational dynamics of apex state institutions: Rajasthan High Court under Article 214 (inaugurated 29 Aug 1949 at Jodhpur, Satyanarayan Rao Committee Jaipur Bench 1977, 50 judges) and Rajasthan Public Service Commission under Article 315 (constituted 20 Aug 1949, shifted to Ajmer 1956, 1 Chair + 7 Members, appointment by Governor vs removal by President).',
    difficulty: 'ADVANCED',
    topicTitle: 'Rajasthan State Polity: Executive, Assembly, Demography & Apex Institutions',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // TOPIC 25: COMPARATIVE CONSTITUTIONAL SYSTEMS (3 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-T25-01',
    slug: 'constitutional-models-sovereignty-uk-usa-indian-synthesis',
    title: 'Constitutional Models & Sovereignty: UK Parliamentary Sovereignty vs USA Judicial Supremacy vs Indian Synthesis',
    shortDefinition: 'Comparative constitutional analysis of the British unwritten constitution and Diceyan Parliamentary Sovereignty, the American rigid written constitution and judicial supremacy with substantive Due Process, and the Indian constitutional synthesis of parliamentary executive with judicial review bound by the Basic Structure Doctrine.',
    difficulty: 'ADVANCED',
    topicTitle: 'Comparative Constitutional Systems: UK, USA, Canada, Germany & Switzerland',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T25-02',
    slug: 'comparative-federal-architectures-usa-canada-australia-germany-india',
    title: 'Comparative Federal Architectures: USA, Canada, Australia, Germany & Indian Asymmetric Federalism',
    shortDefinition: 'Comparative analysis of major federal systems: American Dual Federalism (indestructible states, dual citizenship), Canadian Strong-Centre Federalism (Governor appointment, central residuary powers), Australian Cooperative Federalism (Concurrent list, trade commerce), German Administrative Federalism (Bundesrat), and India\'s Quasi-Federal model with asymmetric constitutional provisions.',
    difficulty: 'ADVANCED',
    topicTitle: 'Comparative Constitutional Systems: UK, USA, Canada, Germany & Switzerland',
    subjectName: 'Indian Polity',
  },
  {
    id: 'CON-T25-03',
    slug: 'instruments-direct-democracy-plural-executive-swiss-model',
    title: 'Instruments of Direct Democracy & Plural Executive: The Swiss Constitutional Model',
    shortDefinition: 'The constitutional architecture of the Swiss Confederation (Federal Constitution of 1999), the four instruments of Direct Democracy (Mandatory/Optional Referendum, Popular Initiative, Recall, Landsgemeinde), and the unique 7-member collegial Plural Executive (Federal Council) with an annually rotating Federal President.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Comparative Constitutional Systems: UK, USA, Canada, Germany & Switzerland',
    subjectName: 'Indian Polity',
  },

  // =========================================================================
  // ECONOMICS: INFLATION BENCHMARK (5 CONCEPTS)
  // =========================================================================
  {
    id: 'CON-ECON-INF-01',
    slug: 'inflation-definition-distinctions-real-nominal',
    title: 'Inflation Definition, Rate vs Level & Real-Nominal Distinctions',
    shortDefinition: 'Persistent generalized price rise, speedometer disinflation, and Fisher equation exact compounding.',
    difficulty: 'BEGINNER',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  {
    id: 'CON-ECON-INF-02',
    slug: 'price-indices-measurement-cpi-wpi-core-headline',
    title: 'Price Indices & Measurement: CPI, WPI, Core vs Headline & Base Effect',
    shortDefinition: 'NSO CPI vs DPIIT WPI commodity scope, Laspeyres weighting, and 3-step Base Effect price ladders.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  {
    id: 'CON-ECON-INF-03',
    slug: 'inflation-causes-mechanisms-demand-cost-structural',
    title: 'Causal Mechanisms: Demand-Pull, Cost-Push & Structural Inflation',
    shortDefinition: 'Factory sustainable output gap, landed currency pass-through ($100 at ₹75 vs ₹85), and structural bottlenecks.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  {
    id: 'CON-ECON-INF-04',
    slug: 'inflation-distributional-impacts-growth-tradeoffs-phillips-curve',
    title: 'Distributional Impacts, Growth Trade-Offs & Phillips Curve Dynamics',
    shortDefinition: 'Fixed vs floating loan debt redistribution, fiscal bracket creep, and Indian 4-6% empirical threshold.',
    difficulty: 'ADVANCED',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  {
    id: 'CON-ECON-INF-05',
    slug: 'inflation-policy-framework-rbi-mpc-flexible-targeting-supply-side',
    title: 'Policy Framework: RBI Flexible Inflation Targeting & Supply-Side Policy',
    shortDefinition: 'Section 45ZA mandate, monetary transmission frictions (EBLR), and the Two Hands of Policy boundary.',
    difficulty: 'ADVANCED',
    topicTitle: 'Inflation Dynamics, Measurement & Policy',
    subjectName: 'Indian Economy',
  },
  // =========================================================================
  // BATCH P7 DEEPENED CONCEPTS
  // =========================================================================
  {
    id: 'CON-T23-06',
    slug: 'district-administration-citizen-charters-sevottam-model-public-service-guarantee-acts',
    title: 'District Administration, Citizen Charters, Sevottam Model & Public Service Guarantee Acts',
    shortDefinition: 'District Collector 3-in-1 role (Warren Hastings 1772), Board of Revenue Ajmer (1949), Sevottam Model (IS 15700:2005), and Rajasthan Public Services Guarantee Act 2011.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Statutory, Regulatory & Quasi-Judicial Bodies',
    subjectName: 'Indian Polity & Constitutional Dynamics',
  },
  {
    id: 'CON-T11-07',
    slug: 'coalition-governments-common-minimum-programme-hung-assemblies-pressure-groups',
    title: 'Coalition Governments, Common Minimum Programme, Hung Assemblies & Pressure Groups',
    shortDefinition: 'Coalition governance dynamics (1989-2014), Common Minimum Programme, Sarkaria-Punchhi hung assembly hierarchy, and Almond pressure group typology.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'The Union Executive: President, Vice-President, PM & Council of Ministers',
    subjectName: 'Indian Polity & Constitutional Dynamics',
  },
  {
    id: 'CON-T22-05',
    slug: 'determinants-voting-behavior-evm-vvpat-architecture-electoral-technology-reforms',
    title: 'Determinants of Voting Behavior, EVM-VVPAT Architecture & Electoral Technology Reforms',
    shortDefinition: 'Voting behavior determinants, EVM standalone air-gapped architecture, VVPAT 7-second audit slip, ADR v. ECI (2024) Supreme Court verdict, and cVIGIL/ENCORE.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Election Commission of India & Electoral Governance',
    subjectName: 'Indian Polity & Constitutional Dynamics',
  },
  {
    id: 'CON-T20-05',
    slug: 'national-integration-mechanisms-inter-state-council-internal-security-framework',
    title: 'National Integration Mechanisms, Inter-State Council & Internal Security Framework',
    shortDefinition: 'National Integration Council (1961), Article 263 Inter-State Council (1990), Zonal Councils (1956 Act), Article 355 Union duty, and NIA/UAPA/AFSPA statutory security stack.',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Emergency Provisions & Federal Security Architecture',
    subjectName: 'Indian Polity & Constitutional Dynamics',
  },
  {
    id: 'CON-T04-09',
    slug: 'official-language-constitutional-scheme-part-xvii-special-directives-constitutional-morality',
    title: 'Official Language Constitutional Scheme (Part XVII), Special Linguistic Directives & Constitutional Morality',
    shortDefinition: 'Part XVII (Arts 343-351), Official Languages Act 1963/1967, Art 348 judicial language, Arts 350A/350B (7th CAA), and the doctrine of Constitutional Morality (Ambedkar to Navtej Johar).',
    difficulty: 'INTERMEDIATE',
    topicTitle: 'Schedules of the Indian Constitution & Language Scheme',
    subjectName: 'Indian Polity & Constitutional Dynamics',
  },
  {
    id: 'CON-T19-06',
    slug: 'inter-state-river-water-disputes-boundary-adjudication-sub-classification-jurisprudence',
    title: 'Inter-State River Water Disputes (Article 262), Boundary Adjudication & Sub-Classification Jurisprudence',
    shortDefinition: 'Article 262 & ISRWD Act 1956 (court jurisdiction ouster), Article 131 boundary disputes, and the 7-judge Supreme Court bench ruling in State of Punjab v. Davinder Singh (2024) permitting SC/ST sub-classification.',
    difficulty: 'ADVANCED',
    topicTitle: 'Centre-State Relations, Federal Finance & Inter-State Governance',
    subjectName: 'Indian Polity & Constitutional Dynamics',
  },
];
