import { db } from '../db/client';

export interface BatchASemanticUnit {
  semanticUnitId: string;
  topicNumber: number;
  pdfPage: number;
  printedPage: number;
  localHeading: string;
  contentType:
    | 'FACT'
    | 'CONSTITUTIONAL_TEXT'
    | 'LEGAL_RULE'
    | 'JUDICIAL_DOCTRINE'
    | 'HISTORICAL_CLAIM'
    | 'CONCEPT'
    | 'DEFINITION'
    | 'EXPLANATION'
    | 'COMPARISON'
    | 'COMPARISON_TABLE'
    | 'VISUAL_DIAGRAM'
    | 'EXCEPTION_QUALIFICATION'
    | 'MNEMONIC'
    | 'PYQ'
    | 'EXAM_TRAP';
  origin: 'TEXT_DERIVED' | 'VISUAL_DERIVED' | 'TABLE_DERIVED' | 'MIXED';
  shortDescription: string;
  rawExcerpt?: string;
  requiresVerification: boolean;
  status: 'INVENTORIED' | 'REVIEW_REQUIRED' | 'VERIFIED' | 'CANONICALIZED';
  notes?: string;
}

export const BATCH_A_SEMANTIC_UNITS: BatchASemanticUnit[] = [
  // ==========================================
  // TOPIC 1: BASIC CONCEPTS OF POLITY (PDF 7-9)
  // ==========================================
  {
    semanticUnitId: 'SEM-T1-01',
    topicNumber: 1,
    pdfPage: 7,
    printedPage: 1,
    localHeading: 'Definition and Essential Elements of State',
    contentType: 'DEFINITION',
    origin: 'TEXT_DERIVED',
    shortDescription: 'State defined as community residing in definite territory governed by sovereign government free from external control. 4 elements: Territory, Population, Government, Sovereignty.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T1-02',
    topicNumber: 1,
    pdfPage: 7,
    printedPage: 1,
    localHeading: "Kautilya's Saptanga Theory of State",
    contentType: 'CONCEPT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Arthashastra 7 organic elements: King (Swami), Amatya (Minister), Janapada (Territory/People), Durga (Fort/Capital), Kosha (Treasury), Danda/Bala (Army), Mitra (Ally).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T1-03',
    topicNumber: 1,
    pdfPage: 7,
    printedPage: 1,
    localHeading: 'State vs Nation Distinction',
    contentType: 'COMPARISON',
    origin: 'TABLE_DERIVED',
    shortDescription: 'State is a political-legal entity; Nation is a socio-cultural-psychological entity of shared language, customs, historical continuity. Classification table (India, Japan, USA, Arab Nation).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T1-04',
    topicNumber: 1,
    pdfPage: 7,
    printedPage: 1,
    localHeading: 'Divine Origin and Social Contract Theories of State',
    contentType: 'CONCEPT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Divine theory (King as shadow of God / Jillh-e-Ilahi); Social Contract (Hobbes, Locke, Rousseau; State of Nature as Matsya Nyaya; mutual surrender of freedom for ordered rule).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T1-05',
    topicNumber: 1,
    pdfPage: 8,
    printedPage: 2,
    localHeading: 'System of Governance in India: Dual Legislature, Dual Executive, Unified Judiciary',
    contentType: 'EXPLANATION',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Dual legislature (Centre & States), Dual executive (Union & State Council of Ministers), Unified single integrated judiciary (HCs subordinate to SC).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T1-06',
    topicNumber: 1,
    pdfPage: 8,
    printedPage: 2,
    localHeading: 'Separation of Powers & Constitutional Supremacy (India vs UK vs USA)',
    contentType: 'COMPARISON_TABLE',
    origin: 'VISUAL_DERIVED',
    shortDescription: 'India: Parliamentary system with Constitutional Supremacy; UK: Parliamentary Sovereignty with Executive/Judiciary inside Parliament; USA: Presidential with strict Separation of Powers.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T1-07',
    topicNumber: 1,
    pdfPage: 9,
    printedPage: 3,
    localHeading: 'Constitution: Etymology, Definition and 4 Core Functions',
    contentType: 'DEFINITION',
    origin: 'TEXT_DERIVED',
    shortDescription: "Derived from Latin 'Constitutio' (to establish/command). Supreme formal document defining political structure, citizenship rights/duties, socio-economic goals, national values.",
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T1-08',
    topicNumber: 1,
    pdfPage: 9,
    printedPage: 3,
    localHeading: 'Constitutionalism: Meaning, 5 Pillars and Constitution vs Constitutionalism',
    contentType: 'CONCEPT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'System of limited government under rule of law. 5 pillars: Limited government, Rule of law, Protection of rights, Separation of powers, Judicial review.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },

  // ==========================================
  // TOPIC 2: CONSTITUENT ASSEMBLY (PDF 10-19)
  // ==========================================
  {
    semanticUnitId: 'SEM-T2-01',
    topicNumber: 2,
    pdfPage: 10,
    printedPage: 4,
    localHeading: 'Historical Evolution & Demand for Constituent Assembly (1895–1946)',
    contentType: 'HISTORICAL_CLAIM',
    origin: 'TEXT_DERIVED',
    shortDescription: '1895 Swaraj Bill (Tilak), 1922 Gandhi, 1928 Nehru Report, 1934 M.N. Roy, 1935 INC official demand, 1938 Nehru declaration, 1940 August Offer, 1942 Cripps Mission, 1946 Cabinet Mission.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T2-02',
    topicNumber: 2,
    pdfPage: 11,
    printedPage: 5,
    localHeading: 'Composition, Seat Allocation and Electoral Method of Constituent Assembly',
    contentType: 'FACT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Total 389 seats (292 British Provinces, 93 Princely States, 4 Chief Commissioner Provinces: Delhi, Ajmer-Merwara, Coorg, British Balochistan). Proportional representation by single transferable vote.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T2-03',
    topicNumber: 2,
    pdfPage: 12,
    printedPage: 6,
    localHeading: '1946 Elections, Party Representation and Post-Partition Restructuring',
    contentType: 'FACT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'July-Aug 1946 elections: INC 208, Muslim League 73, Others 15. Post-partition strength reduced from 389 to 299 (229 British Provinces, 70 Princely States).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T2-04',
    topicNumber: 2,
    pdfPage: 13,
    printedPage: 7,
    localHeading: 'First Meeting, Leadership and Key Functionaries',
    contentType: 'FACT',
    origin: 'TEXT_DERIVED',
    shortDescription: '1st meeting Dec 9, 1946 (Dr. Sachchidananda Sinha temporary chairman); Dec 11, 1946 Dr. Rajendra Prasad elected permanent President; H.C. Mukherjee & V.T. Krishnamachari VPs; Sir B.N. Rau Constitutional Advisor.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T2-05',
    topicNumber: 2,
    pdfPage: 14,
    printedPage: 8,
    localHeading: 'Objectives Resolution & Dual Role of Constituent Assembly',
    contentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Moved Dec 13, 1946 by Nehru, adopted Jan 22, 1947. Dual role under Indian Independence Act 1947: Constitution-making (Dr. Rajendra Prasad) and Provisional Parliament (G.V. Mavalankar).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T2-06',
    topicNumber: 2,
    pdfPage: 15,
    printedPage: 9,
    localHeading: 'Major Committees of Constituent Assembly & The Drafting Committee',
    contentType: 'FACT',
    origin: 'TABLE_DERIVED',
    shortDescription: 'Drafting Committee set up Aug 29, 1947 with 7 members: Dr. B.R. Ambedkar (Chairman), N. Gopalaswamy Ayyangar, Alladi Krishnaswamy Iyer, K.M. Munshi, Mohammad Saadulla, N. Madhava Rau, T.T. Krishnamachari.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T2-07',
    topicNumber: 2,
    pdfPage: 16,
    printedPage: 10,
    localHeading: 'Important Historical Dates, Symbols, Calligraphers & Rajasthan Members',
    contentType: 'FACT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Seal (Elephant), Secretary (H.V.R. Iyengar), Chief Draftsman (S.N. Mukherjee), Calligraphers (Prem Behari Narain Raizada, Vasant Krishan Vaidya), Artists (Nandalal Bose, Beohar Sinha). 14 members from Rajasthan.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T2-08',
    topicNumber: 2,
    pdfPage: 17,
    printedPage: 11,
    localHeading: 'Criticisms of the Constituent Assembly & Systematic Rebuttals',
    contentType: 'EXPLANATION',
    origin: 'TEXT_DERIVED',
    shortDescription: "6 major criticisms & rebuttals: Non-representative body, Sovereignty defect, Time-consuming ('Drifting Committee' - Naziruddin Ahmad), Congress dominance (Granville Austin), Hindu dominance (Churchill/Simon), Lawyer-politician paradise.",
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T2-09',
    topicNumber: 2,
    pdfPage: 18,
    printedPage: 12,
    localHeading: 'Sessions of Assembly & Key Sources Borrowed (1935 Act, UK, USA)',
    contentType: 'FACT',
    origin: 'TABLE_DERIVED',
    shortDescription: '11 regular sessions + 12th session (Jan 24, 1950). Sources: 1935 Act (Federal structure, Governor, Judiciary, UPSC), UK (Parliamentary system, Rule of Law, Writs, Cabinet), USA (FRs, Judicial review, Preamble phrase).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T2-10',
    topicNumber: 2,
    pdfPage: 19,
    printedPage: 13,
    localHeading: 'Sources Borrowed from Canada, Ireland, South Africa, Australia, France, USSR, Germany, Japan',
    contentType: 'FACT',
    origin: 'TABLE_DERIVED',
    shortDescription: 'Canada (Strong Centre, Residuary powers), Ireland (DPSPs, RS nomination), South Africa (Amendment, RS election), Australia (Concurrent List, Joint Sitting), France (Republic, Liberty/Equality/Fraternity), USSR (FDs, Justice), Germany (Suspension of FRs), Japan (Procedure established by law).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },

  // ==========================================
  // TOPIC 3: PREAMBLE (PDF 20-33)
  // ==========================================
  {
    semanticUnitId: 'SEM-T3-01',
    topicNumber: 3,
    pdfPage: 20,
    printedPage: 14,
    localHeading: 'Verbatim Text, Historical Origin and Adoption Date',
    contentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Complete text of Preamble; derived from Objectives Resolution; enacted at the conclusion of Constitution drafting (Oct 17, 1949); adopted Nov 26, 1949.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T3-02',
    topicNumber: 3,
    pdfPage: 21,
    printedPage: 15,
    localHeading: "Source of Authority: 'We The People of India' & Popular Sovereignty",
    contentType: 'CONCEPT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Derives authority directly from the people of India (popular sovereignty), not an external British monarch or statutory grant.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T3-03',
    topicNumber: 3,
    pdfPage: 22,
    printedPage: 16,
    localHeading: 'Nature of State: Sovereign (Internal & External Dimensions)',
    contentType: 'CONCEPT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Internal supremacy and absolute external independence. Power to acquire or cede territory (Berubari 1960, 100th Amendment 2015). UN/Commonwealth membership does not curtail sovereignty.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T3-04',
    topicNumber: 3,
    pdfPage: 23,
    printedPage: 17,
    localHeading: 'Nature of State: Socialist (Democratic vs Communist Socialism)',
    contentType: 'CONCEPT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Democratic socialism / Fabian mixed economy; elimination of poverty, ignorance, disease, inequality (Excel Wear 1978, D.S. Nakara 1983). Added by 42nd Amendment 1976.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T3-05',
    topicNumber: 3,
    pdfPage: 24,
    printedPage: 18,
    localHeading: 'Nature of State: Secular (Indian Positive Secularism vs Western Separation)',
    contentType: 'CONCEPT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Indian positive secularism: Sarva Dharma Sambhava (equal respect & protection, state intervention for social reform under Arts 25-28), distinct from Western negative wall of separation. S.R. Bommai 1994 (Basic structure). Added by 42nd Amendment 1976.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T3-06',
    topicNumber: 3,
    pdfPage: 25,
    printedPage: 19,
    localHeading: 'Nature of State: Democratic & Republic',
    contentType: 'CONCEPT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Representative Parliamentary Democracy with adult suffrage (Art 326), periodic elections, rule of law; Republic: Elected Head of State (President) for fixed tenure, absence of hereditary monarch, public offices open to all.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T3-07',
    topicNumber: 3,
    pdfPage: 26,
    printedPage: 20,
    localHeading: 'Constitutional Objectives: Justice (Social, Economic, Political)',
    contentType: 'CONCEPT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Three dimensions of Justice inspired by 1917 Russian Revolution: Social justice (elimination of social discrimination), Economic justice (non-concentration of wealth, Arts 39(b)/(c)), Political justice (equal voting and political participation, Arts 325 & 326).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T3-08',
    topicNumber: 3,
    pdfPage: 27,
    printedPage: 21,
    localHeading: 'Constitutional Objectives: Liberty, Equality, Fraternity and Dignity',
    contentType: 'CONCEPT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Liberty (Thought, Expression, Belief, Faith, Worship; French Revolution 1789; bounded by reasonable restrictions); Equality (Status and Opportunity, Arts 14-18); Fraternity (Common brotherhood, single citizenship, individual dignity, unity and integrity).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T3-09',
    topicNumber: 3,
    pdfPage: 28,
    printedPage: 22,
    localHeading: 'Status of Preamble as Part of Constitution (Berubari vs Kesavananda vs LIC)',
    contentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Berubari Union (1960 - not part of Constitution) overruled by Kesavananda Bharati (1973 - 13-judge bench, integral part, enactable by same process). Reaffirmed in LIC of India (1995).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T3-10',
    topicNumber: 3,
    pdfPage: 29,
    printedPage: 23,
    localHeading: 'Amendability of Preamble & 42nd Constitutional Amendment Act 1976',
    contentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Preamble can be amended under Article 368 subject to Basic Structure doctrine. 42nd Amendment 1976 added three words: Socialist, Secular, and Integrity.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T3-11',
    topicNumber: 3,
    pdfPage: 30,
    printedPage: 24,
    localHeading: 'Legal Effect and Enforceability of the Preamble',
    contentType: 'LEGAL_RULE',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Preamble is non-justiciable (not enforceable in courts), neither a source of substantive legislative power nor a prohibition on legislative power. Acts as an interpretative key during statutory ambiguity.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T3-12',
    topicNumber: 3,
    pdfPage: 31,
    printedPage: 25,
    localHeading: 'Eminent Jurists and Scholars Quotes on the Preamble',
    contentType: 'FACT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Palkhivala (Identity Card), K.M. Munshi (Political Horoscope), Alladi (Dreamt so long), Thakur Das Bhargava (Soul/Jewel), Ernest Barker (Key-note), M. Hidayatullah (Declaration of Independence).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },

  // ==========================================
  // TOPIC 4: SCHEDULES (PDF 34-40)
  // ==========================================
  {
    semanticUnitId: 'SEM-T4-01',
    topicNumber: 4,
    pdfPage: 34,
    printedPage: 28,
    localHeading: 'Overview, Evolution & 1st to 4th Schedules',
    contentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Originally 8 Schedules in 1949; 12 today. 1st Schedule (States & UTs territorial extent); 2nd Schedule (Salaries/emoluments of President, Governors, Judges, CAG; ministers excluded); 3rd Schedule (Oaths of ministers, MPs, judges; President/VP/Governor excluded); 4th Schedule (Rajya Sabha seat allocation).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T4-02',
    topicNumber: 4,
    pdfPage: 35,
    printedPage: 29,
    localHeading: '5th and 6th Schedules (Scheduled & Tribal Areas Administration)',
    contentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TABLE_DERIVED',
    shortDescription: '5th Schedule (10 states excluding AMTM; Tribes Advisory Council max 20 members, 3/4th ST MLAs; Governor discretionary modifications); 6th Schedule (Assam, Meghalaya, Tripura, Mizoram - AMTM; Autonomous District Councils max 30 members: 26 elected, 4 nominated; 5-yr term).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T4-03',
    topicNumber: 4,
    pdfPage: 36,
    printedPage: 30,
    localHeading: '7th Schedule: Union, State, Concurrent Lists & 42nd Amendment Shift',
    contentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Article 246 division: Union List (orig 97 -> 100), State List (orig 66 -> 61), Concurrent List (orig 47 -> 52). 42nd Amendment transferred 5 subjects from State to Concurrent: Education, Forests, Weights & Measures, Wild animals/birds protection, Administration of justice/subordinate courts. Residuary powers to Parliament (Art 248).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T4-04',
    topicNumber: 4,
    pdfPage: 37,
    printedPage: 31,
    localHeading: '8th Schedule: 22 Languages, 3 Amendments & 11 Classical Languages',
    contentType: 'FACT',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Original 14 languages; 21st Amendment (1967 - Sindhi), 71st Amendment (1992 - Konkani, Manipuri, Nepali), 92nd Amendment (2003 - Bodo, Dogri, Maithili, Santhali) -> 22 languages. English & Rajasthani not included. 11 Classical Languages recognized by Ministry of Culture (including 2024: Assamese, Bengali, Marathi, Pali, Prakrit).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T4-05',
    topicNumber: 4,
    pdfPage: 38,
    printedPage: 32,
    localHeading: '9th Schedule: Origin, Land Reforms & I.R. Coelho Doctrine (2007)',
    contentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Added by 1st Amendment 1951 + Art 31B to shield agrarian land reforms & Zamindari abolition from judicial review. I.R. Coelho v. State of Tamil Nadu (2007, 9 judges): Laws inserted after April 24, 1973 (Kesavananda Bharati date) open to judicial review for Basic Structure violations.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T4-06',
    topicNumber: 4,
    pdfPage: 39,
    printedPage: 33,
    localHeading: '10th Schedule: Anti-Defection Law, 52nd & 91st Amendments, Whip Convention',
    contentType: 'LEGAL_RULE',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Added by 52nd Amendment 1985 (Arts 102(2) & 191(2)). Grounds: voluntary resignation from party, voting against party whip without 15-day condonation, independent joining party, nominated joining after 6 months. 91st Amendment 2003 deleted 1/3rd split; retained 2/3rd merger. Note: Whip is British convention, not in Constitution.',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
  {
    semanticUnitId: 'SEM-T4-07',
    topicNumber: 4,
    pdfPage: 40,
    printedPage: 34,
    localHeading: '10th Schedule Judicial Evolution (Kihoto Holohan, Keisham Meghchandra) & 11th/12th Schedules',
    contentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    shortDescription: 'Kihoto Holohan (1992 - Speaker decision subject to judicial review, Section 7 void); Keisham Meghchandra Singh (2020 - Speaker must decide within 3 months, SC Art 142 powers). 11th Schedule (73rd Amendment 1992, Art 243G, 29 Panchayat subjects); 12th Schedule (74th Amendment 1992, Art 243W, 18 Municipal subjects).',
    requiresVerification: false,
    status: 'CANONICALIZED',
  },
];

export async function seedBatchASemanticInventory() {
  console.log(`Seeding Batch A semantic units (${BATCH_A_SEMANTIC_UNITS.length} units)...`);

  const source = await db.source.upsert({
    where: { id: 'CERAMIC-POLITY-2026' },
    update: {},
    create: {
      id: 'CERAMIC-POLITY-2026',
      title: 'Ceramic Polity Treatise (2026)',
      sourceType: 'COACHING_COMPILATION',
      authorityTier: 'TIER_C_EDUCATIONAL',
      description: 'Comprehensive Indian Polity treatise by Ceramic Academy (408 pages).',
      identifier: 'Indian-Polity-English-[2026]-pdf.pdf',
    },
  });

  return BATCH_A_SEMANTIC_UNITS.length;
}
