/**
 * Economics Master Source Inventory & Salvage Crosswalk
 * Mind of Aravalli — Academic Reading Hub
 *
 * Provides typed provenance metadata, defect logs, salvage verdicts,
 * and canonical domain mappings for all 47 master source units from
 * `03_Indian_Economy_Macro_Master.md`.
 */

export type SalvageVerdict =
  | 'KEEP_AS_IS'
  | 'KEEP_EDIT'
  | 'REWRITE'
  | 'RESEARCH_REQUIRED'
  | 'DISCARD'
  | 'DUPLICATE'
  | 'OUTDATED';

export type TargetDomainCode =
  | 'DOMAIN_A_FOUNDATIONS'
  | 'DOMAIN_B_MICROECONOMICS'
  | 'DOMAIN_C_MACROECONOMICS'
  | 'DOMAIN_D_INFLATION'
  | 'DOMAIN_E_MONEY_MONETARY'
  | 'DOMAIN_F_BANKING_FINANCIAL'
  | 'DOMAIN_G_FISCAL_PUBLIC_FINANCE'
  | 'DOMAIN_H_EXTERNAL_SECTOR'
  | 'DOMAIN_I_DEVELOPMENT'
  | 'DOMAIN_J_INDIAN_ECONOMY'
  | 'DOMAIN_K_AGRICULTURE_RURAL'
  | 'DOMAIN_L_INDUSTRY_INFRASTRUCTURE'
  | 'DOMAIN_M_LABOUR_SOCIAL'
  | 'DOMAIN_N_INSTITUTIONS_POLICY'
  | 'DOMAIN_O_RAJASTHAN_ECONOMY';

export interface EconomicsSourceNote {
  noteNumber: number;
  sourceTitle: string;
  category: string;
  targetDomain: TargetDomainCode;
  targetDomainTitle: string;
  salvageVerdict: SalvageVerdict;
  targetConceptIds: string[];
  primaryDefects: string[];
  authoritativeSources: string[];
  verifiedYear: number;
}

export const ECONOMICS_SOURCE_INVENTORY: EconomicsSourceNote[] = [
  {
    noteNumber: 1,
    sourceTitle: 'Absolute vs Relative Poverty & Lorenz Curve / Gini Index',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetDomain: 'DOMAIN_I_DEVELOPMENT',
    targetDomainTitle: 'Domain I: Development Economics, Poverty & Sustainability',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-37', 'CON-ECO-38'],
    primaryDefects: ['Empty latex block', 'Stray dollar delimiter on percentages ($x%$)'],
    authoritativeSources: ['World Bank Poverty & Inequality Platform', 'NITI Aayog National MPI Report', 'Atkinson (1970) On the Measurement of Economic Inequality'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 2,
    sourceTitle: 'Agriculture Sector & MSP Architecture',
    category: 'Book III: Indian Economic Structure & Sectors',
    targetDomain: 'DOMAIN_K_AGRICULTURE_RURAL',
    targetDomainTitle: 'Domain K: Agriculture, Food Security & Rural Economy',
    salvageVerdict: 'REWRITE',
    targetConceptIds: ['CON-ECO-30', 'CON-ECO-32'],
    primaryDefects: ['Superficial MSP coverage', 'Lacks CACP cost formula derivations (A2, A2+FL, C2)', 'Missing PM-AASHA and e-NAM integration'],
    authoritativeSources: ['Commission for Agricultural Costs and Prices (CACP) Price Policy Reports', 'National Commission on Farmers (Swaminathan Committee, 2006)', 'Ministry of Agriculture & Farmers Welfare Operational Guidelines'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 3,
    sourceTitle: "Amartya Sen's Capability Approach & Entitlements",
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetDomain: 'DOMAIN_I_DEVELOPMENT',
    targetDomainTitle: 'Domain I: Development Economics, Poverty & Sustainability',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-39'],
    primaryDefects: ['Purely qualitative text', 'Lacks mathematical linkage to Human Development Index geometric mean formulation'],
    authoritativeSources: ['Amartya Sen (1981) Poverty and Famines: An Essay on Entitlement and Deprivation', 'Amartya Sen (1999) Development as Freedom', 'UNDP Human Development Report Methodology'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 4,
    sourceTitle: 'Balance of Payments (BoP) & Foreign Exchange Reserves',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_H_EXTERNAL_SECTOR',
    targetDomainTitle: 'Domain H: External Sector & International Economics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-26'],
    primaryDefects: ['Contains stale 2021 BoP figures', 'High-density dollar formatting'],
    authoritativeSources: ['RBI Balance of Payments Manual (BPM6 alignment)', 'IMF Balance of Payments and International Investment Position Manual (BPM6)', 'RBI Bulletin — Developments in India’s Balance of Payments'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 5,
    sourceTitle: 'Basel Accords & Risk-Weighted Asset Framework',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_F_BANKING_FINANCIAL',
    targetDomainTitle: 'Domain F: Banking & Financial System',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-23'],
    primaryDefects: ['Needs updated Domestic Systemically Important Banks (D-SIBs) bucket list', 'Raw dollar delimiter on percentages'],
    authoritativeSources: ['Basel Committee on Banking Supervision (BCBS) Basel III Framework', 'RBI Master Circular — Basel III Capital Regulations', 'RBI Financial Stability Report'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 6,
    sourceTitle: 'Capital Market Instruments: Equities, Bonds & Derivatives',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_F_BANKING_FINANCIAL',
    targetDomainTitle: 'Domain F: Banking & Financial System',
    salvageVerdict: 'REWRITE',
    targetConceptIds: ['CON-ECO-11'],
    primaryDefects: ['Missing derivative pricing mathematics (Black-Scholes, Greeks)', 'Lacks bond duration/convexity', 'Missing SEBI LODR and PIT statutory regulations'],
    authoritativeSources: ['SEBI (LODR) Regulations, 2015', 'SEBI (PIT) Regulations, 2015', 'John C. Hull — Options, Futures, and Other Derivatives', 'Frank Fabozzi — Bond Markets, Analysis, and Strategies'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 7,
    sourceTitle: 'Central Banking & RBI Functions',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_E_MONEY_MONETARY',
    targetDomainTitle: 'Domain E: Money & Monetary Economics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-12'],
    primaryDefects: ['Needs updated Central Board composition', 'Minor formatting cleanup'],
    authoritativeSources: ['Reserve Bank of India Act, 1934 (Sections 3, 17, 45ZB)', 'Banking Regulation Act, 1949', 'RBI Annual Report'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 8,
    sourceTitle: 'Circular Flow of Income, Factor Payments & Leakages',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_C_MACROECONOMICS',
    targetDomainTitle: 'Domain C: National Income & Macroeconomics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-03'],
    primaryDefects: ['Delimiters on variable symbols', 'Repetitive summary boilerplate'],
    authoritativeSources: ['Richard Stone (1947) Definition and Measurement of National Income', 'N. Gregory Mankiw — Macroeconomics', 'UN System of National Accounts (SNA 2008)'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 9,
    sourceTitle: 'Commercial Banking & Money Creation',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_E_MONEY_MONETARY',
    targetDomainTitle: 'Domain E: Money & Monetary Economics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-09'],
    primaryDefects: ['High-density dollar formatting in balance sheet examples'],
    authoritativeSources: ['Paul Samuelson & William Nordhaus — Economics', 'RBI Working Group on Money Supply (Y.V. Reddy Committee, 1998)', 'Frederic Mishkin — The Economics of Money, Banking, and Financial Markets'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 10,
    sourceTitle: 'CPI vs. WPI Inflation Indices & Food Inflation Dynamics',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_D_INFLATION',
    targetDomainTitle: 'Domain D: Inflation, Price Theory & Employment',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-16'],
    primaryDefects: ['Empty code block', 'Needs latest CPI Combined and WPI group weightings table'],
    authoritativeSources: ['MoSPI / NSO Consumer Price Index (CPI) Base 2012 Methodology', 'Office of the Economic Adviser, DPIIT Wholesale Price Index (WPI) Base 2011-12 Methodology', 'Urjit Patel Committee Report on Monetary Policy Framework (2014)'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 11,
    sourceTitle: 'Evolution of Indian Economic Planning: PC to NITI Aayog',
    category: 'Book III: Indian Economic Structure & Sectors',
    targetDomain: 'DOMAIN_J_INDIAN_ECONOMY',
    targetDomainTitle: 'Domain J: Indian Economic Development & Structural Reforms',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-44'],
    primaryDefects: ['Pure text narrative; needs structured comparative table of Planning Commission vs NITI Aayog'],
    authoritativeSources: ['NITI Aayog Notification (Cabinet Resolution No. 511/2/1/2015-Cab)', 'Planning Commission Five-Year Plan Documents', 'NITI Aayog Strategy for New India @ 75'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 12,
    sourceTitle: 'Exchange Rate Regimes & Rupee Convertibility',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_H_EXTERNAL_SECTOR',
    targetDomainTitle: 'Domain H: External Sector & International Economics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-27'],
    primaryDefects: ['Dollar signs on acronyms like $LERMS$'],
    authoritativeSources: ['Tarapore Committee Reports on Full Capital Account Convertibility', 'Foreign Exchange Management Act, 1999 (FEMA)', 'RBI Master Direction — External Commercial Borrowings'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 13,
    sourceTitle: 'Factor Cost, Market Price & GVA at Basic Prices',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_C_MACROECONOMICS',
    targetDomainTitle: 'Domain C: National Income & Macroeconomics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-04'],
    primaryDefects: ['Formatting density on sub/superscripts'],
    authoritativeSources: ['MoSPI National Accounts Statistics: Sources and Methods 2015', 'UN System of National Accounts (SNA 2008)', 'Economic Survey of India'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 14,
    sourceTitle: 'Financial Inclusion Initiatives & Priority Sector Lending Targets',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_F_BANKING_FINANCIAL',
    targetDomainTitle: 'Domain F: Banking & Financial System',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-24'],
    primaryDefects: ['Needs updated Priority Sector Lending Certificates (PSLC) market trading mechanism'],
    authoritativeSources: ['RBI Master Directions — Priority Sector Lending (PSL) Targets and Classification', 'Nachiket Mor Committee Report (2014)', 'National Strategy for Financial Inclusion (NSFI) 2019-2024'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 15,
    sourceTitle: 'Financial Regulatory Bodies: SEBI, IRDAI, PFRDA & IFSCA',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_N_INSTITUTIONS_POLICY',
    targetDomainTitle: 'Domain N: Economic Institutions & Regulatory Architecture',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-22'],
    primaryDefects: ['Lacks FSDC sub-committee statutory coordination mechanisms'],
    authoritativeSources: ['SEBI Act, 1992', 'IRDAI Act, 1999', 'PFRDA Act, 2013', 'IFSCA Act, 2019', 'FSDC Gazette Notifications'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 16,
    sourceTitle: 'Foreign Direct Investment (FDI) & Foreign Portfolio Investment (FPI)',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_H_EXTERNAL_SECTOR',
    targetDomainTitle: 'Domain H: External Sector & International Economics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-28'],
    primaryDefects: ['Needs latest consolidated FDI Policy circular updates from DPIIT'],
    authoritativeSources: ['DPIIT Consolidated FDI Policy Circular', 'Arvind Mayaram Committee Report on Defining FDI and FPI (2014)', 'SEBI (FPI) Regulations, 2019'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 17,
    sourceTitle: 'FRBM Act 2003 & Fiscal Consolidation Ladder',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_G_FISCAL_PUBLIC_FINANCE',
    targetDomainTitle: 'Domain G: Fiscal Economics & Public Finance',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-21'],
    primaryDefects: ['Minor formatting cleanup on equation lines'],
    authoritativeSources: ['Fiscal Responsibility and Budget Management Act, 2003', 'N.K. Singh FRBM Review Committee Report (2017)', 'Union Budget Macroeconomic Framework Statements'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 18,
    sourceTitle: 'Functions of Money & Evolutionary Arc of Payment Systems',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_E_MONEY_MONETARY',
    targetDomainTitle: 'Domain E: Money & Monetary Economics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-07'],
    primaryDefects: ['Needs updated Central Bank Digital Currency (CBDC / e-Rupee) pilot architectures'],
    authoritativeSources: ['RBI Concept Note on Central Bank Digital Currency (2022)', 'Payment and Settlement Systems Act, 2007', 'NPCI Technical Architecture Documentation'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 19,
    sourceTitle: 'GDP, NDP, GNP & NNP Aggregate Ladder',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_C_MACROECONOMICS',
    targetDomainTitle: 'Domain C: National Income & Macroeconomics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-04'],
    primaryDefects: ['Empty code block', 'Delimiters on variable symbols'],
    authoritativeSources: ['MoSPI National Accounts Statistics (NAS) Methodology', 'UN System of National Accounts (SNA 2008)', 'NCERT Macroeconomics Class XII'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 20,
    sourceTitle: 'Human Capital Formation: Education, Skill India & Health Index',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetDomain: 'DOMAIN_I_DEVELOPMENT',
    targetDomainTitle: 'Domain I: Development Economics, Poverty & Sustainability',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-40'],
    primaryDefects: ['Needs updated National Education Policy (NEP 2020) target metrics and NITI Aayog Health Index'],
    authoritativeSources: ['National Education Policy 2020', 'NITI Aayog State Health Index', 'Economic Survey — Social Infrastructure Chapter'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 21,
    sourceTitle: 'Inclusive Growth, Financial Inclusion & JAM Trinity',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetDomain: 'DOMAIN_I_DEVELOPMENT',
    targetDomainTitle: 'Domain I: Development Economics, Poverty & Sustainability',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-25'],
    primaryDefects: ['Repetitive summary text'],
    authoritativeSources: ['Direct Benefit Transfer (DBT) Mission', 'PMJDY Official Portal Statistics', 'RBI Financial Inclusion Index (FI-Index)'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 22,
    sourceTitle: 'Industrial Policies in India: 1948, 1956 Mahalanobis to 1991',
    category: 'Book III: Indian Economic Structure & Sectors',
    targetDomain: 'DOMAIN_J_INDIAN_ECONOMY',
    targetDomainTitle: 'Domain J: Indian Economic Development & Structural Reforms',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-33'],
    primaryDefects: ['Needs integration with contemporary Production-Linked Incentive (PLI) schemes'],
    authoritativeSources: ['Industrial Policy Resolutions (1948, 1956, 1977, 1980)', 'Statement on Industrial Policy, July 24, 1991', 'DPIIT PLI Guidelines'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 23,
    sourceTitle: 'Inflation Mechanics, Types & The Phillips Curve',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_D_INFLATION',
    targetDomainTitle: 'Domain D: Inflation, Price Theory & Employment',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-15'],
    primaryDefects: ['Empty code block', 'LaTeX delimiter density'],
    authoritativeSources: ['A.W. Phillips (1958) Economica', 'Milton Friedman (1968) The Role of Monetary Policy', 'RBI Report on Currency and Finance'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 24,
    sourceTitle: 'International Economic Institutions: IMF, World Bank, WTO & BRICS',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_H_EXTERNAL_SECTOR',
    targetDomainTitle: 'Domain H: External Sector & International Economics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-29'],
    primaryDefects: ['Needs updated IMF 16th General Review of Quotas decisions'],
    authoritativeSources: ['Articles of Agreement of the IMF & IBRD', 'WTO Legal Instruments (AoA, TRIPS, GATS)', 'New Development Bank (NDB) Agreement'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 25,
    sourceTitle: 'Land Reforms & Green Revolution in India',
    category: 'Book III: Indian Economic Structure & Sectors',
    targetDomain: 'DOMAIN_K_AGRICULTURE_RURAL',
    targetDomainTitle: 'Domain K: Agriculture, Food Security & Rural Economy',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-31'],
    primaryDefects: ['Needs modern DILRMP and SVAMITVA scheme linkages'],
    authoritativeSources: ['P.C. Joshi (1975) Land Reforms in India', 'M.S. Swaminathan (2013) From Green to Evergreen Revolution', 'Ministry of Panchayati Raj Guidelines for SVAMITVA'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 26,
    sourceTitle: 'Methods of Calculating National Income & Sectoral Scrutiny',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_C_MACROECONOMICS',
    targetDomainTitle: 'Domain C: National Income & Macroeconomics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-05'],
    primaryDefects: ['Minor LaTeX sub/superscript formatting'],
    authoritativeSources: ['MoSPI / NSO National Accounts Statistics: Sources and Methods', 'UN System of National Accounts (SNA 2008)', 'Simon Kuznets (1941) National Income'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 27,
    sourceTitle: 'Monetary Policy Instruments: Quantitative vs. Qualitative Tools',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_E_MONEY_MONETARY',
    targetDomainTitle: 'Domain E: Money & Monetary Economics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-14'],
    primaryDefects: ['Needs updated SDF introduction in April 2022'],
    authoritativeSources: ['RBI Monetary Policy Operating Framework Guidelines', 'RBI MPC Bi-Monthly Resolutions', 'RBI Monetary Policy Report (MPR)'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 28,
    sourceTitle: 'Money Market vs. Capital Market Architecture',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_F_BANKING_FINANCIAL',
    targetDomainTitle: 'Domain F: Banking & Financial System',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-10'],
    primaryDefects: ['Formatting on dollar delimiters for acronyms'],
    authoritativeSources: ['RBI Master Direction — Money Market Instruments', 'Clearing Corporation of India Limited (CCIL) Operations Review', 'SEBI Capital Market Handbook'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 29,
    sourceTitle: 'Money Supply Aggregates (M0, M1, M2, M3, M4)',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_E_MONEY_MONETARY',
    targetDomainTitle: 'Domain E: Money & Monetary Economics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-08'],
    primaryDefects: ['High-density dollar math formatting'],
    authoritativeSources: ['Report of the Working Group on Money Supply (Y.V. Reddy Committee, 1998)', 'RBI Handbook of Statistics on Indian Economy'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 30,
    sourceTitle: 'MSME Sector Architecture & 2020 Composite Criteria',
    category: 'Book III: Indian Economic Structure & Sectors',
    targetDomain: 'DOMAIN_L_INDUSTRY_INFRASTRUCTURE',
    targetDomainTitle: 'Domain L: Industry, Infrastructure & Services',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-34'],
    primaryDefects: ['Needs integration with Champion Portal and RAMP scheme'],
    authoritativeSources: ['MSMED Act, 2006', 'Ministry of MSME Gazette Notification S.O. 2119(E) (June 2020)', 'Ministry of MSME Annual Report'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 31,
    sourceTitle: 'Non-Performing Assets (NPAs) & Insolvency Resolution',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_F_BANKING_FINANCIAL',
    targetDomainTitle: 'Domain F: Banking & Financial System',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-24'],
    primaryDefects: ['Needs updated IBBI resolution statistics and Pre-packaged Insolvency (PPIRP)'],
    authoritativeSources: ['Insolvency and Bankruptcy Code, 2016', 'SARFAESI Act, 2002', 'RBI Prudential Framework for Resolution of Stressed Assets (2019 Circular)'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 32,
    sourceTitle: 'Poverty Measurement in India: Historical & Post-Independent Committees',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetDomain: 'DOMAIN_I_DEVELOPMENT',
    targetDomainTitle: 'Domain I: Development Economics, Poverty & Sustainability',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-41'],
    primaryDefects: ['Repetitive boilerplate text'],
    authoritativeSources: ['Dadabhai Naoroji (1901) Poverty and Un-British Rule in India', 'V.M. Dandekar & N. Rath (1971) Poverty in India', 'Y.K. Alagh (1979)', 'D.T. Lakdawala (1993)'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 33,
    sourceTitle: 'Public Sector Enterprises & Disinvestment Architecture',
    category: 'Book III: Indian Economic Structure & Sectors',
    targetDomain: 'DOMAIN_J_INDIAN_ECONOMY',
    targetDomainTitle: 'Domain J: Indian Economic Development & Structural Reforms',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-35'],
    primaryDefects: ['Needs updated New PSE Policy 2021 (Strategic vs Non-strategic)'],
    authoritativeSources: ['DPE Guidelines on Maharatna/Navratna/Miniratna', 'DIPAM Strategic Disinvestment Guidelines', 'Union Budget Disinvestment Annexures'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 34,
    sourceTitle: 'RAS Economy Ch 1: Economic Review of Rajasthan & State Flagship Schemes',
    category: 'Book III: Indian Economic Structure & Sectors',
    targetDomain: 'DOMAIN_O_RAJASTHAN_ECONOMY',
    targetDomainTitle: 'Domain O: Rajasthan Economy (RPSC RAS Dedicated Core)',
    salvageVerdict: 'REWRITE',
    targetConceptIds: ['CON-ECO-47', 'CON-ECO-48', 'CON-ECO-49'],
    primaryDefects: ['MASSIVE DEFECT: Whole Rajasthan economy dumped into 1 note; contains stale data, lacks micro-irrigation, animal husbandry, mineral economy, desert development programs'],
    authoritativeSources: ['Economic Review of Rajasthan (Directorate of Economics and Statistics, GoR)', 'Rajasthan State Budget Documents', 'Reports of 5th & 6th State Finance Commissions of Rajasthan'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 35,
    sourceTitle: 'RBI Grade B (ESI) Volume 4: Economic & Social Issues Descriptive Vault',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetDomain: 'DOMAIN_M_LABOUR_SOCIAL',
    targetDomainTitle: 'Domain M: Labour Economics, Employment & Social Security',
    salvageVerdict: 'REWRITE',
    targetConceptIds: ['CON-ECO-43'],
    primaryDefects: ['Unstructured exam dump without atomic conceptual definitions or statutory grounding'],
    authoritativeSources: ['Ministry of Labour and Employment Annual Report', 'Periodic Labour Force Survey (PLFS) Reports (NSO)', 'V.V. Giri National Labour Institute Studies'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 36,
    sourceTitle: 'Real vs Nominal GDP, GDP Deflator & Green GDP',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_C_MACROECONOMICS',
    targetDomainTitle: 'Domain C: National Income & Macroeconomics',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-06'],
    primaryDefects: ['Minor math formatting cleanup'],
    authoritativeSources: ['MoSPI / NSO National Accounts Statistics: Base Year Revision Methodology', 'System of Environmental-Economic Accounting (SEEA 2012, UN)', 'Partha Dasgupta (2021) Dasgupta Review on Economics of Biodiversity'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 37,
    sourceTitle: "Services Sector & India's Digital Public Infrastructure (DPI)",
    category: 'Book III: Indian Economic Structure & Sectors',
    targetDomain: 'DOMAIN_L_INDUSTRY_INFRASTRUCTURE',
    targetDomainTitle: 'Domain L: Industry, Infrastructure & Services',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-36'],
    primaryDefects: ['Needs integration with ONDC and Account Aggregator ecosystem'],
    authoritativeSources: ['MeitY DPI Architecture Papers', 'RBI ReBIT Reports', 'NASSCOM Strategic Review on Indian Tech Sector'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 38,
    sourceTitle: 'Specialized Financial Institutions & DFI Architecture',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_N_INSTITUTIONS_POLICY',
    targetDomainTitle: 'Domain N: Economic Institutions & Regulatory Architecture',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-17'],
    primaryDefects: ['Needs NaBFID Act 2021 operational details'],
    authoritativeSources: ['NaBFID Act, 2021', 'NABARD Act, 1981', 'SIDBI Act, 1989', 'EXIM Bank Act, 1981', 'NHB Act, 1987'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 39,
    sourceTitle: 'Sustainable Development, Climate Economics & Carbon Markets',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetDomain: 'DOMAIN_I_DEVELOPMENT',
    targetDomainTitle: 'Domain I: Development Economics, Poverty & Sustainability',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-42'],
    primaryDefects: ['Needs updated Energy Conservation (Amendment) Act 2022 and CCTS scheme'],
    authoritativeSources: ['Energy Conservation (Amendment) Act, 2022', 'Ministry of Finance Framework for Sovereign Green Bonds (2022)', 'UNFCCC Paris Agreement (Article 6)', 'IPCC AR6'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 40,
    sourceTitle: 'Taxation Architecture: Direct vs. Indirect Taxes & GST',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_G_FISCAL_PUBLIC_FINANCE',
    targetDomainTitle: 'Domain G: Fiscal Economics & Public Finance',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-20'],
    primaryDefects: ['Needs GST compensation cess transition rules post-June 2022'],
    authoritativeSources: ['Constitution (101st Amendment) Act, 2016', 'CGST Act, 2017', 'GST Council Meeting Registers', 'Direct Taxes Code Task Force Report (2019)'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 41,
    sourceTitle: 'Tendulkar vs. Rangarajan Committees & NITI Aayog National MPI',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetDomain: 'DOMAIN_I_DEVELOPMENT',
    targetDomainTitle: 'Domain I: Development Economics, Poverty & Sustainability',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-41'],
    primaryDefects: ['Formatting on dollar delimiters for poverty line rupees'],
    authoritativeSources: ['Tendulkar Committee Report (Planning Commission 2009)', 'Rangarajan Committee Report (Planning Commission 2014)', 'NITI Aayog National MPI Progress Review 2023'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 42,
    sourceTitle: 'The 3 Central Problems & Goods Classification Matrix',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_A_FOUNDATIONS',
    targetDomainTitle: 'Domain A: Economic Foundations',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-02'],
    primaryDefects: ['Delimiters on goods classification matrix'],
    authoritativeSources: ['Paul Samuelson & William Nordhaus — Economics', 'Elinor Ostrom (1990) Governing the Commons', 'Hal Varian — Intermediate Microeconomics'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 43,
    sourceTitle: 'The Informal Economy, Gig Economy & PLFS Data Trends',
    category: 'Book III: Indian Economic Structure & Sectors',
    targetDomain: 'DOMAIN_M_LABOUR_SOCIAL',
    targetDomainTitle: 'Domain M: Labour Economics, Employment & Social Security',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-45'],
    primaryDefects: ['Needs integration with Code on Social Security 2020 Gig Worker Board statutory provisions'],
    authoritativeSources: ['NCEUS / Arjun Sengupta Report (2007)', 'Code on Social Security, 2020 (Sections 112–114)', 'NITI Aayog Gig Economy Report (2022)'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 44,
    sourceTitle: 'Types & Measurement of Unemployment (PLFS / NSO Framework)',
    category: 'Book III: Indian Economic Structure & Sectors',
    targetDomain: 'DOMAIN_M_LABOUR_SOCIAL',
    targetDomainTitle: 'Domain M: Labour Economics, Employment & Social Security',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-46'],
    primaryDefects: ['Needs latest annual PLFS labor force metrics (LFPR, WPR, UR)'],
    authoritativeSources: ['NSO / MoSPI Annual Report: Periodic Labour Force Survey (PLFS)', 'ILO 19th ICLS Standards on Labour Statistics', 'Economic Survey — Employment Chapter'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 45,
    sourceTitle: 'Union Budget Architecture & Fiscal Deficit Equations',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_G_FISCAL_PUBLIC_FINANCE',
    targetDomainTitle: 'Domain G: Fiscal Economics & Public Finance',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-18', 'CON-ECO-19'],
    primaryDefects: ['Minor math formatting cleanup'],
    authoritativeSources: ['Constitution of India (Articles 112–117)', 'Key to Budget Documents (Ministry of Finance)', 'Richard Musgrave & Peggy Musgrave — Public Finance in Theory and Practice'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 46,
    sourceTitle: 'What is Economics? Scarcity, Choice & Opportunity Cost',
    category: 'Book I: Foundations of Economics & National Income',
    targetDomain: 'DOMAIN_A_FOUNDATIONS',
    targetDomainTitle: 'Domain A: Economic Foundations',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-01'],
    primaryDefects: ['Delimiters on economics acronyms'],
    authoritativeSources: ['Lionel Robbins (1932) Nature and Significance of Economic Science', 'Adam Smith (1776) Wealth of Nations', 'Alfred Marshall (1890) Principles of Economics'],
    verifiedYear: 2026,
  },
  {
    noteNumber: 47,
    sourceTitle: 'What is Poverty? Dimensions, SDG Linkage & Poverty Gap',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetDomain: 'DOMAIN_I_DEVELOPMENT',
    targetDomainTitle: 'Domain I: Development Economics, Poverty & Sustainability',
    salvageVerdict: 'KEEP_EDIT',
    targetConceptIds: ['CON-ECO-37'],
    primaryDefects: ['Minor formatting on FGT formula line'],
    authoritativeSources: ['Foster, Greer, and Thorbecke (1984) Econometrica', 'World Bank World Development Report', 'UN Sustainable Development Goal 1 Indicators'],
    verifiedYear: 2026,
  },
];
