/**
 * Phase E: Indian Economy & Macroeconomics Semantic Inventory
 * Mind of Aravalli — Academic Reading Hub
 *
 * Maps all 47 Master Units from `03_Indian_Economy_Macro_Master.md`
 * into 49 Canonical Concepts across 11 Canonical Topics.
 */

export interface EconomicsSemanticUnit {
  semanticUnitId: string;
  sourceNoteNumber: number;
  sourceTitle: string;
  category: string;
  targetTopicOrder: number;
  targetTopicSlug: string;
  targetConceptId: string;
  targetConceptSlug: string;
  verifiedYear: number;
  temporalStatus: 'CORE_FOUNDATION' | 'STATUTORY_RULE' | 'CURRENT_FRAMEWORK' | 'HISTORICAL_EVOLUTION';
}

export const ECONOMICS_SEMANTIC_INVENTORY: EconomicsSemanticUnit[] = [
  // =========================================================================
  // TOPIC E1: Foundations of Economics & National Income Accounting
  // =========================================================================
  {
    semanticUnitId: 'SEM-ECO-01',
    sourceNoteNumber: 46,
    sourceTitle: 'What is Economics? Scarcity, Choice & Opportunity Cost',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 27,
    targetTopicSlug: 'foundations-of-economics-and-national-income',
    targetConceptId: 'CON-ECO-01',
    targetConceptSlug: 'scarcity-choice-opportunity-cost-ppf-central-economic-problems',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-02',
    sourceNoteNumber: 42,
    sourceTitle: 'The 3 Central Problems & Goods Classification Matrix',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 27,
    targetTopicSlug: 'foundations-of-economics-and-national-income',
    targetConceptId: 'CON-ECO-02',
    targetConceptSlug: 'classification-of-goods-public-private-common-resources-club-goods',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-03',
    sourceNoteNumber: 8,
    sourceTitle: 'Circular Flow of Income, Factor Payments & Leakages',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 27,
    targetTopicSlug: 'foundations-of-economics-and-national-income',
    targetConceptId: 'CON-ECO-03',
    targetConceptSlug: 'circular-flow-of-income-factor-payments-injections-and-leakages',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-04',
    sourceNoteNumber: 19,
    sourceTitle: 'GDP, NDP, GNP & NNP Aggregate Ladder',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 27,
    targetTopicSlug: 'foundations-of-economics-and-national-income',
    targetConceptId: 'CON-ECO-04',
    targetConceptSlug: 'national-income-aggregates-gdp-ndp-gnp-nnp-factor-cost-basic-prices-market-prices',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-05',
    sourceNoteNumber: 26,
    sourceTitle: 'Methods of Calculating National Income & Sectoral Scrutiny',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 27,
    targetTopicSlug: 'foundations-of-economics-and-national-income',
    targetConceptId: 'CON-ECO-05',
    targetConceptSlug: 'methods-of-national-income-calculation-production-income-expenditure-approaches',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-06',
    sourceNoteNumber: 36,
    sourceTitle: 'Real vs Nominal GDP, GDP Deflator & Green GDP',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 27,
    targetTopicSlug: 'foundations-of-economics-and-national-income',
    targetConceptId: 'CON-ECO-06',
    targetConceptSlug: 'real-vs-nominal-gdp-gdp-deflator-base-year-revisions-green-gdp',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },

  // =========================================================================
  // TOPIC E2: Money, Commercial Banking & Financial Markets Architecture
  // =========================================================================
  {
    semanticUnitId: 'SEM-ECO-07',
    sourceNoteNumber: 18,
    sourceTitle: 'Functions of Money & Evolutionary Arc of Payment Systems',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 28,
    targetTopicSlug: 'money-commercial-banking-and-financial-markets',
    targetConceptId: 'CON-ECO-07',
    targetConceptSlug: 'evolution-of-money-functions-legal-tender-fiat-money-digital-payments-cbdc',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-08',
    sourceNoteNumber: 29,
    sourceTitle: 'Money Supply Aggregates (M0, M1, M2, M3, M4)',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 28,
    targetTopicSlug: 'money-commercial-banking-and-financial-markets',
    targetConceptId: 'CON-ECO-08',
    targetConceptSlug: 'money-supply-aggregates-m0-m1-m2-m3-m4-liquidity-aggregates-money-multiplier',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-09',
    sourceNoteNumber: 9,
    sourceTitle: 'Commercial Banking & Money Creation',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 28,
    targetTopicSlug: 'money-commercial-banking-and-financial-markets',
    targetConceptId: 'CON-ECO-09',
    targetConceptSlug: 'commercial-banking-architecture-fractional-reserve-banking-credit-creation-mechanics',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-10',
    sourceNoteNumber: 28,
    sourceTitle: 'Money Market vs. Capital Market Architecture',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 28,
    targetTopicSlug: 'money-commercial-banking-and-financial-markets',
    targetConceptId: 'CON-ECO-10',
    targetConceptSlug: 'financial-markets-architecture-money-market-instruments-vs-capital-markets',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-11',
    sourceNoteNumber: 6,
    sourceTitle: 'Capital Market Instruments: Equities, Bonds & Derivatives',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 28,
    targetTopicSlug: 'money-commercial-banking-and-financial-markets',
    targetConceptId: 'CON-ECO-11',
    targetConceptSlug: 'capital-market-instruments-equities-corporate-bonds-yield-curves-derivatives',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },

  // =========================================================================
  // TOPIC E3: Central Banking, Monetary Policy Framework & Price Theory
  // =========================================================================
  {
    semanticUnitId: 'SEM-ECO-12',
    sourceNoteNumber: 7,
    sourceTitle: 'Central Banking & RBI Functions',
    category: 'Book IV: Monetary Economics, Inflation & RBI Framework',
    targetTopicOrder: 29,
    targetTopicSlug: 'central-banking-monetary-policy-and-price-theory',
    targetConceptId: 'CON-ECO-12',
    targetConceptSlug: 'central-banking-rbi-statutory-functions-reserve-management-lender-of-last-resort',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-ECO-13',
    sourceNoteNumber: 7,
    sourceTitle: 'Monetary Policy Framework & MPC',
    category: 'Book IV: Monetary Economics, Inflation & RBI Framework',
    targetTopicOrder: 29,
    targetTopicSlug: 'central-banking-monetary-policy-and-price-theory',
    targetConceptId: 'CON-ECO-13',
    targetConceptSlug: 'monetary-policy-framework-flexible-inflation-targeting-mpc-transmission-channels',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-ECO-14',
    sourceNoteNumber: 27,
    sourceTitle: 'Monetary Policy Instruments: Quantitative vs. Qualitative Tools',
    category: 'Book IV: Monetary Economics, Inflation & RBI Framework',
    targetTopicOrder: 29,
    targetTopicSlug: 'central-banking-monetary-policy-and-price-theory',
    targetConceptId: 'CON-ECO-14',
    targetConceptSlug: 'quantitative-qualitative-monetary-instruments-repo-sdf-msf-crr-slr-omo-market-stabilization',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-ECO-15',
    sourceNoteNumber: 23,
    sourceTitle: 'Inflation Mechanics, Types & The Phillips Curve',
    category: 'Book IV: Monetary Economics, Inflation & RBI Framework',
    targetTopicOrder: 29,
    targetTopicSlug: 'central-banking-monetary-policy-and-price-theory',
    targetConceptId: 'CON-ECO-15',
    targetConceptSlug: 'price-theory-inflation-mechanics-demand-pull-cost-push-stagflation-phillips-curve',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-16',
    sourceNoteNumber: 10,
    sourceTitle: 'CPI vs. WPI Inflation Indices & Food Inflation Dynamics',
    category: 'Book IV: Monetary Economics, Inflation & RBI Framework',
    targetTopicOrder: 29,
    targetTopicSlug: 'central-banking-monetary-policy-and-price-theory',
    targetConceptId: 'CON-ECO-16',
    targetConceptSlug: 'measurement-of-inflation-cpi-vs-wpi-basket-weightages-core-headline-food-inflation',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },
  {
    semanticUnitId: 'SEM-ECO-17',
    sourceNoteNumber: 38,
    sourceTitle: 'Specialized Financial Institutions & DFI Architecture',
    category: 'Book IV: Monetary Economics, Inflation & RBI Framework',
    targetTopicOrder: 29,
    targetTopicSlug: 'central-banking-monetary-policy-and-price-theory',
    targetConceptId: 'CON-ECO-17',
    targetConceptSlug: 'specialized-development-financial-institutions-nabard-sidbi-nhb-exim-nabfid',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },

  // =========================================================================
  // TOPIC E4: Public Finance, Union Budget Architecture & Taxation
  // =========================================================================
  {
    semanticUnitId: 'SEM-ECO-18',
    sourceNoteNumber: 45,
    sourceTitle: 'Union Budget Architecture & Constitutional Stages',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 30,
    targetTopicSlug: 'public-finance-union-budget-and-taxation',
    targetConceptId: 'CON-ECO-18',
    targetConceptSlug: 'union-budget-architecture-revenue-vs-capital-receipts-expenditure-constitutional-stages',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-ECO-19',
    sourceNoteNumber: 45,
    sourceTitle: 'Fiscal Deficit Equations & Debt Dynamics',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 30,
    targetTopicSlug: 'public-finance-union-budget-and-taxation',
    targetConceptId: 'CON-ECO-19',
    targetConceptSlug: 'fiscal-deficit-equations-budgetary-revenue-effective-revenue-fiscal-primary-deficits',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-20',
    sourceNoteNumber: 40,
    sourceTitle: 'Taxation Architecture: Direct vs. Indirect Taxes & GST',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 30,
    targetTopicSlug: 'public-finance-union-budget-and-taxation',
    targetConceptId: 'CON-ECO-20',
    targetConceptSlug: 'taxation-architecture-in-india-direct-vs-indirect-taxes-tax-buoyancy-gst-ecosystem',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-ECO-21',
    sourceNoteNumber: 17,
    sourceTitle: 'FRBM Act 2003 & Fiscal Consolidation Ladder',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 30,
    targetTopicSlug: 'public-finance-union-budget-and-taxation',
    targetConceptId: 'CON-ECO-21',
    targetConceptSlug: 'frbm-act-2003-fiscal-consolidation-roadmap-nk-singh-committee-escape-clauses',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },

  // =========================================================================
  // TOPIC E5: Banking Regulations, Basel Norms, NPAs & Financial Inclusion
  // =========================================================================
  {
    semanticUnitId: 'SEM-ECO-22',
    sourceNoteNumber: 15,
    sourceTitle: 'Financial Regulatory Bodies: SEBI, IRDAI, PFRDA & IFSCA',
    category: 'Book V: Inclusive Growth, Financial Inclusion & Welfare Schemes',
    targetTopicOrder: 31,
    targetTopicSlug: 'banking-regulations-basel-norms-and-financial-inclusion',
    targetConceptId: 'CON-ECO-22',
    targetConceptSlug: 'financial-regulatory-architecture-sebi-irdai-pfrda-ifsca-fsdc-inter-regulatory-coordination',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-ECO-23',
    sourceNoteNumber: 5,
    sourceTitle: 'Basel Accords & Risk-Weighted Asset Framework',
    category: 'Book IV: Monetary Economics, Inflation & RBI Framework',
    targetTopicOrder: 31,
    targetTopicSlug: 'banking-regulations-basel-norms-and-financial-inclusion',
    targetConceptId: 'CON-ECO-23',
    targetConceptSlug: 'prudential-regulations-basel-accords-basel-i-ii-iii-rwa-crar-capital-buffers',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },
  {
    semanticUnitId: 'SEM-ECO-24',
    sourceNoteNumber: 31,
    sourceTitle: 'Non-Performing Assets (NPAs) & Insolvency Resolution',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 31,
    targetTopicSlug: 'banking-regulations-basel-norms-and-financial-inclusion',
    targetConceptId: 'CON-ECO-24',
    targetConceptSlug: 'non-performing-assets-sma-classification-provisioning-norms-sarfaesi-ibc-2016-resolution',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-ECO-25',
    sourceNoteNumber: 14,
    sourceTitle: 'Financial Inclusion Initiatives & Priority Sector Lending Targets',
    category: 'Book V: Inclusive Growth, Financial Inclusion & Welfare Schemes',
    targetTopicOrder: 31,
    targetTopicSlug: 'banking-regulations-basel-norms-and-financial-inclusion',
    targetConceptId: 'CON-ECO-25',
    targetConceptSlug: 'financial-inclusion-framework-priority-sector-lending-psl-sub-targets-pslc-lead-bank-pmjdy',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },

  // =========================================================================
  // TOPIC E6: External Sector, Balance of Payments & International Trade
  // =========================================================================
  {
    semanticUnitId: 'SEM-ECO-26',
    sourceNoteNumber: 4,
    sourceTitle: 'Balance of Payments (BoP) & Foreign Exchange Reserves',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetTopicOrder: 32,
    targetTopicSlug: 'external-sector-balance-of-payments-and-trade',
    targetConceptId: 'CON-ECO-26',
    targetConceptSlug: 'balance-of-payments-framework-current-account-capital-account-cad-forex-reserves',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-27',
    sourceNoteNumber: 12,
    sourceTitle: 'Exchange Rate Regimes & Rupee Convertibility',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 32,
    targetTopicSlug: 'external-sector-balance-of-payments-and-trade',
    targetConceptId: 'CON-ECO-27',
    targetConceptSlug: 'exchange-rate-regimes-lerms-neer-reer-rupee-convertibility-tarapore-committee-roadmaps',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },
  {
    semanticUnitId: 'SEM-ECO-28',
    sourceNoteNumber: 16,
    sourceTitle: 'Foreign Direct Investment (FDI) & Foreign Portfolio Investment (FPI)',
    category: 'Book V: Inclusive Growth, Financial Inclusion & Welfare Schemes',
    targetTopicOrder: 32,
    targetTopicSlug: 'external-sector-balance-of-payments-and-trade',
    targetConceptId: 'CON-ECO-28',
    targetConceptSlug: 'foreign-capital-flows-fdi-automatic-vs-government-routes-fpi-regulations-external-commercial-borrowings',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-ECO-29',
    sourceNoteNumber: 24,
    sourceTitle: 'International Economic Institutions: IMF, World Bank, WTO & BRICS Bank',
    category: 'Book V: Inclusive Growth, Financial Inclusion & Welfare Schemes',
    targetTopicOrder: 32,
    targetTopicSlug: 'external-sector-balance-of-payments-and-trade',
    targetConceptId: 'CON-ECO-29',
    targetConceptSlug: 'international-economic-institutions-imf-sdr-world-bank-group-wto-agreements-ndb-aiib',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },

  // =========================================================================
  // TOPIC E7: Agriculture, Land Reforms & Food Security
  // =========================================================================
  {
    semanticUnitId: 'SEM-ECO-30',
    sourceNoteNumber: 25,
    sourceTitle: 'Land Reforms & Green Revolution in India',
    category: 'Book V: Agriculture, Rural Economy & Land Reforms',
    targetTopicOrder: 33,
    targetTopicSlug: 'agriculture-land-reforms-and-food-security',
    targetConceptId: 'CON-ECO-30',
    targetConceptSlug: 'indian-agriculture-structural-evolution-green-revolution-cropping-patterns-irrigation',
    verifiedYear: 2026,
    temporalStatus: 'HISTORICAL_EVOLUTION',
  },
  {
    semanticUnitId: 'SEM-ECO-31',
    sourceNoteNumber: 25,
    sourceTitle: 'Land Reforms in Post-Independence India',
    category: 'Book V: Agriculture, Rural Economy & Land Reforms',
    targetTopicOrder: 33,
    targetTopicSlug: 'agriculture-land-reforms-and-food-security',
    targetConceptId: 'CON-ECO-31',
    targetConceptSlug: 'land-reforms-in-india-zamindari-abolition-tenancy-reforms-land-ceilings-bhoodan-digitization',
    verifiedYear: 2026,
    temporalStatus: 'HISTORICAL_EVOLUTION',
  },
  {
    semanticUnitId: 'SEM-ECO-32',
    sourceNoteNumber: 2,
    sourceTitle: 'Agriculture Sector & MSP Architecture',
    category: 'Book V: Agriculture, Rural Economy & Land Reforms',
    targetTopicOrder: 33,
    targetTopicSlug: 'agriculture-land-reforms-and-food-security',
    targetConceptId: 'CON-ECO-32',
    targetConceptSlug: 'agricultural-pricing-architecture-msp-cacp-cost-concepts-a2-fl-c2-e-nam-pm-aasha',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },

  // =========================================================================
  // TOPIC E8: Industrial Policy, MSMEs, Disinvestment & Digital Infrastructure
  // =========================================================================
  {
    semanticUnitId: 'SEM-ECO-33',
    sourceNoteNumber: 22,
    sourceTitle: 'Industrial Policies in India: 1948, 1956 Mahalanobis to 1991',
    category: 'Book IV: Industry, Industrial Policy & Manufacturing',
    targetTopicOrder: 34,
    targetTopicSlug: 'industrial-policy-msmes-and-digital-infrastructure',
    targetConceptId: 'CON-ECO-33',
    targetConceptSlug: 'industrial-policy-evolution-ipr-1948-1956-mahalanobis-strategy-1991-lpg-reforms-pli-schemes',
    verifiedYear: 2026,
    temporalStatus: 'HISTORICAL_EVOLUTION',
  },
  {
    semanticUnitId: 'SEM-ECO-34',
    sourceNoteNumber: 30,
    sourceTitle: 'MSME Sector Architecture & 2020 Composite Criteria',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 34,
    targetTopicSlug: 'industrial-policy-msmes-and-digital-infrastructure',
    targetConceptId: 'CON-ECO-34',
    targetConceptSlug: 'msme-sector-framework-revised-2020-composite-criteria-udyam-portal-cgtmse-credit-schemes',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-ECO-35',
    sourceNoteNumber: 33,
    sourceTitle: 'Public Sector Enterprises & Disinvestment Architecture',
    category: 'Book IV: Industry, Industrial Policy & Manufacturing',
    targetTopicOrder: 34,
    targetTopicSlug: 'industrial-policy-msmes-and-digital-infrastructure',
    targetConceptId: 'CON-ECO-35',
    targetConceptSlug: 'central-public-sector-enterprises-maharatna-navratna-strategic-disinvestment-dipam-policy',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },
  {
    semanticUnitId: 'SEM-ECO-36',
    sourceNoteNumber: 37,
    sourceTitle: 'Services Sector & India\'s Digital Public Infrastructure (DPI)',
    category: 'Book IV: Industry, Industrial Policy & Manufacturing',
    targetTopicOrder: 34,
    targetTopicSlug: 'industrial-policy-msmes-and-digital-infrastructure',
    targetConceptId: 'CON-ECO-36',
    targetConceptSlug: 'services-sector-and-indias-digital-public-infrastructure-dpi-india-stack-account-aggregator-ondc',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },

  // =========================================================================
  // TOPIC E9: Poverty, Inequality, Human Capital & Sustainable Development
  // =========================================================================
  {
    semanticUnitId: 'SEM-ECO-37',
    sourceNoteNumber: 47,
    sourceTitle: 'What is Poverty? Dimensions, SDG Linkage & Poverty Gap',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetTopicOrder: 35,
    targetTopicSlug: 'poverty-inequality-human-capital-and-sustainability',
    targetConceptId: 'CON-ECO-37',
    targetConceptSlug: 'concepts-of-poverty-absolute-vs-relative-headcount-ratio-poverty-gap-squared-poverty-gap',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-38',
    sourceNoteNumber: 1,
    sourceTitle: 'Absolute vs Relative Poverty & Lorenz Curve / Gini Index',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetTopicOrder: 35,
    targetTopicSlug: 'poverty-inequality-human-capital-and-sustainability',
    targetConceptId: 'CON-ECO-38',
    targetConceptSlug: 'measuring-economic-inequality-lorenz-curve-gini-coefficient-palma-ratio-consumption-vs-wealth-gini',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-39',
    sourceNoteNumber: 32,
    sourceTitle: 'Poverty Measurement in India: Historical & Post-Independent Committees',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetTopicOrder: 35,
    targetTopicSlug: 'poverty-inequality-human-capital-and-sustainability',
    targetConceptId: 'CON-ECO-39',
    targetConceptSlug: 'evolution-of-poverty-estimation-in-india-dadabhai-naoroji-alagh-lakdawala-tendulkar-rangarajan',
    verifiedYear: 2026,
    temporalStatus: 'HISTORICAL_EVOLUTION',
  },
  {
    semanticUnitId: 'SEM-ECO-40',
    sourceNoteNumber: 41,
    sourceTitle: 'Tendulkar vs. Rangarajan Committees & NITI Aayog National MPI',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetTopicOrder: 35,
    targetTopicSlug: 'poverty-inequality-human-capital-and-sustainability',
    targetConceptId: 'CON-ECO-40',
    targetConceptSlug: 'multidimensional-poverty-index-alkire-foster-method-niti-aayog-national-mpi-12-indicators',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },
  {
    semanticUnitId: 'SEM-ECO-41',
    sourceNoteNumber: 3,
    sourceTitle: 'Amartya Sen\'s Capability Approach & Entitlements',
    category: 'Book II: Poverty, Inequality & Human Capital',
    targetTopicOrder: 35,
    targetTopicSlug: 'poverty-inequality-human-capital-and-sustainability',
    targetConceptId: 'CON-ECO-41',
    targetConceptSlug: 'human-capital-formation-amartya-sen-capability-approach-education-health-skill-development',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-ECO-42',
    sourceNoteNumber: 39,
    sourceTitle: 'Sustainable Development, Climate Economics & Carbon Markets',
    category: 'Book V: Inclusive Growth, Financial Inclusion & Welfare Schemes',
    targetTopicOrder: 35,
    targetTopicSlug: 'poverty-inequality-human-capital-and-sustainability',
    targetConceptId: 'CON-ECO-42',
    targetConceptSlug: 'sustainable-development-climate-economics-environmental-kuznets-curve-carbon-credits-green-bonds',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },

  // =========================================================================
  // TOPIC E10: Employment, Labor Markets, Planning & NITI Aayog
  // =========================================================================
  {
    semanticUnitId: 'SEM-ECO-43',
    sourceNoteNumber: 44,
    sourceTitle: 'Types & Measurement of Unemployment (PLFS / NSO Framework)',
    category: 'Book III: Labor Markets, Employment & Informal Sector',
    targetTopicOrder: 36,
    targetTopicSlug: 'employment-labor-markets-and-economic-planning',
    targetConceptId: 'CON-ECO-43',
    targetConceptSlug: 'unemployment-typology-and-measurement-ups-upss-cws-lfpr-wpr-plfs-labor-market-trends',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },
  {
    semanticUnitId: 'SEM-ECO-44',
    sourceNoteNumber: 43,
    sourceTitle: 'The Informal Economy, Gig Economy & PLFS Data Trends',
    category: 'Book III: Labor Markets, Employment & Informal Sector',
    targetTopicOrder: 36,
    targetTopicSlug: 'employment-labor-markets-and-economic-planning',
    targetConceptId: 'CON-ECO-44',
    targetConceptSlug: 'informal-sector-gig-platform-workers-social-security-code-2020-e-shram-portal',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-ECO-45',
    sourceNoteNumber: 21,
    sourceTitle: 'Inclusive Growth, Financial Inclusion & JAM Trinity',
    category: 'Book V: Inclusive Growth, Financial Inclusion & Welfare Schemes',
    targetTopicOrder: 36,
    targetTopicSlug: 'employment-labor-markets-and-economic-planning',
    targetConceptId: 'CON-ECO-45',
    targetConceptSlug: 'inclusive-growth-architecture-direct-benefit-transfer-dbt-jam-trinity-welfare-governance',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },
  {
    semanticUnitId: 'SEM-ECO-46',
    sourceNoteNumber: 11,
    sourceTitle: 'Evolution of Indian Economic Planning: PC to NITI Aayog',
    category: 'Book I: Foundations of Economics & National Income',
    targetTopicOrder: 36,
    targetTopicSlug: 'employment-labor-markets-and-economic-planning',
    targetConceptId: 'CON-ECO-46',
    targetConceptSlug: 'evolution-of-economic-planning-five-year-plans-planning-commission-to-niti-aayog-federalism',
    verifiedYear: 2026,
    temporalStatus: 'HISTORICAL_EVOLUTION',
  },

  // =========================================================================
  // TOPIC E11: Rajasthan State Economy & Flagship Development Programs
  // =========================================================================
  {
    semanticUnitId: 'SEM-ECO-47',
    sourceNoteNumber: 34,
    sourceTitle: 'RAS Economy: Macroeconomic Profile of Rajasthan',
    category: 'Economy',
    targetTopicOrder: 37,
    targetTopicSlug: 'rajasthan-state-economy-and-development',
    targetConceptId: 'CON-ECO-47',
    targetConceptSlug: 'macroeconomic-profile-of-rajasthan-gsdp-gsva-sectoral-shares-per-capita-income',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },
  {
    semanticUnitId: 'SEM-ECO-48',
    sourceNoteNumber: 34,
    sourceTitle: 'RAS Economy: Key Sectors & Resource Endowment of Rajasthan',
    category: 'Economy',
    targetTopicOrder: 37,
    targetTopicSlug: 'rajasthan-state-economy-and-development',
    targetConceptId: 'CON-ECO-48',
    targetConceptSlug: 'key-economic-sectors-of-rajasthan-arid-agriculture-minerals-renewable-energy-hub-tourism',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },
  {
    semanticUnitId: 'SEM-ECO-49',
    sourceNoteNumber: 34,
    sourceTitle: 'RAS Economy: Industrial Corridor, RIPS & Flagship Schemes',
    category: 'Economy',
    targetTopicOrder: 37,
    targetTopicSlug: 'rajasthan-state-economy-and-development',
    targetConceptId: 'CON-ECO-49',
    targetConceptSlug: 'industrial-infrastructure-and-flagship-schemes-in-rajasthan-rips-riico-dmic-social-welfare',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },
];
