/**
 * IIBF & Banking Regulations Semantic Inventory
 * Mind of Aravalli — Academic Reading Hub
 *
 * Maps all 79 Master Units from `02_IIBF_Banking_Regulations_Master.md`
 * into canonical concepts across the 4 core IIBF DBF papers:
 * - Paper 1: Indian Economy & Indian Financial System (IE&IFS)
 * - Paper 2: Principles & Practices of Banking (PPB)
 * - Paper 3: Accounting & Financial Management for Bankers (AFMB)
 * - Paper 4: Retail Banking & Wealth Management (RBWM)
 * - Core Banking Regulations & RBI FM Management Vault
 */

export interface IIBFSemanticUnit {
  semanticUnitId: string;
  sourceNoteNumber: number;
  sourceTitle: string;
  paper: 'IE_IFS' | 'PPB' | 'AFMB' | 'RBWM' | 'BANKING_REGULATIONS' | 'RBI_FM';
  targetTopicOrder: number;
  targetTopicSlug: string;
  targetConceptId: string;
  targetConceptSlug: string;
  verifiedYear: number;
  temporalStatus: 'CORE_FOUNDATION' | 'STATUTORY_RULE' | 'CURRENT_FRAMEWORK' | 'HISTORICAL_EVOLUTION';
}

export const IIBF_SEMANTIC_INVENTORY: IIBFSemanticUnit[] = [
  // =========================================================================
  // PAPER 1: INDIAN ECONOMY & INDIAN FINANCIAL SYSTEM (IE&IFS)
  // =========================================================================
  {
    semanticUnitId: 'SEM-IIBF-01',
    sourceNoteNumber: 22,
    sourceTitle: 'Overview of Indian Economy, Demographic Transition & Economic Planning',
    paper: 'IE_IFS',
    targetTopicOrder: 38,
    targetTopicSlug: 'iibf-indian-financial-system-architecture',
    targetConceptId: 'CON-IIBF-01',
    targetConceptSlug: 'indian-financial-system-evolution-institutional-structure-and-phase-transitions',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-02',
    sourceNoteNumber: 37,
    sourceTitle: 'Overview of Indian Financial System & Institutional Pillars',
    paper: 'IE_IFS',
    targetTopicOrder: 38,
    targetTopicSlug: 'iibf-indian-financial-system-architecture',
    targetConceptId: 'CON-IIBF-01',
    targetConceptSlug: 'indian-financial-system-evolution-institutional-structure-and-phase-transitions',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-03',
    sourceNoteNumber: 40,
    sourceTitle: 'Regional Rural Banks (RRBs) Structure, Equity & PSL Mandates',
    paper: 'IE_IFS',
    targetTopicOrder: 38,
    targetTopicSlug: 'iibf-indian-financial-system-architecture',
    targetConceptId: 'CON-IIBF-02',
    targetConceptSlug: 'regional-rural-banks-structure-amalgamation-and-ownership-governance',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-04',
    sourceNoteNumber: 41,
    sourceTitle: 'Cooperative Banking System, BR Amendment 2020 & 4-Tier UCBs',
    paper: 'IE_IFS',
    targetTopicOrder: 38,
    targetTopicSlug: 'iibf-indian-financial-system-architecture',
    targetConceptId: 'CON-IIBF-03',
    targetConceptSlug: 'cooperative-banking-framework-br-act-amendment-2020-and-4-tier-ucb-categorization',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-05',
    sourceNoteNumber: 42,
    sourceTitle: 'NBFCs, Scale-Based Regulation (SBR) & Housing Finance Companies',
    paper: 'IE_IFS',
    targetTopicOrder: 38,
    targetTopicSlug: 'iibf-indian-financial-system-architecture',
    targetConceptId: 'CON-IIBF-04',
    targetConceptSlug: 'non-banking-financial-companies-scale-based-regulation-and-regulatory-layers',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-06',
    sourceNoteNumber: 43,
    sourceTitle: 'Development Financial Institutions (NABARD, SIDBI, EXIM, NHB & NaBFID)',
    paper: 'IE_IFS',
    targetTopicOrder: 38,
    targetTopicSlug: 'iibf-indian-financial-system-architecture',
    targetConceptId: 'CON-IIBF-05',
    targetConceptSlug: 'development-financial-institutions-nabard-sidbi-exim-nhb-and-nabfid-statutory-mandates',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-07',
    sourceNoteNumber: 46,
    sourceTitle: 'Financial Markets Structure (Money vs Capital, Primary vs Secondary)',
    paper: 'IE_IFS',
    targetTopicOrder: 39,
    targetTopicSlug: 'iibf-financial-markets-and-instruments',
    targetConceptId: 'CON-IIBF-06',
    targetConceptSlug: 'financial-markets-duality-money-market-vs-capital-market-mechanisms',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-08',
    sourceNoteNumber: 47,
    sourceTitle: 'Money Market Instruments (Call Money, T-Bills, CP, CD & TREPS)',
    paper: 'IE_IFS',
    targetTopicOrder: 39,
    targetTopicSlug: 'iibf-financial-markets-and-instruments',
    targetConceptId: 'CON-IIBF-07',
    targetConceptSlug: 'money-market-instruments-call-notice-term-money-t-bills-cp-cd-and-treps',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-09',
    sourceNoteNumber: 48,
    sourceTitle: 'Capital Markets, Stock Exchanges & Depository Architecture',
    paper: 'IE_IFS',
    targetTopicOrder: 39,
    targetTopicSlug: 'iibf-financial-markets-and-instruments',
    targetConceptId: 'CON-IIBF-08',
    targetConceptSlug: 'capital-markets-primary-issue-mechanisms-ipo-fpo-ofs-and-depository-systems-nsdl-cdsl',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-10',
    sourceNoteNumber: 49,
    sourceTitle: 'Fixed Income Securities, G-Secs, Yield Curves & Duration',
    paper: 'IE_IFS',
    targetTopicOrder: 39,
    targetTopicSlug: 'iibf-financial-markets-and-instruments',
    targetConceptId: 'CON-IIBF-09',
    targetConceptSlug: 'fixed-income-mathematics-bond-pricing-yield-to-maturity-macaulay-duration-and-convexity',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-11',
    sourceNoteNumber: 50,
    sourceTitle: 'Derivatives Market (Forwards, Futures, Options & Swaps)',
    paper: 'IE_IFS',
    targetTopicOrder: 39,
    targetTopicSlug: 'iibf-financial-markets-and-instruments',
    targetConceptId: 'CON-IIBF-10',
    targetConceptSlug: 'financial-derivatives-forwards-futures-options-payoffs-and-interest-rate-swaps',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-12',
    sourceNoteNumber: 51,
    sourceTitle: 'Mutual Funds, Alternate Investment Funds (AIF) & REITs/InvITs',
    paper: 'IE_IFS',
    targetTopicOrder: 39,
    targetTopicSlug: 'iibf-financial-markets-and-instruments',
    targetConceptId: 'CON-IIBF-11',
    targetConceptSlug: 'collective-investment-vehicles-mutual-funds-nav-aif-categories-and-reits-invits',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-13',
    sourceNoteNumber: 52,
    sourceTitle: 'Insurance Principles, IRDAI Bima Trinity & Pension Systems (NPS)',
    paper: 'IE_IFS',
    targetTopicOrder: 39,
    targetTopicSlug: 'iibf-financial-markets-and-instruments',
    targetConceptId: 'CON-IIBF-12',
    targetConceptSlug: 'insurance-and-pension-systems-principles-of-insurance-bima-trinity-and-national-pension-system',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-14',
    sourceNoteNumber: 53,
    sourceTitle: 'Factoring, Forfaiting and TReDS Architecture',
    paper: 'IE_IFS',
    targetTopicOrder: 39,
    targetTopicSlug: 'iibf-financial-markets-and-instruments',
    targetConceptId: 'CON-IIBF-13',
    targetConceptSlug: 'factoring-forfaiting-and-treds-trade-receivables-financing-mechanisms',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-15',
    sourceNoteNumber: 54,
    sourceTitle: 'Foreign Exchange Market, Quotes, FEMA 1999 & NRI Accounts',
    paper: 'IE_IFS',
    targetTopicOrder: 40,
    targetTopicSlug: 'iibf-forex-markets-and-nri-banking',
    targetConceptId: 'CON-IIBF-14',
    targetConceptSlug: 'forex-market-mechanics-direct-vs-indirect-quotes-cross-rates-and-fedaic-rules',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-16',
    sourceNoteNumber: 54,
    sourceTitle: 'Foreign Exchange Market, Quotes, FEMA 1999 & NRI Accounts',
    paper: 'IE_IFS',
    targetTopicOrder: 40,
    targetTopicSlug: 'iibf-forex-markets-and-nri-banking',
    targetConceptId: 'CON-IIBF-15',
    targetConceptSlug: 'nri-deposit-accounts-framework-nre-nro-and-fcnr-b-comparative-matrix',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-17',
    sourceNoteNumber: 55,
    sourceTitle: 'Core Banking Solutions, ESG Risk, Green Bonds & BRSR Framework',
    paper: 'IE_IFS',
    targetTopicOrder: 41,
    targetTopicSlug: 'iibf-sustainable-finance-and-banking-technology',
    targetConceptId: 'CON-IIBF-16',
    targetConceptSlug: 'sustainable-finance-climate-risk-framework-green-deposits-and-brsr-reporting',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },

  // =========================================================================
  // PAPER 2: PRINCIPLES & PRACTICES OF BANKING (PPB)
  // =========================================================================
  {
    semanticUnitId: 'SEM-IIBF-18',
    sourceNoteNumber: 56,
    sourceTitle: 'Banker-Customer Relationship, Rights & Duties',
    paper: 'PPB',
    targetTopicOrder: 42,
    targetTopicSlug: 'iibf-banker-customer-relationship-and-customer-service',
    targetConceptId: 'CON-IIBF-17',
    targetConceptSlug: 'banker-customer-relationship-statutory-nature-rights-and-legal-duties',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-19',
    sourceNoteNumber: 57,
    sourceTitle: 'AML / KYC Norms & Customer Due Diligence (CDD)',
    paper: 'PPB',
    targetTopicOrder: 42,
    targetTopicSlug: 'iibf-banker-customer-relationship-and-customer-service',
    targetConceptId: 'CON-IIBF-18',
    targetConceptSlug: 'anti-money-laundering-pmla-2002-and-rbi-kyc-master-directions',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-20',
    sourceNoteNumber: 58,
    sourceTitle: 'Operations in Accounts of Special Customers',
    paper: 'PPB',
    targetTopicOrder: 42,
    targetTopicSlug: 'iibf-banker-customer-relationship-and-customer-service',
    targetConceptId: 'CON-IIBF-19',
    targetConceptSlug: 'operations-in-accounts-of-special-customers-minors-illiterates-blind-and-insolvents',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-21',
    sourceNoteNumber: 59,
    sourceTitle: 'Operations in Accounts of Companies, Trusts, Clubs & Societies',
    paper: 'PPB',
    targetTopicOrder: 42,
    targetTopicSlug: 'iibf-banker-customer-relationship-and-customer-service',
    targetConceptId: 'CON-IIBF-20',
    targetConceptSlug: 'operations-in-accounts-of-entities-proprietorships-partnerships-companies-and-trusts',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-22',
    sourceNoteNumber: 60,
    sourceTitle: 'Mandate, Power of Attorney & Legal Orders (Garnishee vs Attachment)',
    paper: 'PPB',
    targetTopicOrder: 42,
    targetTopicSlug: 'iibf-banker-customer-relationship-and-customer-service',
    targetConceptId: 'CON-IIBF-21',
    targetConceptSlug: 'legal-orders-affecting-bank-accounts-garnishee-order-vs-income-tax-attachment-order',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-23',
    sourceNoteNumber: 61,
    sourceTitle: 'Safe Deposit Lockers, Safe Custody & Nomination Facility',
    paper: 'PPB',
    targetTopicOrder: 42,
    targetTopicSlug: 'iibf-banker-customer-relationship-and-customer-service',
    targetConceptId: 'CON-IIBF-22',
    targetConceptSlug: 'safe-deposit-lockers-safe-custody-and-statutory-nomination-framework',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-24',
    sourceNoteNumber: 62,
    sourceTitle: 'Cash Operations, Clean Note Policy & Counterfeit Currency',
    paper: 'PPB',
    targetTopicOrder: 42,
    targetTopicSlug: 'iibf-banker-customer-relationship-and-customer-service',
    targetConceptId: 'CON-IIBF-23',
    targetConceptSlug: 'cash-operations-management-clean-note-policy-and-ficn-counterfeit-detection',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-25',
    sourceNoteNumber: 63,
    sourceTitle: 'Principles of Lending, Working Capital Assessment & Term Loans',
    paper: 'PPB',
    targetTopicOrder: 43,
    targetTopicSlug: 'iibf-principles-of-lending-and-credit-assessment',
    targetConceptId: 'CON-IIBF-24',
    targetConceptSlug: 'principles-of-bank-lending-and-working-capital-assessment-turnover-mpbf-and-cash-budget',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-26',
    sourceNoteNumber: 64,
    sourceTitle: 'Types of Collaterals & Modes of Creating Charges',
    paper: 'PPB',
    targetTopicOrder: 43,
    targetTopicSlug: 'iibf-principles-of-lending-and-credit-assessment',
    targetConceptId: 'CON-IIBF-25',
    targetConceptSlug: 'modes-of-creating-charges-on-securities-pledge-hypothecation-mortgage-lien-and-assignment',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-27',
    sourceNoteNumber: 65,
    sourceTitle: 'Non-Fund Based Facilities — Letters of Credit (LC) & UCPDC 600',
    paper: 'PPB',
    targetTopicOrder: 44,
    targetTopicSlug: 'iibf-non-fund-facilities-and-trade-finance',
    targetConceptId: 'CON-IIBF-26',
    targetConceptSlug: 'letters-of-credit-operational-mechanism-parties-types-and-ucpdc-600-rules',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-28',
    sourceNoteNumber: 66,
    sourceTitle: 'Bank Guarantees (BG), Co-Acceptance & Deferred Payments',
    paper: 'PPB',
    targetTopicOrder: 44,
    targetTopicSlug: 'iibf-non-fund-facilities-and-trade-finance',
    targetConceptId: 'CON-IIBF-27',
    targetConceptSlug: 'bank-guarantees-financial-performance-statutory-invocations-and-co-acceptance',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-29',
    sourceNoteNumber: 67,
    sourceTitle: 'Export Finance & Foreign Exchange Operations for Banks',
    paper: 'PPB',
    targetTopicOrder: 44,
    targetTopicSlug: 'iibf-non-fund-facilities-and-trade-finance',
    targetConceptId: 'CON-IIBF-28',
    targetConceptSlug: 'export-finance-mechanisms-pre-shipment-post-shipment-pcfc-and-ecgc-cover',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-30',
    sourceNoteNumber: 70,
    sourceTitle: 'Essentials of Bank Computerization, CBS & Data Centers',
    paper: 'PPB',
    targetTopicOrder: 45,
    targetTopicSlug: 'iibf-digital-banking-and-it-security',
    targetConceptId: 'CON-IIBF-29',
    targetConceptSlug: 'core-banking-systems-architecture-data-center-redundancy-and-disaster-recovery-rto-rpo',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },
  {
    semanticUnitId: 'SEM-IIBF-31',
    sourceNoteNumber: 71,
    sourceTitle: 'Electronic Payment Systems, NPCI Architecture & Digital Rupee',
    paper: 'PPB',
    targetTopicOrder: 45,
    targetTopicSlug: 'iibf-digital-banking-and-it-security',
    targetConceptId: 'CON-IIBF-30',
    targetConceptSlug: 'electronic-payment-rails-rtgs-neft-upi-imps-nach-and-central-bank-digital-currency-cbdc',
    verifiedYear: 2026,
    temporalStatus: 'CURRENT_FRAMEWORK',
  },
  {
    semanticUnitId: 'SEM-IIBF-32',
    sourceNoteNumber: 72,
    sourceTitle: 'Cyber Security in Banks, ISO 27001 & Information Technology Act',
    paper: 'PPB',
    targetTopicOrder: 45,
    targetTopicSlug: 'iibf-digital-banking-and-it-security',
    targetConceptId: 'CON-IIBF-31',
    targetConceptSlug: 'cyber-security-framework-in-banks-soc-csirt-iso-27001-and-it-act-2000-statutory-provisions',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-33',
    sourceNoteNumber: 73,
    sourceTitle: 'Ethics, Business Values & Corporate Governance in Banks',
    paper: 'PPB',
    targetTopicOrder: 45,
    targetTopicSlug: 'iibf-digital-banking-and-it-security',
    targetConceptId: 'CON-IIBF-32',
    targetConceptSlug: 'banking-ethics-whistleblower-framework-and-corporate-governance-standards',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },

  // =========================================================================
  // PAPER 3: ACCOUNTING & FINANCIAL MANAGEMENT FOR BANKERS (AFMB)
  // =========================================================================
  {
    semanticUnitId: 'SEM-IIBF-34',
    sourceNoteNumber: 8,
    sourceTitle: 'Accounting Concepts, Principles (GAAP) & Ind AS Framework',
    paper: 'AFMB',
    targetTopicOrder: 46,
    targetTopicSlug: 'iibf-accounting-principles-and-financial-statements',
    targetConceptId: 'CON-IIBF-33',
    targetConceptSlug: 'accounting-foundations-gaap-conventions-and-ind-as-ifrs-convergence',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-35',
    sourceNoteNumber: 9,
    sourceTitle: 'Golden Rules of Accounting, Journalizing & Ledger Posting',
    paper: 'AFMB',
    targetTopicOrder: 46,
    targetTopicSlug: 'iibf-accounting-principles-and-financial-statements',
    targetConceptId: 'CON-IIBF-34',
    targetConceptSlug: 'double-entry-bookkeeping-golden-rules-journal-entries-and-ledger-balancing',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-36',
    sourceNoteNumber: 10,
    sourceTitle: 'Trial Balance, Rectification of Errors & Suspense Account',
    paper: 'AFMB',
    targetTopicOrder: 46,
    targetTopicSlug: 'iibf-accounting-principles-and-financial-statements',
    targetConceptId: 'CON-IIBF-35',
    targetConceptSlug: 'trial-balance-preparation-classification-of-accounting-errors-and-rectification-entries',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-37',
    sourceNoteNumber: 11,
    sourceTitle: 'Bank Reconciliation Statement (BRS)',
    paper: 'AFMB',
    targetTopicOrder: 46,
    targetTopicSlug: 'iibf-accounting-principles-and-financial-statements',
    targetConceptId: 'CON-IIBF-36',
    targetConceptSlug: 'bank-reconciliation-statement-brs-mechanics-timing-differences-and-reconciliation-rules',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-38',
    sourceNoteNumber: 12,
    sourceTitle: 'Depreciation Accounting & Mathematical Methods',
    paper: 'AFMB',
    targetTopicOrder: 47,
    targetTopicSlug: 'iibf-financial-mathematics-and-capital-budgeting',
    targetConceptId: 'CON-IIBF-37',
    targetConceptSlug: 'depreciation-accounting-methods-straight-line-slm-written-down-value-wdv-and-sinking-fund',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-39',
    sourceNoteNumber: 13,
    sourceTitle: 'Time Value of Money (TVM), Annuity & YTM Mathematics',
    paper: 'AFMB',
    targetTopicOrder: 47,
    targetTopicSlug: 'iibf-financial-mathematics-and-capital-budgeting',
    targetConceptId: 'CON-IIBF-38',
    targetConceptSlug: 'time-value-of-money-compounding-discounting-annuities-sinking-funds-and-amortization',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-40',
    sourceNoteNumber: 14,
    sourceTitle: 'Capital Budgeting & Investment Decisions (NPV, IRR, Payback)',
    paper: 'AFMB',
    targetTopicOrder: 47,
    targetTopicSlug: 'iibf-financial-mathematics-and-capital-budgeting',
    targetConceptId: 'CON-IIBF-39',
    targetConceptSlug: 'capital-budgeting-techniques-payback-npv-irr-profitability-index-and-discounted-payback',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-41',
    sourceNoteNumber: 15,
    sourceTitle: 'Ratio Analysis for Credit & Financial Health Assessment',
    paper: 'AFMB',
    targetTopicOrder: 48,
    targetTopicSlug: 'iibf-financial-analysis-and-taxation',
    targetConceptId: 'CON-IIBF-40',
    targetConceptSlug: 'financial-ratio-analysis-liquidity-solvency-profitability-turnover-and-dscr-metrics',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-42',
    sourceNoteNumber: 16,
    sourceTitle: 'Fundamentals of Costing, Marginal Costing & Break-Even Analysis',
    paper: 'AFMB',
    targetTopicOrder: 48,
    targetTopicSlug: 'iibf-financial-analysis-and-taxation',
    targetConceptId: 'CON-IIBF-41',
    targetConceptSlug: 'cost-accounting-and-marginal-costing-break-even-point-bep-margin-of-safety-and-pv-ratio',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-43',
    sourceNoteNumber: 17,
    sourceTitle: 'Direct & Indirect Taxation, GST & TDS in Banking',
    paper: 'AFMB',
    targetTopicOrder: 48,
    targetTopicSlug: 'iibf-financial-analysis-and-taxation',
    targetConceptId: 'CON-IIBF-42',
    targetConceptSlug: 'banking-taxation-architecture-tds-under-income-tax-act-and-gst-applicability-on-banking-services',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },

  // =========================================================================
  // PAPER 4: RETAIL BANKING & WEALTH MANAGEMENT (RBWM)
  // =========================================================================
  {
    semanticUnitId: 'SEM-IIBF-44',
    sourceNoteNumber: 74,
    sourceTitle: 'Retail Banking: Characteristics, Business Models & Segmentation',
    paper: 'RBWM',
    targetTopicOrder: 49,
    targetTopicSlug: 'iibf-retail-banking-products-and-wealth-management',
    targetConceptId: 'CON-IIBF-43',
    targetConceptSlug: 'retail-banking-architecture-customer-segmentation-business-models-and-cross-selling',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-45',
    sourceNoteNumber: 75,
    sourceTitle: 'Retail Lending Products: Housing, Auto, Education & Credit Cards',
    paper: 'RBWM',
    targetTopicOrder: 49,
    targetTopicSlug: 'iibf-retail-banking-products-and-wealth-management',
    targetConceptId: 'CON-IIBF-44',
    targetConceptSlug: 'retail-lending-products-home-loans-ltv-emi-credit-cards-and-education-loans',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-46',
    sourceNoteNumber: 76,
    sourceTitle: 'Credit Scoring (CIBIL & CICs), Recovery & DRA Code of Conduct',
    paper: 'RBWM',
    targetTopicOrder: 49,
    targetTopicSlug: 'iibf-retail-banking-products-and-wealth-management',
    targetConceptId: 'CON-IIBF-45',
    targetConceptSlug: 'credit-information-companies-cics-cibil-scoring-and-debt-recovery-agent-dra-guidelines',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-47',
    sourceNoteNumber: 77,
    sourceTitle: 'Wealth Management, Investment Advisory & Real Estate (RERA)',
    paper: 'RBWM',
    targetTopicOrder: 49,
    targetTopicSlug: 'iibf-retail-banking-products-and-wealth-management',
    targetConceptId: 'CON-IIBF-46',
    targetConceptSlug: 'wealth-management-portfolio-allocation-estate-planning-and-rera-regulations',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },

  // =========================================================================
  // BANKING STATUTORY GOVERNANCE & RBI FM MANAGEMENT VAULT
  // =========================================================================
  {
    semanticUnitId: 'SEM-IIBF-48',
    sourceNoteNumber: 1,
    sourceTitle: 'Module 1: Deposit Operations, Customer Rights & Statutory Governance',
    paper: 'BANKING_REGULATIONS',
    targetTopicOrder: 50,
    targetTopicSlug: 'iibf-banking-regulations-and-statutory-governance',
    targetConceptId: 'CON-IIBF-47',
    targetConceptSlug: 'banking-regulation-act-1949-licensing-governance-and-reserve-bank-regulatory-powers',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-49',
    sourceNoteNumber: 2,
    sourceTitle: 'Module 2: Credit Risk, Prudential Lending & Fair Lending Frameworks',
    paper: 'BANKING_REGULATIONS',
    targetTopicOrder: 50,
    targetTopicSlug: 'iibf-banking-regulations-and-statutory-governance',
    targetConceptId: 'CON-IIBF-48',
    targetConceptSlug: 'prudential-exposure-norms-large-exposure-framework-lef-and-connected-lending-curbs',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-50',
    sourceNoteNumber: 7,
    sourceTitle: 'IIBF High-Yield Banking Traps & Rapid Recall Cheat Sheet',
    paper: 'BANKING_REGULATIONS',
    targetTopicOrder: 50,
    targetTopicSlug: 'iibf-banking-regulations-and-statutory-governance',
    targetConceptId: 'CON-IIBF-49',
    targetConceptSlug: 'deposit-insurance-dicgc-act-1961-rs-5-lakh-coverage-and-claim-settlement-timelines',
    verifiedYear: 2026,
    temporalStatus: 'STATUTORY_RULE',
  },
  {
    semanticUnitId: 'SEM-IIBF-51',
    sourceNoteNumber: 78,
    sourceTitle: 'RBI Grade B (FM) Volume 1: Management & Organisational Behaviour Descriptive Vault',
    paper: 'RBI_FM',
    targetTopicOrder: 51,
    targetTopicSlug: 'rbi-management-and-organisational-behaviour',
    targetConceptId: 'CON-IIBF-50',
    targetConceptSlug: 'management-theories-classical-neo-classical-and-modern-leadership-models',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
  {
    semanticUnitId: 'SEM-IIBF-52',
    sourceNoteNumber: 79,
    sourceTitle: 'RBI Grade B (FM) Volume 2: Organisational Communication Descriptive Vault',
    paper: 'RBI_FM',
    targetTopicOrder: 51,
    targetTopicSlug: 'rbi-management-and-organisational-behaviour',
    targetConceptId: 'CON-IIBF-51',
    targetConceptSlug: 'organisational-communication-barriers-channels-and-corporate-governance-mechanisms',
    verifiedYear: 2026,
    temporalStatus: 'CORE_FOUNDATION',
  },
];
