/**
 * Quantitative Aptitude — Source Corpus Forensic Inventory Ledger
 * Status: AUDIT ONLY — NO CANONICAL CONCEPTS CREATED
 */

export interface QuantSourceNoteInventoryItem {
  noteIndex: number;
  itemId: string;
  title: string;
  section: string;
  targetExams: string[];
  lineCount: number;
  classification: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K';
  classificationDescription: string;
  hasBrokenStubs: boolean;
  stubCount: number;
  mathEscapeCorruption: boolean;
  pedagogicalValue: 'VERY_HIGH' | 'HIGH' | 'MEDIUM' | 'LOW';
  recommendedCanonicalTarget: string;
}

export const QUANT_SOURCE_INVENTORY: QuantSourceNoteInventoryItem[] = [
  {
    noteIndex: 1,
    itemId: 'migrated-quant-qsec4-1',
    title: '1 Core Formulas & Identities',
    section: 'Algebra',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 26,
    classification: 'B',
    classificationDescription: 'Useful solved methodology & formulas',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: false,
    pedagogicalValue: 'HIGH',
    recommendedCanonicalTarget: 'Algebraic Identities, Quadratic Equations & Root Sign Heuristics',
  },
  {
    noteIndex: 2,
    itemId: 'migrated-quant-qsec7-2',
    title: '2 Permutation & Combination Shortcuts',
    section: 'Modern Math',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 31,
    classification: 'K',
    classificationDescription: 'Mixed; valid handshake rule + empty latex code fence',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: false,
    pedagogicalValue: 'HIGH',
    recommendedCanonicalTarget: 'Permutations, Combinations, Probability & Strategic Counting',
  },
  {
    noteIndex: 3,
    itemId: 'migrated-quant-qsec3-2',
    title: '2 Shortcuts & Estimation Tricks',
    section: 'Data Interpretation',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 27,
    classification: 'F',
    classificationDescription: 'Exam strategy & estimation heuristics',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: false,
    pedagogicalValue: 'MEDIUM',
    recommendedCanonicalTarget: 'Data Interpretation: Visual Graphs, Estimation & Advanced Caselets',
  },
  {
    noteIndex: 4,
    itemId: 'migrated-quant-qsec5-2',
    title: '2 Shortcuts & Tricks',
    section: 'Number Series',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 27,
    classification: 'I',
    classificationDescription: 'Potentially flawed rounding rule in addition',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: false,
    pedagogicalValue: 'MEDIUM',
    recommendedCanonicalTarget: 'Number Series: Difference-Trees, Multipliers & Wrong Number Diagnostics',
  },
  {
    noteIndex: 5,
    itemId: 'migrated-quant-qsec6-2',
    title: '2 Shortcuts & Tricks',
    section: 'Data Sufficiency',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 27,
    classification: 'F',
    classificationDescription: 'Exam strategy on Data Sufficiency',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: false,
    pedagogicalValue: 'HIGH',
    recommendedCanonicalTarget: 'Data Sufficiency Decision Logic, Quantity Comparison & Circular Races',
  },
  {
    noteIndex: 6,
    itemId: 'migrated-quant-qsec1-1',
    title: '2D Geometry & Mensuration Masterclass',
    section: 'Mensuration',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 51,
    classification: 'A',
    classificationDescription: 'Strong conceptual material with 3-tier right-triangle inradius problem',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: true,
    pedagogicalValue: 'VERY_HIGH',
    recommendedCanonicalTarget: '2D Mensuration: Plane Figures, Inscribed Systems & Pathway Invariants',
  },
  {
    noteIndex: 7,
    itemId: 'migrated-quant-qsec2-3',
    title: '3 Worked Examples',
    section: 'Arithmetic',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 35,
    classification: 'H',
    classificationDescription: 'Incomplete; 4 empty solution stubs (CI-SI, Partnership, Work, Mixture)',
    hasBrokenStubs: true,
    stubCount: 4,
    mathEscapeCorruption: false,
    pedagogicalValue: 'LOW',
    recommendedCanonicalTarget: 'Commercial Interest, Partnership, Mixture & Dilution Invariants',
  },
  {
    noteIndex: 8,
    itemId: 'migrated-quant-qsec3-3',
    title: '3 Worked Examples',
    section: 'Data Interpretation',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 27,
    classification: 'H',
    classificationDescription: 'Incomplete; 3 empty solution stubs (Pie %, Dual pie, Bar CAGR)',
    hasBrokenStubs: true,
    stubCount: 3,
    mathEscapeCorruption: false,
    pedagogicalValue: 'LOW',
    recommendedCanonicalTarget: 'Data Interpretation: Visual Graphs, Estimation & Advanced Caselets',
  },
  {
    noteIndex: 9,
    itemId: 'migrated-quant-qsec4-3',
    title: '3 Worked Examples',
    section: 'Algebra',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 27,
    classification: 'H',
    classificationDescription: 'Incomplete; 2 empty solution stubs (Quadratic comparison, a+1/a)',
    hasBrokenStubs: true,
    stubCount: 2,
    mathEscapeCorruption: false,
    pedagogicalValue: 'LOW',
    recommendedCanonicalTarget: 'Algebraic Identities, Quadratic Equations & Root Sign Heuristics',
  },
  {
    noteIndex: 10,
    itemId: 'migrated-quant-qsec5-3',
    title: '3 Worked Examples',
    section: 'Number Series',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 27,
    classification: 'H',
    classificationDescription: 'Incomplete; 2 empty solution stubs (2nd-level diff, Wrong number)',
    hasBrokenStubs: true,
    stubCount: 2,
    mathEscapeCorruption: false,
    pedagogicalValue: 'LOW',
    recommendedCanonicalTarget: 'Number Series: Difference-Trees, Multipliers & Wrong Number Diagnostics',
  },
  {
    noteIndex: 11,
    itemId: 'migrated-quant-qsec6-3',
    title: '3 Worked Examples',
    section: 'Data Sufficiency',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 27,
    classification: 'H',
    classificationDescription: 'Incomplete; 2 empty solution stubs (DS quantity, DS comparison)',
    hasBrokenStubs: true,
    stubCount: 2,
    mathEscapeCorruption: false,
    pedagogicalValue: 'LOW',
    recommendedCanonicalTarget: 'Data Sufficiency Decision Logic, Quantity Comparison & Circular Races',
  },
  {
    noteIndex: 12,
    itemId: 'migrated-quant-qsec7-3',
    title: '3 Worked Examples',
    section: 'Modern Math',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 27,
    classification: 'H',
    classificationDescription: 'Incomplete; 2 empty solution stubs (BANANA, Independent target hit)',
    hasBrokenStubs: true,
    stubCount: 2,
    mathEscapeCorruption: false,
    pedagogicalValue: 'LOW',
    recommendedCanonicalTarget: 'Permutations, Combinations, Probability & Strategic Counting',
  },
  {
    noteIndex: 13,
    itemId: 'migrated-quant-qsec1-2',
    title: '3D Solid Mensuration & Surface Topology',
    section: 'Mensuration',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 41,
    classification: 'A',
    classificationDescription: 'Strong conceptual material on volume conservation & surface topology',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: true,
    pedagogicalValue: 'VERY_HIGH',
    recommendedCanonicalTarget: '3D Solid Geometry, Composite Solids, Frustums & Dimensional Scaling',
  },
  {
    noteIndex: 14,
    itemId: 'migrated-quant-qsec1-5',
    title: '5 Worked Examples',
    section: 'Mensuration',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 33,
    classification: 'H',
    classificationDescription: 'Incomplete; 4 empty solution stubs (Cone on cylinder, Sphere to cones, Painting, Frustum)',
    hasBrokenStubs: true,
    stubCount: 4,
    mathEscapeCorruption: false,
    pedagogicalValue: 'LOW',
    recommendedCanonicalTarget: '3D Solid Geometry, Composite Solids, Frustums & Dimensional Scaling',
  },
  {
    noteIndex: 15,
    itemId: 'migrated-quant-qsec2-2',
    title: 'Advanced Arithmetic Shortcuts',
    section: 'Arithmetic',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 26,
    classification: 'C',
    classificationDescription: 'Useful shortcuts for LCM models, variable leaks, escalators',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: true,
    pedagogicalValue: 'HIGH',
    recommendedCanonicalTarget: 'Time, Work, Pipes & Dynamic Efficiency Models',
  },
  {
    noteIndex: 16,
    itemId: 'migrated-quant-qsec4-2',
    title: 'Algebra & Quadratic Equations Masterclass',
    section: 'Algebra',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 39,
    classification: 'A',
    classificationDescription: 'Strong methodology on root sign table & double negative constant rule',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: true,
    pedagogicalValue: 'VERY_HIGH',
    recommendedCanonicalTarget: 'Algebraic Identities, Quadratic Equations & Root Sign Heuristics',
  },
  {
    noteIndex: 17,
    itemId: 'migrated-quant-qsec2-1',
    title: 'Arithmetic Mastery: Time & Work, TSD, Boats, Alligation',
    section: 'Arithmetic',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 65,
    classification: 'A',
    classificationDescription: 'Strong conceptual core + complete 3-tier alternate days worked example',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: true,
    pedagogicalValue: 'VERY_HIGH',
    recommendedCanonicalTarget: 'Time, Work, Pipes & Dynamic Efficiency Models',
  },
  {
    noteIndex: 18,
    itemId: 'migrated-quant-qsec3-1',
    title: 'Data Interpretation Masterclass',
    section: 'Data Interpretation',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 31,
    classification: 'B',
    classificationDescription: 'Useful taxonomy of banking DI & fraction-to-percentage table',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: true,
    pedagogicalValue: 'HIGH',
    recommendedCanonicalTarget: 'Data Interpretation: Visual Graphs, Estimation & Advanced Caselets',
  },
  {
    noteIndex: 19,
    itemId: 'migrated-quant-qsec6-1',
    title: 'Data Sufficiency & Quantity Comparison',
    section: 'Data Sufficiency',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 32,
    classification: 'A',
    classificationDescription: 'Strong decision-tree heuristics & uniqueness criteria',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: true,
    pedagogicalValue: 'VERY_HIGH',
    recommendedCanonicalTarget: 'Data Sufficiency Decision Logic, Quantity Comparison & Circular Races',
  },
  {
    noteIndex: 20,
    itemId: 'migrated-quant-qsec1-3',
    title: 'Frustum of Cone, Pyramid & Combined 3D Solids',
    section: 'Mensuration',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 32,
    classification: 'A',
    classificationDescription: 'Strong mathematical formulation of frustums & composite solids',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: true,
    pedagogicalValue: 'VERY_HIGH',
    recommendedCanonicalTarget: '3D Solid Geometry, Composite Solids, Frustums & Dimensional Scaling',
  },
  {
    noteIndex: 21,
    itemId: 'migrated-quant-qsec1-4',
    title: 'Mensuration Percentage Scaling Shortcuts',
    section: 'Mensuration',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 32,
    classification: 'C',
    classificationDescription: 'Useful dimensional scaling & percentage multipliers',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: true,
    pedagogicalValue: 'HIGH',
    recommendedCanonicalTarget: '3D Solid Geometry, Composite Solids, Frustums & Dimensional Scaling',
  },
  {
    noteIndex: 22,
    itemId: 'migrated-quant-qsec7-1',
    title: 'Modern Mathematics: P&C & Probability Theory',
    section: 'Modern Math',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 40,
    classification: 'A',
    classificationDescription: 'Strong combinatorial & probability theory',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: true,
    pedagogicalValue: 'VERY_HIGH',
    recommendedCanonicalTarget: 'Permutations, Combinations, Probability & Strategic Counting',
  },
  {
    noteIndex: 23,
    itemId: 'migrated-quant-qsec5-1',
    title: 'Number Series & Pattern Recognition',
    section: 'Number Series',
    targetExams: ['Bank PO', 'RBI Grade B', 'SBI PO'],
    lineCount: 33,
    classification: 'B',
    classificationDescription: 'Useful difference-tree algorithm & wrong number diagnostic heuristics',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: true,
    pedagogicalValue: 'HIGH',
    recommendedCanonicalTarget: 'Number Series: Difference-Trees, Multipliers & Wrong Number Diagnostics',
  },
  {
    noteIndex: 24,
    itemId: 'quant-rbi-grade-b-pyq-master-suite',
    title: 'RBI Grade B Phase 1 Quant Memory-Based PYQ Masterclass',
    section: 'PYQ & Applied DI',
    targetExams: ['RBI Grade B Phase 1 2026', 'SBI PO Mains 2026', 'IBPS PO Mains 2026'],
    lineCount: 55,
    classification: 'E',
    classificationDescription: 'High-quality authentic 3-tier solved PYQs (NPA Caselet DI & Circular Track)',
    hasBrokenStubs: false,
    stubCount: 0,
    mathEscapeCorruption: true,
    pedagogicalValue: 'VERY_HIGH',
    recommendedCanonicalTarget: 'Data Interpretation: Visual Graphs, Estimation & Advanced Caselets',
  },
];
