export interface SourceObservation {
  observationId: string;
  pdfPage: number;
  printedPage: number;
  sourceHeading: string;
  observedContentType: string;
  origin: 'TEXT_DERIVED' | 'TABLE_DERIVED' | 'VISUAL_DERIVED';
  description: string;
  confidence: 'HIGH' | 'MEDIUM';
}

/**
 * Authoritative, Immutable 44 Independent Source Observations for Topic 9
 * (Printed pp. 56-82 / PDF pp. 62-88).
 */
export const INDEPENDENT_SOURCE_OBSERVATIONS: SourceObservation[] = [
  {
    observationId: 'OBS-T9-01',
    pdfPage: 62,
    printedPage: 56,
    sourceHeading: 'Overview of Part III — Historical Evolution & Magna Carta of India',
    observedContentType: 'CONCEPT',
    origin: 'TEXT_DERIVED',
    description: 'Historical evolution from Magna Carta 1215, French Declaration 1789, US Bill of Rights 1791; Part III called Magna Carta of India.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-02',
    pdfPage: 62,
    printedPage: 56,
    sourceHeading: 'Natural Rights vs Human Rights vs Fundamental Rights Distinction',
    observedContentType: 'COMPARISON',
    origin: 'TEXT_DERIVED',
    description: 'Conceptual distinction between natural rights, human rights, ordinary legal rights, and constitutionally guaranteed fundamental rights.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-03',
    pdfPage: 62,
    printedPage: 56,
    sourceHeading: '6 Categories of Fundamental Rights Comparison Matrix',
    observedContentType: 'COMPARISON_TABLE',
    origin: 'TABLE_DERIVED',
    description: 'Structured classification table of 6 FR categories with article spans; deletion of Right to Property noted.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-04',
    pdfPage: 63,
    printedPage: 57,
    sourceHeading: 'Article 12 — Statutory Definition of State (4 Limbs)',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: '4 statutory limbs: Union Govt/Parliament, State Govt/Legislatures, Local Authorities, Other Authorities.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-05',
    pdfPage: 63,
    printedPage: 57,
    sourceHeading: 'Article 12 — Judicial Interpretation of "Other Authorities" (Ajay Hasia / Zee / BCCI)',
    observedContentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    description: 'Tests of instrumentality/agency of State: Ajay Hasia, Rajasthan SEB, Zee Telefilms (BCCI held not State under Art 12), Judiciary as State debates.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-06',
    pdfPage: 64,
    printedPage: 58,
    sourceHeading: 'Article 13 — Pre/Post Constitutional Inconsistency & Law Definition',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: '13(1) Pre-constitutional laws, 13(2) Post-constitutional laws, 13(3) Definition of Law (orders, bye-laws, customs, usages).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-07',
    pdfPage: 64,
    printedPage: 58,
    sourceHeading: 'Article 13 — Doctrine of Severability (AK Gopalan / RMDC)',
    observedContentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    description: 'Only the unconstitutional portion of a statute is void if severable from the valid portion (AK Gopalan, RMDC).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-08',
    pdfPage: 64,
    printedPage: 58,
    sourceHeading: 'Article 13 — Doctrines of Eclipse (Bhikaji) and Waiver (Basheshar Nath)',
    observedContentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    description: 'Doctrine of Eclipse (Bhikaji Narayan 1955: pre-constitutional law remains dormant); Doctrine of Waiver (Basheshar Nath: citizens cannot waive fundamental rights).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-09',
    pdfPage: 65,
    printedPage: 59,
    sourceHeading: 'Article 14 — Equality Before Law (UK) & Equal Protection (US)',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: 'Dual expressions: Equality before law (UK Common Law/Dicey) and Equal protection of laws (US 14th Amendment); Personal scope covers "any person".',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-10',
    pdfPage: 65,
    printedPage: 59,
    sourceHeading: 'Article 14 — Reasonable Classification vs Class Legislation (Anwar Ali 2-Pronged Test)',
    observedContentType: 'LEGAL_RULE',
    origin: 'TEXT_DERIVED',
    description: 'Prohibition of class legislation; 2-pronged test: Intelligible Differentia and Rational Nexus (Anwar Ali Sarkar, Chiranjit Lal, Ram Krishna Dalmia).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-11',
    pdfPage: 65,
    printedPage: 59,
    sourceHeading: 'Article 14 — Dynamic Non-Arbitrariness Doctrine (Royappa / Maneka Gandhi)',
    observedContentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    description: 'EP Royappa (1974), Maneka Gandhi (1978), Ajay Hasia (1981); Equality is antithetical to arbitrariness.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-12',
    pdfPage: 66,
    printedPage: 60,
    sourceHeading: 'Article 15 — Prohibited Grounds & Special Protective Clauses (15(1)-15(5))',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: '15(1) & 15(2) Prohibition on 5 grounds (religion, race, caste, sex, place of birth); 15(3) women/children; 15(4) 1st Amendment 1951 (Champakam); 15(5) 93rd Amendment 2005.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-13',
    pdfPage: 66,
    printedPage: 60,
    sourceHeading: 'Sub Topic 1: Creamy Layer Concept for Backward Classes (Ram Nandan Committee)',
    observedContentType: 'CONCEPT',
    origin: 'TEXT_DERIVED',
    description: 'Meaning of Creamy Layer for OBCs, Ram Nandan Committee 1993, and income threshold evolution (1 lakh in 1993 to 8 lakh in 2017).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-14',
    pdfPage: 67,
    printedPage: 61,
    sourceHeading: 'Article 16 — Equality of Opportunity in Public Employment & Domicile Clause',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: '16(1) & 16(2) 7 prohibited grounds (including Descent and Residence); 16(3) Parliamentary residence qualification; 16(4) reservation.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-15',
    pdfPage: 67,
    printedPage: 61,
    sourceHeading: 'Articles 16(4A), 16(4B) & SC/ST Promotion Reservation / Seniority Debate',
    observedContentType: 'LEGAL_RULE',
    origin: 'TEXT_DERIVED',
    description: '77th Amendment (16(4A)), 81st Amendment (16(4B) 50% cap on backlog vacancies), 85th Amendment (consequential seniority); Arguments on creamy layer in promotion for SC/ST.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-16',
    pdfPage: 68,
    printedPage: 62,
    sourceHeading: 'Sub Topic 2: Justice Rohini Commission (OBC Sub-Categorization Model)',
    observedContentType: 'CURRENT_AFFAIRS_REFERENCE',
    origin: 'TEXT_DERIVED',
    description: 'Constituted Oct 2017 under Article 340; Findings on concentration of reservation benefits; Proposed 4-tier sub-categorization model.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-17',
    pdfPage: 69,
    printedPage: 63,
    sourceHeading: '103rd Constitutional Amendment Act 2019 — 10% EWS Reservation (Janhit Abhiyan)',
    observedContentType: 'LEGAL_RULE',
    origin: 'TEXT_DERIVED',
    description: 'Inserted Articles 15(6) and 16(6); 8 lakh income criteria; Janhit Abhiyan v. UOI (2022) 3:2 Constitution Bench verdict upholding EWS quota.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-18',
    pdfPage: 70,
    printedPage: 64,
    sourceHeading: 'Reservation Landmark Judgments Matrix (1992 Indra Sawhney → 2024 Davinder Singh)',
    observedContentType: 'COMPARISON_TABLE',
    origin: 'TABLE_DERIVED',
    description: 'Comprehensive table tracing Indra Sawhney (1992), M. Nagaraj (2006), Jarnail Singh (2018), and State of Punjab v. Davinder Singh (2024 SC/ST sub-classification).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-19',
    pdfPage: 71,
    printedPage: 65,
    sourceHeading: 'Article 17 — Abolition of Untouchability & Statutory Framework',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: 'Absolute constitutional prohibition; Protection of Civil Rights Act 1955; SC/ST (POA) Act 1989; Applies against state and private individuals.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-20',
    pdfPage: 71,
    printedPage: 65,
    sourceHeading: 'Article 18 — Abolition of Titles & National Awards Standing',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: '18(1) No title conferred except military/academic; 18(2) Foreign titles barred; Balaji Raghavan v. UOI (1996) national honours upheld.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-21',
    pdfPage: 72,
    printedPage: 66,
    sourceHeading: 'Article 19 — 6 Democratic Freedoms & Reasonable Restriction Matrix',
    observedContentType: 'COMPARISON_TABLE',
    origin: 'TABLE_DERIVED',
    description: '19(1)(a) Speech, 19(1)(b) Assembly, 19(1)(c) Association/Cooperatives, 19(1)(d) Movement, 19(1)(e) Residence, 19(1)(g) Profession; Paired with 19(2)-19(6) restriction grounds.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-22',
    pdfPage: 73,
    printedPage: 67,
    sourceHeading: 'Topic: Right to Internet & Telecommunication Suspension (Anuradha Bhasin)',
    observedContentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    description: 'Indian Telegraph Act 1885 rules; Anuradha Bhasin v. UOI (2020) & Faheema Shirin v. State of Kerala (2019); Proportionality requirement for shutdowns.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-23',
    pdfPage: 74,
    printedPage: 68,
    sourceHeading: 'Topic: Phone Tapping Rules & Privacy Rights (PUCL 1997)',
    observedContentType: 'LEGAL_RULE',
    origin: 'TEXT_DERIVED',
    description: 'PUCL v. UOI (1997) phone tapping guidelines; Section 5(2) Telegraph Act grounds; Review committee oversight.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-24',
    pdfPage: 75,
    printedPage: 69,
    sourceHeading: 'Topic: Right to Protest vs Public Convenience (Shaheen Bagh / Amit Sahni 2020)',
    observedContentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    description: 'Amit Sahni v. Commissioner of Police (2020) Shaheen Bagh ruling: Right to protest cannot occupy public roads indefinitely; Designated protest spaces.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-25',
    pdfPage: 76,
    printedPage: 70,
    sourceHeading: 'Article 20 — Protection in Respect of Conviction for Offences',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: '20(1) Ex-post facto criminal law protection; 20(2) Double jeopardy (court/tribunal only); 20(3) Self-incrimination (Selvi v. State of Karnataka 2010 narco/polygraph ban).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-26',
    pdfPage: 77,
    printedPage: 71,
    sourceHeading: 'Article 21 — Protection of Life & Personal Liberty (Procedure vs Due Process)',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: 'AK Gopalan (1950) literal procedure established by law overturned in Maneka Gandhi (1978) substantive due process; Interplay of Arts 14, 19, 21.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-27',
    pdfPage: 77,
    printedPage: 71,
    sourceHeading: 'Article 21 — Catalog of 30+ Inferred Substantive Fundamental Rights',
    observedContentType: 'FACT',
    origin: 'TEXT_DERIVED',
    description: 'Catalog of 30+ implied fundamental rights under Art 21 (human dignity, clean environment, health, shelter, livelihood, speedy trial, legal aid, sleep, emergency medical care).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-28',
    pdfPage: 78,
    printedPage: 72,
    sourceHeading: 'Topic 1: Right to Privacy (K.S. Puttaswamy 2017 Proportionality Standard)',
    observedContentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    description: '9-judge bench holding privacy as intrinsic part of Article 21 and Part III; 3-fold proportionality test (Legality, Legitimate Goal, Proportionality); UPSC 2017 PYQ callout.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-29',
    pdfPage: 78,
    printedPage: 72,
    sourceHeading: 'Topic 2: Right to Die with Dignity & Living Wills (Common Cause 2018)',
    observedContentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    description: 'Aruna Shanbaug (2011) and Common Cause (2018): Passive euthanasia and advance medical directives (Living Wills) upheld under Article 21.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-30',
    pdfPage: 79,
    printedPage: 73,
    sourceHeading: 'Article 21A — Right to Free & Compulsory Education (86th Amendment & RTE Act)',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: 'Mohini Jain (1992) & Unni Krishnan (1993); 86th Amendment Act 2002 inserted Article 21A (free & compulsory education 6-14 years); RTE Act 2009.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-31',
    pdfPage: 79,
    printedPage: 73,
    sourceHeading: 'Article 22 — Protection Against Arrest & Preventive Detention',
    observedContentType: 'LEGAL_RULE',
    origin: 'TEXT_DERIVED',
    description: 'Punitive arrest rights (grounds of arrest, 24h magistrate production, legal counsel); Preventive detention safeguards (Advisory Board, 3-month max rule).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-32',
    pdfPage: 80,
    printedPage: 74,
    sourceHeading: 'Topic: Preventive Detention & UAPA Bail Jurisprudence (Vernon Gonsalves / Najeeb)',
    observedContentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    description: 'Section 43D(5) UAPA vs Article 21 speedy trial right; Vernon Gonsalves (2023) and Union of India v. KA Najeeb (2021) Supreme Court rulings on prolonged incarceration.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-33',
    pdfPage: 81,
    printedPage: 75,
    sourceHeading: 'Articles 23 & 24 — Right Against Exploitation (Begar, Human Trafficking, Child Labour)',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: 'Article 23 (Trafficking in human beings, Begar, bonded labour prohibited; state compulsory service exception); Article 24 (Child labour prohibition below 14 in factories/mines/hazardous work).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-34',
    pdfPage: 81,
    printedPage: 75,
    sourceHeading: 'Article 25 — Freedom of Conscience, Religion & Essential Religious Practices Doctrine',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: 'Article 25 text, 4 freedoms (conscience, profess, practice, propagate), limitations (public order, morality, health), and judicial Essential Religious Practices doctrine (Shirur Mutt 1954, Sabarimala, Triple Talaq, Santhara).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-35',
    pdfPage: 82,
    printedPage: 76,
    sourceHeading: 'Articles 26, 27, 28 — Institutional Religious Freedoms & No Religious Tax',
    observedContentType: 'LEGAL_RULE',
    origin: 'TEXT_DERIVED',
    description: 'Article 26 (Religious denominations rights to manage affairs), Article 27 (Prohibition of taxes for religion), Article 28 (Religious instruction in state-funded institutions).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-36',
    pdfPage: 82,
    printedPage: 76,
    sourceHeading: 'Article 29 — Protection of Interests of Linguistic & Cultural Minorities',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: '29(1) Right of any section of citizens with distinct language/script/culture; 29(2) Non-discrimination in state-funded educational institutions on religion/race/caste/language.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-37',
    pdfPage: 83,
    printedPage: 77,
    sourceHeading: 'Article 30 — Minorities Right to Establish & Administer Educational Institutions',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: 'Applies to religious and linguistic minorities; 30(1A) 44th Amendment compensation; St. Stephens (1992), TMA Pai (2002), PA Inamdar (2005) regulatory autonomy benchmarks.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-38',
    pdfPage: 83,
    printedPage: 77,
    sourceHeading: 'Article 31 & 300A — Deletion of Right to Property as Fundamental Right (44th Amendment)',
    observedContentType: 'HISTORICAL_CLAIM',
    origin: 'TEXT_DERIVED',
    description: '44th Constitutional Amendment Act 1978 deleted Art 19(1)(f) and Art 31; Transferred to Art 300A (Part XII) as constitutional/legal right.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-39',
    pdfPage: 84,
    printedPage: 78,
    sourceHeading: 'Topic: Demolition Actions ("Bulldozer Justice") & Judicial Due Process Directives',
    observedContentType: 'JUDICIAL_DOCTRINE',
    origin: 'TEXT_DERIVED',
    description: 'Supreme Court guidelines on punitive demolitions: violation of Rule of Law and Right to Shelter under Article 21; Mandatory 15-day notice and due process requirement.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-40',
    pdfPage: 85,
    printedPage: 79,
    sourceHeading: 'Article 32 — Right to Constitutional Remedies ("Heart and Soul of Constitution")',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: '"Heart and Soul of the Constitution" (BR Ambedkar); Fundamental right to approach Supreme Court for Part III enforcement; Basic structure doctrine.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-41',
    pdfPage: 85,
    printedPage: 79,
    sourceHeading: 'Comparative Matrix of 5 Constitutional Writs (Habeas Corpus, Mandamus, etc.)',
    observedContentType: 'COMPARISON_TABLE',
    origin: 'TABLE_DERIVED',
    description: 'Comprehensive structured table comparing Habeas Corpus, Mandamus, Prohibition, Certiorari, and Quo Warranto (Literal meaning, Against whom issued, When not issued).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-42',
    pdfPage: 86,
    printedPage: 80,
    sourceHeading: 'Articles 33, 34, 35 — Special Limitations on Fundamental Rights (Armed Forces & Martial Law)',
    observedContentType: 'CONSTITUTIONAL_TEXT',
    origin: 'TEXT_DERIVED',
    description: 'Article 33 (Armed forces, police, intelligence restrictions by Parliament), Article 34 (Indemnity under Martial Law), Article 35 (Exclusive Parliamentary legislative competence for Part III).',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-43',
    pdfPage: 87,
    printedPage: 81,
    sourceHeading: 'Constitutional Amendability of Fundamental Rights Timeline (1951 Shankari Prasad → 1973 Kesavananda)',
    observedContentType: 'HISTORICAL_CLAIM',
    origin: 'TEXT_DERIVED',
    description: 'Chronological timeline: Shankari Prasad (1951) → Sajjan Singh (1965) → Golaknath (1967) → 24th Amendment (1971) → Kesavananda Bharati (1973) Basic Structure Doctrine.',
    confidence: 'HIGH',
  },
  {
    observationId: 'OBS-T9-44',
    pdfPage: 88,
    printedPage: 82,
    sourceHeading: 'Article 31C & Harmonious Balance Between FRs and DPSPs (Minerva Mills 1980)',
    observedContentType: 'LEGAL_RULE',
    origin: 'TEXT_DERIVED',
    description: '25th Amendment 1971 inserted 31C; 42nd Amendment 1976 blanket extension invalidated in Minerva Mills (1980); Doctrine of harmonious construction between Part III and Part IV.',
    confidence: 'HIGH',
  },
];
