/**
 * STATIC GA & GOVERNMENT SCHEMES SOURCE INVENTORY & CLASSIFICATION LEDGER
 *
 * Enforces the Zero Unaccounted-For Source Omission Principle for:
 * 1. `Static_GA_Superbook_Master.md` (38 notes)
 * 2. `Government_Schemes_Master.md` (1 note / 4 sections)
 */

export interface SourceInventoryItem {
  id: string;
  sourceFile: 'Static_GA_Superbook_Master.md' | 'Government_Schemes_Master.md';
  sourceTitle: string;
  sourceCategory: string;
  classification:
    | 'STATIC_GA'
    | 'GOVERNMENT_SCHEMES'
    | 'MIXED_STATIC_AND_CURRENT'
    | 'CURRENT_AFFAIRS_ONLY'
    | 'DUPLICATE_OR_STUB'
    | 'INCORRECT_REQUIRES_CORRECTION';
  action: 'CANONICAL_CONCEPT' | 'DEDUPLICATED_INTO_EXISTING' | 'EXCLUDED_CURRENT_AFFAIRS' | 'EXCLUDED_STUB' | 'CORRECTED_STATUTORY_FRAMEWORK';
  targetConceptId?: string;
  notes: string;
}

export const STATIC_GA_SCHEMES_INVENTORY: SourceInventoryItem[] = [
  // --- GOVERNMENT SCHEMES MASTERFILE ---
  {
    id: 'INV-GS-01',
    sourceFile: 'Government_Schemes_Master.md',
    sourceTitle: 'Government Schemes Masterfile (10-Bucket Complete Framework)',
    sourceCategory: 'Master Reference',
    classification: 'GOVERNMENT_SCHEMES',
    action: 'CANONICAL_CONCEPT',
    targetConceptId: 'CON-SCH-01',
    notes: 'Forms canonical Concept CON-SCH-01: Central Sector vs Centrally Sponsored (60:40/90:10), SNA model, DBT conduits, and exam traps.',
  },

  // --- STATIC GA SUPERBOOK MASTER (38 NOTES) ---
  {
    id: 'INV-SGA-01',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '1. Agriculture, Energy & Water Resources (21 Schemes)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'EXCLUDED_STUB',
    notes: 'Placeholder header with no body text; Geneva/Vienna HQ exam anchor extracted to CON-GA-01.',
  },
  {
    id: 'INV-SGA-02',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '2. Core Central Welfare Schemes (PMJDY, PMJJBY, PMSBY, PMMY, PM SVANidhi)',
    sourceCategory: 'StaticGA',
    classification: 'GOVERNMENT_SCHEMES',
    action: 'CANONICAL_CONCEPT',
    targetConceptId: 'CON-SCH-02',
    notes: 'Forms canonical Concepts CON-SCH-02 (PMJDY, PMJJBY, PMSBY, APY) and CON-SCH-03 (PMMY MUDRA, PM SVANidhi, PM Vishwakarma).',
  },
  {
    id: 'INV-SGA-03',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '3. D-SIBs & Priority Sector Lending (PSL) Targets',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Fully covered in IIBF Subject (CON-IIBF-04 in Topic 38 and Topic 42).',
  },
  {
    id: 'INV-SGA-04',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '4. DAY-NRLM SHG Credit Framework & Subvention (FY 2025–26)',
    sourceCategory: 'StaticGA',
    classification: 'GOVERNMENT_SCHEMES',
    action: 'CANONICAL_CONCEPT',
    targetConceptId: 'CON-SCH-04',
    notes: 'Forms canonical Concept CON-SCH-04: SHG credit framework, 7% interest subvention (4.5% subvention), CGFMU collateral limit up to ₹20L, Lakhpati Didi.',
  },
  {
    id: 'INV-SGA-05',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '5. Deep Dive: RBI Deputy Governors (2025–2026 Transitions)',
    sourceCategory: 'StaticGA',
    classification: 'CURRENT_AFFAIRS_ONLY',
    action: 'EXCLUDED_CURRENT_AFFAIRS',
    notes: 'Transient appointments excluded; statutory 4 DG limit preserved under RBI governance.',
  },
  {
    id: 'INV-SGA-06',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '6. Economic Survey 2025–26 & Union Budget 2026–27 Highlights',
    sourceCategory: 'StaticGA',
    classification: 'CURRENT_AFFAIRS_ONLY',
    action: 'EXCLUDED_CURRENT_AFFAIRS',
    notes: 'Transient annual budget metrics and tax slabs; excluded from static permanent knowledge layer.',
  },
  {
    id: 'INV-SGA-07',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '7. Exam Revision Corner (Appointments)',
    sourceCategory: 'StaticGA',
    classification: 'CURRENT_AFFAIRS_ONLY',
    action: 'EXCLUDED_CURRENT_AFFAIRS',
    notes: 'Transient executive transitions excluded.',
  },
  {
    id: 'INV-SGA-08',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '8. Exam Revision Corner (Banking & SEBI Reforms)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already canonicalized in IIBF Subject (CON-IIBF-04, CON-IIBF-15, CON-IIBF-16).',
  },
  {
    id: 'INV-SGA-09',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '9. Exam Revision Corner (Budget & Survey)',
    sourceCategory: 'StaticGA',
    classification: 'CURRENT_AFFAIRS_ONLY',
    action: 'EXCLUDED_CURRENT_AFFAIRS',
    notes: 'Transient annual budget deficit targets excluded.',
  },
  {
    id: 'INV-SGA-10',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '10. Exam Revision Corner (Insurance & Bima Trinity)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already canonicalized in IIBF Subject (CON-IIBF-13, CON-IIBF-14 in Topic 41).',
  },
  {
    id: 'INV-SGA-11',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '11. Exam Revision Corner (MDBs & Forecasts)',
    sourceCategory: 'StaticGA',
    classification: 'STATIC_GA',
    action: 'CANONICAL_CONCEPT',
    targetConceptId: 'CON-GA-02',
    notes: 'Forms canonical Concept CON-GA-02: MDB headquarters, voting shares, and Bretton Woods architecture.',
  },
  {
    id: 'INV-SGA-12',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '12. Exam Revision Corner (RBI Monetary Tools)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already fully covered in Economics (CON-ECON-06) and IIBF (CON-IIBF-11).',
  },
  {
    id: 'INV-SGA-13',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '13. Exam Revision Corner (Reports & Indices)',
    sourceCategory: 'StaticGA',
    classification: 'STATIC_GA',
    action: 'CANONICAL_CONCEPT',
    targetConceptId: 'CON-GA-03',
    notes: 'Forms canonical Concept CON-GA-03: Global Reports, Indices, and publishing bodies (WIPO, UNDP, WEF, World Bank, IMF).',
  },
  {
    id: 'INV-SGA-14',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '14. Exam Revision Corner (Rural Reforms & DAY-NRLM)',
    sourceCategory: 'StaticGA',
    classification: 'INCORRECT_REQUIRES_CORRECTION',
    action: 'CORRECTED_STATUTORY_FRAMEWORK',
    targetConceptId: 'CON-SCH-05',
    notes: 'Expert correction: rejected fake "VB-G RAM G Act 2025" repeal claim. Synthesized true statutory framework of MGNREGA 2005.',
  },
  {
    id: 'INV-SGA-15',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '15. Exam Revision Corner (Static Banking)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already covered in IIBF (CON-IIBF-17, CON-IIBF-18, CON-IIBF-22).',
  },
  {
    id: 'INV-SGA-16',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '16. Health, Social Justice & Education (104 Schemes)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'EXCLUDED_STUB',
    notes: 'Placeholder header stub without substantive body.',
  },
  {
    id: 'INV-SGA-17',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: "17. India's Real GDP Growth Forecast Matrix (2025–2027)",
    sourceCategory: 'StaticGA',
    classification: 'CURRENT_AFFAIRS_ONLY',
    action: 'EXCLUDED_CURRENT_AFFAIRS',
    notes: 'Transient GDP growth projections excluded.',
  },
  {
    id: 'INV-SGA-18',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '18. Indian Pension Architecture & Regulatory Shifts (NPS, APY, UPS, NPS Vatsalya)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already canonicalized in IIBF (CON-IIBF-16 in Topic 41). APY included in CON-SCH-02.',
  },
  {
    id: 'INV-SGA-19',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '19. Inflation Indices & RBI Target Framework (CPI vs WPI Comparison)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already canonicalized in Economics (CON-ECON-04 in Topic 27).',
  },
  {
    id: 'INV-SGA-20',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '20. Insurance Laws (Amendment) Act, 2024 & IRDAI Profile',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already canonicalized in IIBF (CON-IIBF-13 in Topic 41).',
  },
  {
    id: 'INV-SGA-21',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '21. LAF Corridor Visualised',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already canonicalized in Economics (CON-ECON-06) and IIBF (CON-IIBF-11).',
  },
  {
    id: 'INV-SGA-22',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '22. Macroeconomic Modernization: Base Year Revisions (2026)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'EXCLUDED_STUB',
    notes: 'Placeholder stub; unverified base year 2024 claim excluded per strict epistemic guidelines.',
  },
  {
    id: 'INV-SGA-23',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '23. Master Directory of Multilateral Development Banks (MDBs)',
    sourceCategory: 'StaticGA',
    classification: 'STATIC_GA',
    action: 'CANONICAL_CONCEPT',
    targetConceptId: 'CON-GA-02',
    notes: 'Synthesized into CON-GA-02 (MDBs).',
  },
  {
    id: 'INV-SGA-24',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '24. Master Rate Directory — Current RBI Interest Rate Corridor',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already in Economics Topic 28 & IIBF Topic 40.',
  },
  {
    id: 'INV-SGA-25',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '25. Ministry of Finance & Financial Inclusion (7 Schemes)',
    sourceCategory: 'StaticGA',
    classification: 'GOVERNMENT_SCHEMES',
    action: 'CANONICAL_CONCEPT',
    targetConceptId: 'CON-SCH-02',
    notes: 'Synthesized into CON-SCH-02.',
  },
  {
    id: 'INV-SGA-26',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '26. Monetary Policy Instruments Deep Dive (Direct vs Indirect Tools)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already fully covered in Economics (CON-ECON-06) and IIBF (CON-IIBF-11).',
  },
  {
    id: 'INV-SGA-27',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '27. Monetary Policy Stance & Rate Trajectory (2025–2026)',
    sourceCategory: 'StaticGA',
    classification: 'CURRENT_AFFAIRS_ONLY',
    action: 'EXCLUDED_CURRENT_AFFAIRS',
    notes: 'Transient rate cycles excluded from static layer.',
  },
  {
    id: 'INV-SGA-28',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '28. MSME, Industry & Commerce Schemes (38 Schemes)',
    sourceCategory: 'StaticGA',
    classification: 'GOVERNMENT_SCHEMES',
    action: 'CANONICAL_CONCEPT',
    targetConceptId: 'CON-SCH-03',
    notes: 'Synthesized into CON-SCH-03 (PMMY, PM SVANidhi, PM Vishwakarma).',
  },
  {
    id: 'INV-SGA-29',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '29. Negotiable Instruments (NI) Act, 1881 Core Provisions',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already canonicalized in IIBF (CON-IIBF-17, CON-IIBF-18, CON-IIBF-19).',
  },
  {
    id: 'INV-SGA-30',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '30. Newly Launched Schemes (2024-2026) (1 Schemes)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'EXCLUDED_STUB',
    notes: 'Placeholder stub.',
  },
  {
    id: 'INV-SGA-31',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '31. NRI Account Architecture & Overseas Accounts Matrix',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already canonicalized in IIBF (CON-IIBF-22 in Topic 43).',
  },
  {
    id: 'INV-SGA-32',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '32. Overseas Account Terminology & Money Supply Aggregates',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Nostro/Vostro/Loro and M0–M4 already covered in IIBF (CON-IIBF-22, CON-IIBF-23) and Economics (CON-ECON-05).',
  },
  {
    id: 'INV-SGA-33',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '33. Part 1: Regulatory & Apex Bodies (RBI, SEBI, IRDAI, PFRDA, IFSCA)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already covered in IIBF Topic 38 & Topic 41.',
  },
  {
    id: 'INV-SGA-34',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '34. Part 2: Public Sector Banks (PSB) & Financial Intermediaries',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already covered in IIBF Topic 38 & Topic 42.',
  },
  {
    id: 'INV-SGA-35',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '35. RBI Money Supply Equations',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already canonicalized in Economics (CON-ECON-05) and IIBF (CON-IIBF-23).',
  },
  {
    id: 'INV-SGA-36',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '36. SEBI Capital Markets Overhaul (T+0, MF Lite, F&O Restructuring, CAS)',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already canonicalized in IIBF (CON-IIBF-15 in Topic 41).',
  },
  {
    id: 'INV-SGA-37',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '37. The Bima Trinity — IRDAI\'s Three-Pillar Inclusion Strategy',
    sourceCategory: 'StaticGA',
    classification: 'DUPLICATE_OR_STUB',
    action: 'DEDUPLICATED_INTO_EXISTING',
    notes: 'Already canonicalized in IIBF (CON-IIBF-14 in Topic 41).',
  },
  {
    id: 'INV-SGA-38',
    sourceFile: 'Static_GA_Superbook_Master.md',
    sourceTitle: '38. VB-G RAM G Act 2025 (MGNREGA Replacement) Framework',
    sourceCategory: 'StaticGA',
    classification: 'INCORRECT_REQUIRES_CORRECTION',
    action: 'CORRECTED_STATUTORY_FRAMEWORK',
    targetConceptId: 'CON-SCH-05',
    notes: 'Rejected fictional replacement; preserved statutory MGNREGA 2005 in CON-SCH-05.',
  },
];
